// Package alerts provides CLI commands for operational alerting.
package alerts

import (
	"fmt"
	"io"
	"text/tabwriter"
	"time"

	"github.com/spf13/cobra"

	"github.com/langoai/lango/internal/cli/clihttp"
)

const defaultGatewayAddr = "http://localhost:18789"

// NewAlertsCmd creates the alerts command group.
func NewAlertsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:           "alerts",
		Short:         "View operational alerts",
		SilenceUsage:  true,
		SilenceErrors: true,
		Long: `View operational alerts generated by threshold-based monitoring.

Requires a running Lango server (lango serve) with alerting enabled.

Examples:
  lango alerts list                    # Recent alerts (last 7 days)
  lango alerts list --days=3           # Alerts from last 3 days
  lango alerts summary                 # Alert counts by type`,
		RunE: listRunE,
	}

	cmd.PersistentFlags().String("output", "table", "Output format: table or json")
	cmd.PersistentFlags().String("addr", defaultGatewayAddr, "Gateway address")

	cmd.AddCommand(newListCmd())
	cmd.AddCommand(newSummaryCmd())

	return cmd
}

func newListCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:           "list",
		Short:         "List recent alerts",
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE:          listRunE,
	}
	cmd.Flags().Int("days", 7, "Number of days to look back")
	return cmd
}

func newSummaryCmd() *cobra.Command {
	return &cobra.Command{
		Use:           "summary",
		Short:         "Show alert counts by type",
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE:          summaryRunE,
	}
}

type alertsResponse struct {
	Alerts []alertEntry `json:"alerts"`
	Total  int          `json:"total"`
	Days   int          `json:"days"`
}

type alertEntry struct {
	ID        string                 `json:"id"`
	Type      string                 `json:"type"`
	Actor     string                 `json:"actor"`
	Details   map[string]interface{} `json:"details"`
	Timestamp string                 `json:"timestamp"`
}

func listRunE(cmd *cobra.Command, _ []string) error {
	addr := getAddr(cmd)
	format, err := getOutputFormat(cmd)
	if err != nil {
		return err
	}

	days := 7
	if d, err := cmd.Flags().GetInt("days"); err == nil && d > 0 {
		days = d
	}

	var resp alertsResponse
	if err := clihttp.FetchJSON(addr, fmt.Sprintf("/alerts?days=%d", days), &resp); err != nil {
		return err
	}

	if format == "json" {
		return printJSON(cmd.OutOrStdout(), resp)
	}

	if resp.Total == 0 {
		_, err := fmt.Fprintf(cmd.OutOrStdout(), "No alerts in the last %d day(s).\n", days)
		return err
	}

	if _, err := fmt.Fprintf(cmd.OutOrStdout(), "=== Alerts (last %d day(s)) === [%d total]\n\n", days, resp.Total); err != nil {
		return err
	}

	w := tabwriter.NewWriter(cmd.OutOrStdout(), 0, 4, 2, ' ', 0)
	fmt.Fprintln(w, "TIME\tTYPE\tSEVERITY\tMESSAGE")
	fmt.Fprintln(w, "----\t----\t--------\t-------")
	for _, a := range resp.Alerts {
		severity, _ := a.Details["severity"].(string)
		message, _ := a.Details["message"].(string)
		ts := a.Timestamp
		if t, err := time.Parse(time.RFC3339, a.Timestamp); err == nil {
			ts = t.Local().Format("2006-01-02 15:04:05")
		}
		fmt.Fprintf(w, "%s\t%s\t%s\t%s\n", ts, a.Type, severity, message)
	}
	return w.Flush()
}

func summaryRunE(cmd *cobra.Command, _ []string) error {
	addr := getAddr(cmd)
	format, err := getOutputFormat(cmd)
	if err != nil {
		return err
	}

	var resp alertsResponse
	if err := clihttp.FetchJSON(addr, "/alerts?days=30", &resp); err != nil {
		return err
	}

	// Aggregate by type.
	counts := make(map[string]int)
	for _, a := range resp.Alerts {
		counts[a.Type]++
	}

	if format == "json" {
		return printJSON(cmd.OutOrStdout(), map[string]interface{}{
			"summary":     counts,
			"totalAlerts": resp.Total,
		})
	}

	if len(counts) == 0 {
		_, err := fmt.Fprintln(cmd.OutOrStdout(), "No alerts in the last 30 days.")
		return err
	}

	if _, err := fmt.Fprintf(cmd.OutOrStdout(), "=== Alert Summary (last 30 days) === [%d total]\n\n", resp.Total); err != nil {
		return err
	}

	w := tabwriter.NewWriter(cmd.OutOrStdout(), 0, 4, 2, ' ', 0)
	fmt.Fprintln(w, "TYPE\tCOUNT")
	fmt.Fprintln(w, "----\t-----")
	for typ, count := range counts {
		fmt.Fprintf(w, "%s\t%d\n", typ, count)
	}
	return w.Flush()
}

func getOutputFormat(cmd *cobra.Command) (string, error) {
	return clihttp.ResolveTableOrJSONOutput(cmd)
}

func getAddr(cmd *cobra.Command) string {
	a, _ := cmd.Flags().GetString("addr")
	if a == "" {
		a = defaultGatewayAddr
	}
	return a
}

func printJSON(w io.Writer, v interface{}) error {
	return clihttp.PrintJSON(w, v)
}
