// Code generated by ent, DO NOT EDIT.

package provenanceattribution

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLTE(FieldID, id))
}

// SessionKey applies equality check predicate on the "session_key" field. It's identical to SessionKeyEQ.
func SessionKey(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldSessionKey, v))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldRunID, v))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldWorkspaceID, v))
}

// AuthorType applies equality check predicate on the "author_type" field. It's identical to AuthorTypeEQ.
func AuthorType(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldAuthorType, v))
}

// AuthorID applies equality check predicate on the "author_id" field. It's identical to AuthorIDEQ.
func AuthorID(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldAuthorID, v))
}

// FilePath applies equality check predicate on the "file_path" field. It's identical to FilePathEQ.
func FilePath(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldFilePath, v))
}

// CommitHash applies equality check predicate on the "commit_hash" field. It's identical to CommitHashEQ.
func CommitHash(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldCommitHash, v))
}

// StepID applies equality check predicate on the "step_id" field. It's identical to StepIDEQ.
func StepID(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldStepID, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldSource, v))
}

// LinesAdded applies equality check predicate on the "lines_added" field. It's identical to LinesAddedEQ.
func LinesAdded(v int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldLinesAdded, v))
}

// LinesRemoved applies equality check predicate on the "lines_removed" field. It's identical to LinesRemovedEQ.
func LinesRemoved(v int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldLinesRemoved, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldCreatedAt, v))
}

// SessionKeyEQ applies the EQ predicate on the "session_key" field.
func SessionKeyEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldSessionKey, v))
}

// SessionKeyNEQ applies the NEQ predicate on the "session_key" field.
func SessionKeyNEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNEQ(FieldSessionKey, v))
}

// SessionKeyIn applies the In predicate on the "session_key" field.
func SessionKeyIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIn(FieldSessionKey, vs...))
}

// SessionKeyNotIn applies the NotIn predicate on the "session_key" field.
func SessionKeyNotIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotIn(FieldSessionKey, vs...))
}

// SessionKeyGT applies the GT predicate on the "session_key" field.
func SessionKeyGT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGT(FieldSessionKey, v))
}

// SessionKeyGTE applies the GTE predicate on the "session_key" field.
func SessionKeyGTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGTE(FieldSessionKey, v))
}

// SessionKeyLT applies the LT predicate on the "session_key" field.
func SessionKeyLT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLT(FieldSessionKey, v))
}

// SessionKeyLTE applies the LTE predicate on the "session_key" field.
func SessionKeyLTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLTE(FieldSessionKey, v))
}

// SessionKeyContains applies the Contains predicate on the "session_key" field.
func SessionKeyContains(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContains(FieldSessionKey, v))
}

// SessionKeyHasPrefix applies the HasPrefix predicate on the "session_key" field.
func SessionKeyHasPrefix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasPrefix(FieldSessionKey, v))
}

// SessionKeyHasSuffix applies the HasSuffix predicate on the "session_key" field.
func SessionKeyHasSuffix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasSuffix(FieldSessionKey, v))
}

// SessionKeyEqualFold applies the EqualFold predicate on the "session_key" field.
func SessionKeyEqualFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEqualFold(FieldSessionKey, v))
}

// SessionKeyContainsFold applies the ContainsFold predicate on the "session_key" field.
func SessionKeyContainsFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContainsFold(FieldSessionKey, v))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotIn(FieldRunID, vs...))
}

// RunIDGT applies the GT predicate on the "run_id" field.
func RunIDGT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGT(FieldRunID, v))
}

// RunIDGTE applies the GTE predicate on the "run_id" field.
func RunIDGTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGTE(FieldRunID, v))
}

// RunIDLT applies the LT predicate on the "run_id" field.
func RunIDLT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLT(FieldRunID, v))
}

// RunIDLTE applies the LTE predicate on the "run_id" field.
func RunIDLTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLTE(FieldRunID, v))
}

// RunIDContains applies the Contains predicate on the "run_id" field.
func RunIDContains(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContains(FieldRunID, v))
}

// RunIDHasPrefix applies the HasPrefix predicate on the "run_id" field.
func RunIDHasPrefix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasPrefix(FieldRunID, v))
}

// RunIDHasSuffix applies the HasSuffix predicate on the "run_id" field.
func RunIDHasSuffix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasSuffix(FieldRunID, v))
}

// RunIDIsNil applies the IsNil predicate on the "run_id" field.
func RunIDIsNil() predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIsNull(FieldRunID))
}

// RunIDNotNil applies the NotNil predicate on the "run_id" field.
func RunIDNotNil() predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotNull(FieldRunID))
}

// RunIDEqualFold applies the EqualFold predicate on the "run_id" field.
func RunIDEqualFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEqualFold(FieldRunID, v))
}

// RunIDContainsFold applies the ContainsFold predicate on the "run_id" field.
func RunIDContainsFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContainsFold(FieldRunID, v))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDGT applies the GT predicate on the "workspace_id" field.
func WorkspaceIDGT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGT(FieldWorkspaceID, v))
}

// WorkspaceIDGTE applies the GTE predicate on the "workspace_id" field.
func WorkspaceIDGTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGTE(FieldWorkspaceID, v))
}

// WorkspaceIDLT applies the LT predicate on the "workspace_id" field.
func WorkspaceIDLT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLT(FieldWorkspaceID, v))
}

// WorkspaceIDLTE applies the LTE predicate on the "workspace_id" field.
func WorkspaceIDLTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLTE(FieldWorkspaceID, v))
}

// WorkspaceIDContains applies the Contains predicate on the "workspace_id" field.
func WorkspaceIDContains(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContains(FieldWorkspaceID, v))
}

// WorkspaceIDHasPrefix applies the HasPrefix predicate on the "workspace_id" field.
func WorkspaceIDHasPrefix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasPrefix(FieldWorkspaceID, v))
}

// WorkspaceIDHasSuffix applies the HasSuffix predicate on the "workspace_id" field.
func WorkspaceIDHasSuffix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasSuffix(FieldWorkspaceID, v))
}

// WorkspaceIDIsNil applies the IsNil predicate on the "workspace_id" field.
func WorkspaceIDIsNil() predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIsNull(FieldWorkspaceID))
}

// WorkspaceIDNotNil applies the NotNil predicate on the "workspace_id" field.
func WorkspaceIDNotNil() predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotNull(FieldWorkspaceID))
}

// WorkspaceIDEqualFold applies the EqualFold predicate on the "workspace_id" field.
func WorkspaceIDEqualFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEqualFold(FieldWorkspaceID, v))
}

// WorkspaceIDContainsFold applies the ContainsFold predicate on the "workspace_id" field.
func WorkspaceIDContainsFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContainsFold(FieldWorkspaceID, v))
}

// AuthorTypeEQ applies the EQ predicate on the "author_type" field.
func AuthorTypeEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldAuthorType, v))
}

// AuthorTypeNEQ applies the NEQ predicate on the "author_type" field.
func AuthorTypeNEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNEQ(FieldAuthorType, v))
}

// AuthorTypeIn applies the In predicate on the "author_type" field.
func AuthorTypeIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIn(FieldAuthorType, vs...))
}

// AuthorTypeNotIn applies the NotIn predicate on the "author_type" field.
func AuthorTypeNotIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotIn(FieldAuthorType, vs...))
}

// AuthorTypeGT applies the GT predicate on the "author_type" field.
func AuthorTypeGT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGT(FieldAuthorType, v))
}

// AuthorTypeGTE applies the GTE predicate on the "author_type" field.
func AuthorTypeGTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGTE(FieldAuthorType, v))
}

// AuthorTypeLT applies the LT predicate on the "author_type" field.
func AuthorTypeLT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLT(FieldAuthorType, v))
}

// AuthorTypeLTE applies the LTE predicate on the "author_type" field.
func AuthorTypeLTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLTE(FieldAuthorType, v))
}

// AuthorTypeContains applies the Contains predicate on the "author_type" field.
func AuthorTypeContains(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContains(FieldAuthorType, v))
}

// AuthorTypeHasPrefix applies the HasPrefix predicate on the "author_type" field.
func AuthorTypeHasPrefix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasPrefix(FieldAuthorType, v))
}

// AuthorTypeHasSuffix applies the HasSuffix predicate on the "author_type" field.
func AuthorTypeHasSuffix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasSuffix(FieldAuthorType, v))
}

// AuthorTypeEqualFold applies the EqualFold predicate on the "author_type" field.
func AuthorTypeEqualFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEqualFold(FieldAuthorType, v))
}

// AuthorTypeContainsFold applies the ContainsFold predicate on the "author_type" field.
func AuthorTypeContainsFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContainsFold(FieldAuthorType, v))
}

// AuthorIDEQ applies the EQ predicate on the "author_id" field.
func AuthorIDEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorIDNEQ applies the NEQ predicate on the "author_id" field.
func AuthorIDNEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNEQ(FieldAuthorID, v))
}

// AuthorIDIn applies the In predicate on the "author_id" field.
func AuthorIDIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIn(FieldAuthorID, vs...))
}

// AuthorIDNotIn applies the NotIn predicate on the "author_id" field.
func AuthorIDNotIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotIn(FieldAuthorID, vs...))
}

// AuthorIDGT applies the GT predicate on the "author_id" field.
func AuthorIDGT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGT(FieldAuthorID, v))
}

// AuthorIDGTE applies the GTE predicate on the "author_id" field.
func AuthorIDGTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGTE(FieldAuthorID, v))
}

// AuthorIDLT applies the LT predicate on the "author_id" field.
func AuthorIDLT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLT(FieldAuthorID, v))
}

// AuthorIDLTE applies the LTE predicate on the "author_id" field.
func AuthorIDLTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLTE(FieldAuthorID, v))
}

// AuthorIDContains applies the Contains predicate on the "author_id" field.
func AuthorIDContains(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContains(FieldAuthorID, v))
}

// AuthorIDHasPrefix applies the HasPrefix predicate on the "author_id" field.
func AuthorIDHasPrefix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasPrefix(FieldAuthorID, v))
}

// AuthorIDHasSuffix applies the HasSuffix predicate on the "author_id" field.
func AuthorIDHasSuffix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasSuffix(FieldAuthorID, v))
}

// AuthorIDEqualFold applies the EqualFold predicate on the "author_id" field.
func AuthorIDEqualFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEqualFold(FieldAuthorID, v))
}

// AuthorIDContainsFold applies the ContainsFold predicate on the "author_id" field.
func AuthorIDContainsFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContainsFold(FieldAuthorID, v))
}

// FilePathEQ applies the EQ predicate on the "file_path" field.
func FilePathEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldFilePath, v))
}

// FilePathNEQ applies the NEQ predicate on the "file_path" field.
func FilePathNEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNEQ(FieldFilePath, v))
}

// FilePathIn applies the In predicate on the "file_path" field.
func FilePathIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIn(FieldFilePath, vs...))
}

// FilePathNotIn applies the NotIn predicate on the "file_path" field.
func FilePathNotIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotIn(FieldFilePath, vs...))
}

// FilePathGT applies the GT predicate on the "file_path" field.
func FilePathGT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGT(FieldFilePath, v))
}

// FilePathGTE applies the GTE predicate on the "file_path" field.
func FilePathGTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGTE(FieldFilePath, v))
}

// FilePathLT applies the LT predicate on the "file_path" field.
func FilePathLT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLT(FieldFilePath, v))
}

// FilePathLTE applies the LTE predicate on the "file_path" field.
func FilePathLTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLTE(FieldFilePath, v))
}

// FilePathContains applies the Contains predicate on the "file_path" field.
func FilePathContains(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContains(FieldFilePath, v))
}

// FilePathHasPrefix applies the HasPrefix predicate on the "file_path" field.
func FilePathHasPrefix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasPrefix(FieldFilePath, v))
}

// FilePathHasSuffix applies the HasSuffix predicate on the "file_path" field.
func FilePathHasSuffix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasSuffix(FieldFilePath, v))
}

// FilePathIsNil applies the IsNil predicate on the "file_path" field.
func FilePathIsNil() predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIsNull(FieldFilePath))
}

// FilePathNotNil applies the NotNil predicate on the "file_path" field.
func FilePathNotNil() predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotNull(FieldFilePath))
}

// FilePathEqualFold applies the EqualFold predicate on the "file_path" field.
func FilePathEqualFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEqualFold(FieldFilePath, v))
}

// FilePathContainsFold applies the ContainsFold predicate on the "file_path" field.
func FilePathContainsFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContainsFold(FieldFilePath, v))
}

// CommitHashEQ applies the EQ predicate on the "commit_hash" field.
func CommitHashEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldCommitHash, v))
}

// CommitHashNEQ applies the NEQ predicate on the "commit_hash" field.
func CommitHashNEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNEQ(FieldCommitHash, v))
}

// CommitHashIn applies the In predicate on the "commit_hash" field.
func CommitHashIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIn(FieldCommitHash, vs...))
}

// CommitHashNotIn applies the NotIn predicate on the "commit_hash" field.
func CommitHashNotIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotIn(FieldCommitHash, vs...))
}

// CommitHashGT applies the GT predicate on the "commit_hash" field.
func CommitHashGT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGT(FieldCommitHash, v))
}

// CommitHashGTE applies the GTE predicate on the "commit_hash" field.
func CommitHashGTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGTE(FieldCommitHash, v))
}

// CommitHashLT applies the LT predicate on the "commit_hash" field.
func CommitHashLT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLT(FieldCommitHash, v))
}

// CommitHashLTE applies the LTE predicate on the "commit_hash" field.
func CommitHashLTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLTE(FieldCommitHash, v))
}

// CommitHashContains applies the Contains predicate on the "commit_hash" field.
func CommitHashContains(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContains(FieldCommitHash, v))
}

// CommitHashHasPrefix applies the HasPrefix predicate on the "commit_hash" field.
func CommitHashHasPrefix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasPrefix(FieldCommitHash, v))
}

// CommitHashHasSuffix applies the HasSuffix predicate on the "commit_hash" field.
func CommitHashHasSuffix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasSuffix(FieldCommitHash, v))
}

// CommitHashIsNil applies the IsNil predicate on the "commit_hash" field.
func CommitHashIsNil() predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIsNull(FieldCommitHash))
}

// CommitHashNotNil applies the NotNil predicate on the "commit_hash" field.
func CommitHashNotNil() predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotNull(FieldCommitHash))
}

// CommitHashEqualFold applies the EqualFold predicate on the "commit_hash" field.
func CommitHashEqualFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEqualFold(FieldCommitHash, v))
}

// CommitHashContainsFold applies the ContainsFold predicate on the "commit_hash" field.
func CommitHashContainsFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContainsFold(FieldCommitHash, v))
}

// StepIDEQ applies the EQ predicate on the "step_id" field.
func StepIDEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldStepID, v))
}

// StepIDNEQ applies the NEQ predicate on the "step_id" field.
func StepIDNEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNEQ(FieldStepID, v))
}

// StepIDIn applies the In predicate on the "step_id" field.
func StepIDIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIn(FieldStepID, vs...))
}

// StepIDNotIn applies the NotIn predicate on the "step_id" field.
func StepIDNotIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotIn(FieldStepID, vs...))
}

// StepIDGT applies the GT predicate on the "step_id" field.
func StepIDGT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGT(FieldStepID, v))
}

// StepIDGTE applies the GTE predicate on the "step_id" field.
func StepIDGTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGTE(FieldStepID, v))
}

// StepIDLT applies the LT predicate on the "step_id" field.
func StepIDLT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLT(FieldStepID, v))
}

// StepIDLTE applies the LTE predicate on the "step_id" field.
func StepIDLTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLTE(FieldStepID, v))
}

// StepIDContains applies the Contains predicate on the "step_id" field.
func StepIDContains(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContains(FieldStepID, v))
}

// StepIDHasPrefix applies the HasPrefix predicate on the "step_id" field.
func StepIDHasPrefix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasPrefix(FieldStepID, v))
}

// StepIDHasSuffix applies the HasSuffix predicate on the "step_id" field.
func StepIDHasSuffix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasSuffix(FieldStepID, v))
}

// StepIDIsNil applies the IsNil predicate on the "step_id" field.
func StepIDIsNil() predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIsNull(FieldStepID))
}

// StepIDNotNil applies the NotNil predicate on the "step_id" field.
func StepIDNotNil() predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotNull(FieldStepID))
}

// StepIDEqualFold applies the EqualFold predicate on the "step_id" field.
func StepIDEqualFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEqualFold(FieldStepID, v))
}

// StepIDContainsFold applies the ContainsFold predicate on the "step_id" field.
func StepIDContainsFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContainsFold(FieldStepID, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldContainsFold(FieldSource, v))
}

// LinesAddedEQ applies the EQ predicate on the "lines_added" field.
func LinesAddedEQ(v int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldLinesAdded, v))
}

// LinesAddedNEQ applies the NEQ predicate on the "lines_added" field.
func LinesAddedNEQ(v int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNEQ(FieldLinesAdded, v))
}

// LinesAddedIn applies the In predicate on the "lines_added" field.
func LinesAddedIn(vs ...int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIn(FieldLinesAdded, vs...))
}

// LinesAddedNotIn applies the NotIn predicate on the "lines_added" field.
func LinesAddedNotIn(vs ...int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotIn(FieldLinesAdded, vs...))
}

// LinesAddedGT applies the GT predicate on the "lines_added" field.
func LinesAddedGT(v int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGT(FieldLinesAdded, v))
}

// LinesAddedGTE applies the GTE predicate on the "lines_added" field.
func LinesAddedGTE(v int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGTE(FieldLinesAdded, v))
}

// LinesAddedLT applies the LT predicate on the "lines_added" field.
func LinesAddedLT(v int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLT(FieldLinesAdded, v))
}

// LinesAddedLTE applies the LTE predicate on the "lines_added" field.
func LinesAddedLTE(v int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLTE(FieldLinesAdded, v))
}

// LinesRemovedEQ applies the EQ predicate on the "lines_removed" field.
func LinesRemovedEQ(v int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldLinesRemoved, v))
}

// LinesRemovedNEQ applies the NEQ predicate on the "lines_removed" field.
func LinesRemovedNEQ(v int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNEQ(FieldLinesRemoved, v))
}

// LinesRemovedIn applies the In predicate on the "lines_removed" field.
func LinesRemovedIn(vs ...int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIn(FieldLinesRemoved, vs...))
}

// LinesRemovedNotIn applies the NotIn predicate on the "lines_removed" field.
func LinesRemovedNotIn(vs ...int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotIn(FieldLinesRemoved, vs...))
}

// LinesRemovedGT applies the GT predicate on the "lines_removed" field.
func LinesRemovedGT(v int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGT(FieldLinesRemoved, v))
}

// LinesRemovedGTE applies the GTE predicate on the "lines_removed" field.
func LinesRemovedGTE(v int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGTE(FieldLinesRemoved, v))
}

// LinesRemovedLT applies the LT predicate on the "lines_removed" field.
func LinesRemovedLT(v int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLT(FieldLinesRemoved, v))
}

// LinesRemovedLTE applies the LTE predicate on the "lines_removed" field.
func LinesRemovedLTE(v int) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLTE(FieldLinesRemoved, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProvenanceAttribution) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProvenanceAttribution) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProvenanceAttribution) predicate.ProvenanceAttribution {
	return predicate.ProvenanceAttribution(sql.NotPredicates(p))
}
