// Code generated by ent, DO NOT EDIT.

package missionexecutionlink

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the missionexecutionlink type in the database.
	Label = "mission_execution_link"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMissionID holds the string denoting the mission_id field in the database.
	FieldMissionID = "mission_id"
	// FieldExecutionKind holds the string denoting the execution_kind field in the database.
	FieldExecutionKind = "execution_kind"
	// FieldExecutionRef holds the string denoting the execution_ref field in the database.
	FieldExecutionRef = "execution_ref"
	// FieldLinkRole holds the string denoting the link_role field in the database.
	FieldLinkRole = "link_role"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the missionexecutionlink in the database.
	Table = "mission_execution_links"
)

// Columns holds all SQL columns for missionexecutionlink fields.
var Columns = []string{
	FieldID,
	FieldMissionID,
	FieldExecutionKind,
	FieldExecutionRef,
	FieldLinkRole,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ExecutionRefValidator is a validator for the "execution_ref" field. It is called by the builders before save.
	ExecutionRefValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ExecutionKind defines the type for the "execution_kind" enum field.
type ExecutionKind string

// ExecutionKind values.
const (
	ExecutionKindRunledgerRun    ExecutionKind = "runledger_run"
	ExecutionKindTaskOsExecution ExecutionKind = "task_os_execution"
)

func (ek ExecutionKind) String() string {
	return string(ek)
}

// ExecutionKindValidator is a validator for the "execution_kind" field enum values. It is called by the builders before save.
func ExecutionKindValidator(ek ExecutionKind) error {
	switch ek {
	case ExecutionKindRunledgerRun, ExecutionKindTaskOsExecution:
		return nil
	default:
		return fmt.Errorf("missionexecutionlink: invalid enum value for execution_kind field: %q", ek)
	}
}

// LinkRole defines the type for the "link_role" enum field.
type LinkRole string

// LinkRolePrimary is the default value of the LinkRole enum.
const DefaultLinkRole = LinkRolePrimary

// LinkRole values.
const (
	LinkRolePrimary  LinkRole = "primary"
	LinkRoleFollowup LinkRole = "followup"
	LinkRoleRetry    LinkRole = "retry"
	LinkRoleResearch LinkRole = "research"
	LinkRoleDraft    LinkRole = "draft"
	LinkRoleHandoff  LinkRole = "handoff"
)

func (lr LinkRole) String() string {
	return string(lr)
}

// LinkRoleValidator is a validator for the "link_role" field enum values. It is called by the builders before save.
func LinkRoleValidator(lr LinkRole) error {
	switch lr {
	case LinkRolePrimary, LinkRoleFollowup, LinkRoleRetry, LinkRoleResearch, LinkRoleDraft, LinkRoleHandoff:
		return nil
	default:
		return fmt.Errorf("missionexecutionlink: invalid enum value for link_role field: %q", lr)
	}
}

// OrderOption defines the ordering options for the MissionExecutionLink queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMissionID orders the results by the mission_id field.
func ByMissionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMissionID, opts...).ToFunc()
}

// ByExecutionKind orders the results by the execution_kind field.
func ByExecutionKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutionKind, opts...).ToFunc()
}

// ByExecutionRef orders the results by the execution_ref field.
func ByExecutionRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutionRef, opts...).ToFunc()
}

// ByLinkRole orders the results by the link_role field.
func ByLinkRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkRole, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
