// Code generated by ent, DO NOT EDIT.

package missionexecutionlink

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldLTE(FieldID, id))
}

// MissionID applies equality check predicate on the "mission_id" field. It's identical to MissionIDEQ.
func MissionID(v uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldEQ(FieldMissionID, v))
}

// ExecutionRef applies equality check predicate on the "execution_ref" field. It's identical to ExecutionRefEQ.
func ExecutionRef(v string) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldEQ(FieldExecutionRef, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldEQ(FieldCreatedAt, v))
}

// MissionIDEQ applies the EQ predicate on the "mission_id" field.
func MissionIDEQ(v uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldEQ(FieldMissionID, v))
}

// MissionIDNEQ applies the NEQ predicate on the "mission_id" field.
func MissionIDNEQ(v uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldNEQ(FieldMissionID, v))
}

// MissionIDIn applies the In predicate on the "mission_id" field.
func MissionIDIn(vs ...uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldIn(FieldMissionID, vs...))
}

// MissionIDNotIn applies the NotIn predicate on the "mission_id" field.
func MissionIDNotIn(vs ...uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldNotIn(FieldMissionID, vs...))
}

// MissionIDGT applies the GT predicate on the "mission_id" field.
func MissionIDGT(v uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldGT(FieldMissionID, v))
}

// MissionIDGTE applies the GTE predicate on the "mission_id" field.
func MissionIDGTE(v uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldGTE(FieldMissionID, v))
}

// MissionIDLT applies the LT predicate on the "mission_id" field.
func MissionIDLT(v uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldLT(FieldMissionID, v))
}

// MissionIDLTE applies the LTE predicate on the "mission_id" field.
func MissionIDLTE(v uuid.UUID) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldLTE(FieldMissionID, v))
}

// ExecutionKindEQ applies the EQ predicate on the "execution_kind" field.
func ExecutionKindEQ(v ExecutionKind) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldEQ(FieldExecutionKind, v))
}

// ExecutionKindNEQ applies the NEQ predicate on the "execution_kind" field.
func ExecutionKindNEQ(v ExecutionKind) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldNEQ(FieldExecutionKind, v))
}

// ExecutionKindIn applies the In predicate on the "execution_kind" field.
func ExecutionKindIn(vs ...ExecutionKind) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldIn(FieldExecutionKind, vs...))
}

// ExecutionKindNotIn applies the NotIn predicate on the "execution_kind" field.
func ExecutionKindNotIn(vs ...ExecutionKind) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldNotIn(FieldExecutionKind, vs...))
}

// ExecutionRefEQ applies the EQ predicate on the "execution_ref" field.
func ExecutionRefEQ(v string) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldEQ(FieldExecutionRef, v))
}

// ExecutionRefNEQ applies the NEQ predicate on the "execution_ref" field.
func ExecutionRefNEQ(v string) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldNEQ(FieldExecutionRef, v))
}

// ExecutionRefIn applies the In predicate on the "execution_ref" field.
func ExecutionRefIn(vs ...string) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldIn(FieldExecutionRef, vs...))
}

// ExecutionRefNotIn applies the NotIn predicate on the "execution_ref" field.
func ExecutionRefNotIn(vs ...string) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldNotIn(FieldExecutionRef, vs...))
}

// ExecutionRefGT applies the GT predicate on the "execution_ref" field.
func ExecutionRefGT(v string) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldGT(FieldExecutionRef, v))
}

// ExecutionRefGTE applies the GTE predicate on the "execution_ref" field.
func ExecutionRefGTE(v string) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldGTE(FieldExecutionRef, v))
}

// ExecutionRefLT applies the LT predicate on the "execution_ref" field.
func ExecutionRefLT(v string) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldLT(FieldExecutionRef, v))
}

// ExecutionRefLTE applies the LTE predicate on the "execution_ref" field.
func ExecutionRefLTE(v string) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldLTE(FieldExecutionRef, v))
}

// ExecutionRefContains applies the Contains predicate on the "execution_ref" field.
func ExecutionRefContains(v string) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldContains(FieldExecutionRef, v))
}

// ExecutionRefHasPrefix applies the HasPrefix predicate on the "execution_ref" field.
func ExecutionRefHasPrefix(v string) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldHasPrefix(FieldExecutionRef, v))
}

// ExecutionRefHasSuffix applies the HasSuffix predicate on the "execution_ref" field.
func ExecutionRefHasSuffix(v string) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldHasSuffix(FieldExecutionRef, v))
}

// ExecutionRefEqualFold applies the EqualFold predicate on the "execution_ref" field.
func ExecutionRefEqualFold(v string) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldEqualFold(FieldExecutionRef, v))
}

// ExecutionRefContainsFold applies the ContainsFold predicate on the "execution_ref" field.
func ExecutionRefContainsFold(v string) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldContainsFold(FieldExecutionRef, v))
}

// LinkRoleEQ applies the EQ predicate on the "link_role" field.
func LinkRoleEQ(v LinkRole) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldEQ(FieldLinkRole, v))
}

// LinkRoleNEQ applies the NEQ predicate on the "link_role" field.
func LinkRoleNEQ(v LinkRole) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldNEQ(FieldLinkRole, v))
}

// LinkRoleIn applies the In predicate on the "link_role" field.
func LinkRoleIn(vs ...LinkRole) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldIn(FieldLinkRole, vs...))
}

// LinkRoleNotIn applies the NotIn predicate on the "link_role" field.
func LinkRoleNotIn(vs ...LinkRole) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldNotIn(FieldLinkRole, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MissionExecutionLink) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MissionExecutionLink) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MissionExecutionLink) predicate.MissionExecutionLink {
	return predicate.MissionExecutionLink(sql.NotPredicates(p))
}
