// Code generated by ent, DO NOT EDIT.

package turntrace

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLTE(FieldID, id))
}

// TraceID applies equality check predicate on the "trace_id" field. It's identical to TraceIDEQ.
func TraceID(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldTraceID, v))
}

// SessionKey applies equality check predicate on the "session_key" field. It's identical to SessionKeyEQ.
func SessionKey(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldSessionKey, v))
}

// Entrypoint applies equality check predicate on the "entrypoint" field. It's identical to EntrypointEQ.
func Entrypoint(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldEntrypoint, v))
}

// Outcome applies equality check predicate on the "outcome" field. It's identical to OutcomeEQ.
func Outcome(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldOutcome, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldErrorCode, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldSummary, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldEndedAt, v))
}

// TraceIDEQ applies the EQ predicate on the "trace_id" field.
func TraceIDEQ(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldTraceID, v))
}

// TraceIDNEQ applies the NEQ predicate on the "trace_id" field.
func TraceIDNEQ(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNEQ(FieldTraceID, v))
}

// TraceIDIn applies the In predicate on the "trace_id" field.
func TraceIDIn(vs ...string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldIn(FieldTraceID, vs...))
}

// TraceIDNotIn applies the NotIn predicate on the "trace_id" field.
func TraceIDNotIn(vs ...string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNotIn(FieldTraceID, vs...))
}

// TraceIDGT applies the GT predicate on the "trace_id" field.
func TraceIDGT(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGT(FieldTraceID, v))
}

// TraceIDGTE applies the GTE predicate on the "trace_id" field.
func TraceIDGTE(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGTE(FieldTraceID, v))
}

// TraceIDLT applies the LT predicate on the "trace_id" field.
func TraceIDLT(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLT(FieldTraceID, v))
}

// TraceIDLTE applies the LTE predicate on the "trace_id" field.
func TraceIDLTE(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLTE(FieldTraceID, v))
}

// TraceIDContains applies the Contains predicate on the "trace_id" field.
func TraceIDContains(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldContains(FieldTraceID, v))
}

// TraceIDHasPrefix applies the HasPrefix predicate on the "trace_id" field.
func TraceIDHasPrefix(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldHasPrefix(FieldTraceID, v))
}

// TraceIDHasSuffix applies the HasSuffix predicate on the "trace_id" field.
func TraceIDHasSuffix(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldHasSuffix(FieldTraceID, v))
}

// TraceIDEqualFold applies the EqualFold predicate on the "trace_id" field.
func TraceIDEqualFold(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEqualFold(FieldTraceID, v))
}

// TraceIDContainsFold applies the ContainsFold predicate on the "trace_id" field.
func TraceIDContainsFold(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldContainsFold(FieldTraceID, v))
}

// SessionKeyEQ applies the EQ predicate on the "session_key" field.
func SessionKeyEQ(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldSessionKey, v))
}

// SessionKeyNEQ applies the NEQ predicate on the "session_key" field.
func SessionKeyNEQ(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNEQ(FieldSessionKey, v))
}

// SessionKeyIn applies the In predicate on the "session_key" field.
func SessionKeyIn(vs ...string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldIn(FieldSessionKey, vs...))
}

// SessionKeyNotIn applies the NotIn predicate on the "session_key" field.
func SessionKeyNotIn(vs ...string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNotIn(FieldSessionKey, vs...))
}

// SessionKeyGT applies the GT predicate on the "session_key" field.
func SessionKeyGT(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGT(FieldSessionKey, v))
}

// SessionKeyGTE applies the GTE predicate on the "session_key" field.
func SessionKeyGTE(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGTE(FieldSessionKey, v))
}

// SessionKeyLT applies the LT predicate on the "session_key" field.
func SessionKeyLT(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLT(FieldSessionKey, v))
}

// SessionKeyLTE applies the LTE predicate on the "session_key" field.
func SessionKeyLTE(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLTE(FieldSessionKey, v))
}

// SessionKeyContains applies the Contains predicate on the "session_key" field.
func SessionKeyContains(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldContains(FieldSessionKey, v))
}

// SessionKeyHasPrefix applies the HasPrefix predicate on the "session_key" field.
func SessionKeyHasPrefix(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldHasPrefix(FieldSessionKey, v))
}

// SessionKeyHasSuffix applies the HasSuffix predicate on the "session_key" field.
func SessionKeyHasSuffix(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldHasSuffix(FieldSessionKey, v))
}

// SessionKeyEqualFold applies the EqualFold predicate on the "session_key" field.
func SessionKeyEqualFold(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEqualFold(FieldSessionKey, v))
}

// SessionKeyContainsFold applies the ContainsFold predicate on the "session_key" field.
func SessionKeyContainsFold(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldContainsFold(FieldSessionKey, v))
}

// EntrypointEQ applies the EQ predicate on the "entrypoint" field.
func EntrypointEQ(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldEntrypoint, v))
}

// EntrypointNEQ applies the NEQ predicate on the "entrypoint" field.
func EntrypointNEQ(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNEQ(FieldEntrypoint, v))
}

// EntrypointIn applies the In predicate on the "entrypoint" field.
func EntrypointIn(vs ...string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldIn(FieldEntrypoint, vs...))
}

// EntrypointNotIn applies the NotIn predicate on the "entrypoint" field.
func EntrypointNotIn(vs ...string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNotIn(FieldEntrypoint, vs...))
}

// EntrypointGT applies the GT predicate on the "entrypoint" field.
func EntrypointGT(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGT(FieldEntrypoint, v))
}

// EntrypointGTE applies the GTE predicate on the "entrypoint" field.
func EntrypointGTE(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGTE(FieldEntrypoint, v))
}

// EntrypointLT applies the LT predicate on the "entrypoint" field.
func EntrypointLT(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLT(FieldEntrypoint, v))
}

// EntrypointLTE applies the LTE predicate on the "entrypoint" field.
func EntrypointLTE(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLTE(FieldEntrypoint, v))
}

// EntrypointContains applies the Contains predicate on the "entrypoint" field.
func EntrypointContains(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldContains(FieldEntrypoint, v))
}

// EntrypointHasPrefix applies the HasPrefix predicate on the "entrypoint" field.
func EntrypointHasPrefix(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldHasPrefix(FieldEntrypoint, v))
}

// EntrypointHasSuffix applies the HasSuffix predicate on the "entrypoint" field.
func EntrypointHasSuffix(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldHasSuffix(FieldEntrypoint, v))
}

// EntrypointEqualFold applies the EqualFold predicate on the "entrypoint" field.
func EntrypointEqualFold(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEqualFold(FieldEntrypoint, v))
}

// EntrypointContainsFold applies the ContainsFold predicate on the "entrypoint" field.
func EntrypointContainsFold(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldContainsFold(FieldEntrypoint, v))
}

// OutcomeEQ applies the EQ predicate on the "outcome" field.
func OutcomeEQ(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldOutcome, v))
}

// OutcomeNEQ applies the NEQ predicate on the "outcome" field.
func OutcomeNEQ(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNEQ(FieldOutcome, v))
}

// OutcomeIn applies the In predicate on the "outcome" field.
func OutcomeIn(vs ...string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldIn(FieldOutcome, vs...))
}

// OutcomeNotIn applies the NotIn predicate on the "outcome" field.
func OutcomeNotIn(vs ...string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNotIn(FieldOutcome, vs...))
}

// OutcomeGT applies the GT predicate on the "outcome" field.
func OutcomeGT(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGT(FieldOutcome, v))
}

// OutcomeGTE applies the GTE predicate on the "outcome" field.
func OutcomeGTE(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGTE(FieldOutcome, v))
}

// OutcomeLT applies the LT predicate on the "outcome" field.
func OutcomeLT(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLT(FieldOutcome, v))
}

// OutcomeLTE applies the LTE predicate on the "outcome" field.
func OutcomeLTE(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLTE(FieldOutcome, v))
}

// OutcomeContains applies the Contains predicate on the "outcome" field.
func OutcomeContains(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldContains(FieldOutcome, v))
}

// OutcomeHasPrefix applies the HasPrefix predicate on the "outcome" field.
func OutcomeHasPrefix(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldHasPrefix(FieldOutcome, v))
}

// OutcomeHasSuffix applies the HasSuffix predicate on the "outcome" field.
func OutcomeHasSuffix(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldHasSuffix(FieldOutcome, v))
}

// OutcomeEqualFold applies the EqualFold predicate on the "outcome" field.
func OutcomeEqualFold(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEqualFold(FieldOutcome, v))
}

// OutcomeContainsFold applies the ContainsFold predicate on the "outcome" field.
func OutcomeContainsFold(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldContainsFold(FieldOutcome, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldContainsFold(FieldErrorCode, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryIsNil applies the IsNil predicate on the "summary" field.
func SummaryIsNil() predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldIsNull(FieldSummary))
}

// SummaryNotNil applies the NotNil predicate on the "summary" field.
func SummaryNotNil() predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNotNull(FieldSummary))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldContainsFold(FieldSummary, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLTE(FieldStartedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.TurnTrace {
	return predicate.TurnTrace(sql.FieldNotNull(FieldEndedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TurnTrace) predicate.TurnTrace {
	return predicate.TurnTrace(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TurnTrace) predicate.TurnTrace {
	return predicate.TurnTrace(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TurnTrace) predicate.TurnTrace {
	return predicate.TurnTrace(sql.NotPredicates(p))
}
