// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/actionlog"
)

// ActionLog is the model entity for the ActionLog schema.
type ActionLog struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ActionName holds the value of the "action_name" field.
	ActionName string `json:"action_name,omitempty"`
	// Principal holds the value of the "principal" field.
	Principal string `json:"principal,omitempty"`
	// Params holds the value of the "params" field.
	Params map[string]string `json:"params,omitempty"`
	// Status holds the value of the "status" field.
	Status actionlog.Status `json:"status,omitempty"`
	// Effects holds the value of the "effects" field.
	Effects map[string]interface{} `json:"effects,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ActionLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case actionlog.FieldParams, actionlog.FieldEffects:
			values[i] = new([]byte)
		case actionlog.FieldActionName, actionlog.FieldPrincipal, actionlog.FieldStatus, actionlog.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case actionlog.FieldStartedAt, actionlog.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case actionlog.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ActionLog fields.
func (_m *ActionLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case actionlog.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case actionlog.FieldActionName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action_name", values[i])
			} else if value.Valid {
				_m.ActionName = value.String
			}
		case actionlog.FieldPrincipal:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field principal", values[i])
			} else if value.Valid {
				_m.Principal = value.String
			}
		case actionlog.FieldParams:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field params", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Params); err != nil {
					return fmt.Errorf("unmarshal field params: %w", err)
				}
			}
		case actionlog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = actionlog.Status(value.String)
			}
		case actionlog.FieldEffects:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field effects", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Effects); err != nil {
					return fmt.Errorf("unmarshal field effects: %w", err)
				}
			}
		case actionlog.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case actionlog.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case actionlog.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ActionLog.
// This includes values selected through modifiers, order, etc.
func (_m *ActionLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ActionLog.
// Note that you need to call ActionLog.Unwrap() before calling this method if this ActionLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ActionLog) Update() *ActionLogUpdateOne {
	return NewActionLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ActionLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ActionLog) Unwrap() *ActionLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ActionLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ActionLog) String() string {
	var builder strings.Builder
	builder.WriteString("ActionLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("action_name=")
	builder.WriteString(_m.ActionName)
	builder.WriteString(", ")
	builder.WriteString("principal=")
	builder.WriteString(_m.Principal)
	builder.WriteString(", ")
	builder.WriteString("params=")
	builder.WriteString(fmt.Sprintf("%v", _m.Params))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("effects=")
	builder.WriteString(fmt.Sprintf("%v", _m.Effects))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ActionLogs is a parsable slice of ActionLog.
type ActionLogs []*ActionLog
