// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/entityproperty"
)

// EntityPropertyCreate is the builder for creating a EntityProperty entity.
type EntityPropertyCreate struct {
	config
	mutation *EntityPropertyMutation
	hooks    []Hook
}

// SetEntityID sets the "entity_id" field.
func (_c *EntityPropertyCreate) SetEntityID(v string) *EntityPropertyCreate {
	_c.mutation.SetEntityID(v)
	return _c
}

// SetEntityType sets the "entity_type" field.
func (_c *EntityPropertyCreate) SetEntityType(v string) *EntityPropertyCreate {
	_c.mutation.SetEntityType(v)
	return _c
}

// SetProperty sets the "property" field.
func (_c *EntityPropertyCreate) SetProperty(v string) *EntityPropertyCreate {
	_c.mutation.SetProperty(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *EntityPropertyCreate) SetValue(v string) *EntityPropertyCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetValueType sets the "value_type" field.
func (_c *EntityPropertyCreate) SetValueType(v string) *EntityPropertyCreate {
	_c.mutation.SetValueType(v)
	return _c
}

// SetNillableValueType sets the "value_type" field if the given value is not nil.
func (_c *EntityPropertyCreate) SetNillableValueType(v *string) *EntityPropertyCreate {
	if v != nil {
		_c.SetValueType(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EntityPropertyCreate) SetCreatedAt(v time.Time) *EntityPropertyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EntityPropertyCreate) SetNillableCreatedAt(v *time.Time) *EntityPropertyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EntityPropertyCreate) SetUpdatedAt(v time.Time) *EntityPropertyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EntityPropertyCreate) SetNillableUpdatedAt(v *time.Time) *EntityPropertyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EntityPropertyCreate) SetID(v uuid.UUID) *EntityPropertyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EntityPropertyCreate) SetNillableID(v *uuid.UUID) *EntityPropertyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the EntityPropertyMutation object of the builder.
func (_c *EntityPropertyCreate) Mutation() *EntityPropertyMutation {
	return _c.mutation
}

// Save creates the EntityProperty in the database.
func (_c *EntityPropertyCreate) Save(ctx context.Context) (*EntityProperty, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EntityPropertyCreate) SaveX(ctx context.Context) *EntityProperty {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityPropertyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityPropertyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EntityPropertyCreate) defaults() {
	if _, ok := _c.mutation.ValueType(); !ok {
		v := entityproperty.DefaultValueType
		_c.mutation.SetValueType(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := entityproperty.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := entityproperty.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := entityproperty.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EntityPropertyCreate) check() error {
	if _, ok := _c.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "EntityProperty.entity_id"`)}
	}
	if v, ok := _c.mutation.EntityID(); ok {
		if err := entityproperty.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "EntityProperty.entity_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EntityType(); !ok {
		return &ValidationError{Name: "entity_type", err: errors.New(`ent: missing required field "EntityProperty.entity_type"`)}
	}
	if v, ok := _c.mutation.EntityType(); ok {
		if err := entityproperty.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "EntityProperty.entity_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Property(); !ok {
		return &ValidationError{Name: "property", err: errors.New(`ent: missing required field "EntityProperty.property"`)}
	}
	if v, ok := _c.mutation.Property(); ok {
		if err := entityproperty.PropertyValidator(v); err != nil {
			return &ValidationError{Name: "property", err: fmt.Errorf(`ent: validator failed for field "EntityProperty.property": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "EntityProperty.value"`)}
	}
	if _, ok := _c.mutation.ValueType(); !ok {
		return &ValidationError{Name: "value_type", err: errors.New(`ent: missing required field "EntityProperty.value_type"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EntityProperty.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EntityProperty.updated_at"`)}
	}
	return nil
}

func (_c *EntityPropertyCreate) sqlSave(ctx context.Context) (*EntityProperty, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EntityPropertyCreate) createSpec() (*EntityProperty, *sqlgraph.CreateSpec) {
	var (
		_node = &EntityProperty{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entityproperty.Table, sqlgraph.NewFieldSpec(entityproperty.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.EntityID(); ok {
		_spec.SetField(entityproperty.FieldEntityID, field.TypeString, value)
		_node.EntityID = value
	}
	if value, ok := _c.mutation.EntityType(); ok {
		_spec.SetField(entityproperty.FieldEntityType, field.TypeString, value)
		_node.EntityType = value
	}
	if value, ok := _c.mutation.Property(); ok {
		_spec.SetField(entityproperty.FieldProperty, field.TypeString, value)
		_node.Property = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(entityproperty.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.ValueType(); ok {
		_spec.SetField(entityproperty.FieldValueType, field.TypeString, value)
		_node.ValueType = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(entityproperty.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(entityproperty.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// EntityPropertyCreateBulk is the builder for creating many EntityProperty entities in bulk.
type EntityPropertyCreateBulk struct {
	config
	err      error
	builders []*EntityPropertyCreate
}

// Save creates the EntityProperty entities in the database.
func (_c *EntityPropertyCreateBulk) Save(ctx context.Context) ([]*EntityProperty, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EntityProperty, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntityPropertyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EntityPropertyCreateBulk) SaveX(ctx context.Context) []*EntityProperty {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityPropertyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityPropertyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
