// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/entityalias"
)

// EntityAliasCreate is the builder for creating a EntityAlias entity.
type EntityAliasCreate struct {
	config
	mutation *EntityAliasMutation
	hooks    []Hook
}

// SetRawID sets the "raw_id" field.
func (_c *EntityAliasCreate) SetRawID(v string) *EntityAliasCreate {
	_c.mutation.SetRawID(v)
	return _c
}

// SetCanonicalID sets the "canonical_id" field.
func (_c *EntityAliasCreate) SetCanonicalID(v string) *EntityAliasCreate {
	_c.mutation.SetCanonicalID(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *EntityAliasCreate) SetSource(v string) *EntityAliasCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *EntityAliasCreate) SetNillableSource(v *string) *EntityAliasCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EntityAliasCreate) SetCreatedAt(v time.Time) *EntityAliasCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EntityAliasCreate) SetNillableCreatedAt(v *time.Time) *EntityAliasCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EntityAliasCreate) SetID(v uuid.UUID) *EntityAliasCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EntityAliasCreate) SetNillableID(v *uuid.UUID) *EntityAliasCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the EntityAliasMutation object of the builder.
func (_c *EntityAliasCreate) Mutation() *EntityAliasMutation {
	return _c.mutation
}

// Save creates the EntityAlias in the database.
func (_c *EntityAliasCreate) Save(ctx context.Context) (*EntityAlias, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EntityAliasCreate) SaveX(ctx context.Context) *EntityAlias {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityAliasCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityAliasCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EntityAliasCreate) defaults() {
	if _, ok := _c.mutation.Source(); !ok {
		v := entityalias.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := entityalias.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := entityalias.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EntityAliasCreate) check() error {
	if _, ok := _c.mutation.RawID(); !ok {
		return &ValidationError{Name: "raw_id", err: errors.New(`ent: missing required field "EntityAlias.raw_id"`)}
	}
	if v, ok := _c.mutation.RawID(); ok {
		if err := entityalias.RawIDValidator(v); err != nil {
			return &ValidationError{Name: "raw_id", err: fmt.Errorf(`ent: validator failed for field "EntityAlias.raw_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CanonicalID(); !ok {
		return &ValidationError{Name: "canonical_id", err: errors.New(`ent: missing required field "EntityAlias.canonical_id"`)}
	}
	if v, ok := _c.mutation.CanonicalID(); ok {
		if err := entityalias.CanonicalIDValidator(v); err != nil {
			return &ValidationError{Name: "canonical_id", err: fmt.Errorf(`ent: validator failed for field "EntityAlias.canonical_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "EntityAlias.source"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EntityAlias.created_at"`)}
	}
	return nil
}

func (_c *EntityAliasCreate) sqlSave(ctx context.Context) (*EntityAlias, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EntityAliasCreate) createSpec() (*EntityAlias, *sqlgraph.CreateSpec) {
	var (
		_node = &EntityAlias{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entityalias.Table, sqlgraph.NewFieldSpec(entityalias.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.RawID(); ok {
		_spec.SetField(entityalias.FieldRawID, field.TypeString, value)
		_node.RawID = value
	}
	if value, ok := _c.mutation.CanonicalID(); ok {
		_spec.SetField(entityalias.FieldCanonicalID, field.TypeString, value)
		_node.CanonicalID = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(entityalias.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(entityalias.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// EntityAliasCreateBulk is the builder for creating many EntityAlias entities in bulk.
type EntityAliasCreateBulk struct {
	config
	err      error
	builders []*EntityAliasCreate
}

// Save creates the EntityAlias entities in the database.
func (_c *EntityAliasCreateBulk) Save(ctx context.Context) ([]*EntityAlias, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EntityAlias, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntityAliasMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EntityAliasCreateBulk) SaveX(ctx context.Context) []*EntityAlias {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntityAliasCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntityAliasCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
