// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/langoai/lango/internal/ent/escrowdeal"
)

// EscrowDealCreate is the builder for creating a EscrowDeal entity.
type EscrowDealCreate struct {
	config
	mutation *EscrowDealMutation
	hooks    []Hook
}

// SetEscrowID sets the "escrow_id" field.
func (_c *EscrowDealCreate) SetEscrowID(v string) *EscrowDealCreate {
	_c.mutation.SetEscrowID(v)
	return _c
}

// SetBuyerDid sets the "buyer_did" field.
func (_c *EscrowDealCreate) SetBuyerDid(v string) *EscrowDealCreate {
	_c.mutation.SetBuyerDid(v)
	return _c
}

// SetSellerDid sets the "seller_did" field.
func (_c *EscrowDealCreate) SetSellerDid(v string) *EscrowDealCreate {
	_c.mutation.SetSellerDid(v)
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *EscrowDealCreate) SetTotalAmount(v string) *EscrowDealCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *EscrowDealCreate) SetStatus(v string) *EscrowDealCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EscrowDealCreate) SetNillableStatus(v *string) *EscrowDealCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMilestones sets the "milestones" field.
func (_c *EscrowDealCreate) SetMilestones(v []byte) *EscrowDealCreate {
	_c.mutation.SetMilestones(v)
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *EscrowDealCreate) SetTaskID(v string) *EscrowDealCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_c *EscrowDealCreate) SetNillableTaskID(v *string) *EscrowDealCreate {
	if v != nil {
		_c.SetTaskID(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *EscrowDealCreate) SetReason(v string) *EscrowDealCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *EscrowDealCreate) SetNillableReason(v *string) *EscrowDealCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetDisputeNote sets the "dispute_note" field.
func (_c *EscrowDealCreate) SetDisputeNote(v string) *EscrowDealCreate {
	_c.mutation.SetDisputeNote(v)
	return _c
}

// SetNillableDisputeNote sets the "dispute_note" field if the given value is not nil.
func (_c *EscrowDealCreate) SetNillableDisputeNote(v *string) *EscrowDealCreate {
	if v != nil {
		_c.SetDisputeNote(*v)
	}
	return _c
}

// SetChainID sets the "chain_id" field.
func (_c *EscrowDealCreate) SetChainID(v int64) *EscrowDealCreate {
	_c.mutation.SetChainID(v)
	return _c
}

// SetNillableChainID sets the "chain_id" field if the given value is not nil.
func (_c *EscrowDealCreate) SetNillableChainID(v *int64) *EscrowDealCreate {
	if v != nil {
		_c.SetChainID(*v)
	}
	return _c
}

// SetHubAddress sets the "hub_address" field.
func (_c *EscrowDealCreate) SetHubAddress(v string) *EscrowDealCreate {
	_c.mutation.SetHubAddress(v)
	return _c
}

// SetNillableHubAddress sets the "hub_address" field if the given value is not nil.
func (_c *EscrowDealCreate) SetNillableHubAddress(v *string) *EscrowDealCreate {
	if v != nil {
		_c.SetHubAddress(*v)
	}
	return _c
}

// SetOnChainDealID sets the "on_chain_deal_id" field.
func (_c *EscrowDealCreate) SetOnChainDealID(v string) *EscrowDealCreate {
	_c.mutation.SetOnChainDealID(v)
	return _c
}

// SetNillableOnChainDealID sets the "on_chain_deal_id" field if the given value is not nil.
func (_c *EscrowDealCreate) SetNillableOnChainDealID(v *string) *EscrowDealCreate {
	if v != nil {
		_c.SetOnChainDealID(*v)
	}
	return _c
}

// SetDepositTxHash sets the "deposit_tx_hash" field.
func (_c *EscrowDealCreate) SetDepositTxHash(v string) *EscrowDealCreate {
	_c.mutation.SetDepositTxHash(v)
	return _c
}

// SetNillableDepositTxHash sets the "deposit_tx_hash" field if the given value is not nil.
func (_c *EscrowDealCreate) SetNillableDepositTxHash(v *string) *EscrowDealCreate {
	if v != nil {
		_c.SetDepositTxHash(*v)
	}
	return _c
}

// SetReleaseTxHash sets the "release_tx_hash" field.
func (_c *EscrowDealCreate) SetReleaseTxHash(v string) *EscrowDealCreate {
	_c.mutation.SetReleaseTxHash(v)
	return _c
}

// SetNillableReleaseTxHash sets the "release_tx_hash" field if the given value is not nil.
func (_c *EscrowDealCreate) SetNillableReleaseTxHash(v *string) *EscrowDealCreate {
	if v != nil {
		_c.SetReleaseTxHash(*v)
	}
	return _c
}

// SetRefundTxHash sets the "refund_tx_hash" field.
func (_c *EscrowDealCreate) SetRefundTxHash(v string) *EscrowDealCreate {
	_c.mutation.SetRefundTxHash(v)
	return _c
}

// SetNillableRefundTxHash sets the "refund_tx_hash" field if the given value is not nil.
func (_c *EscrowDealCreate) SetNillableRefundTxHash(v *string) *EscrowDealCreate {
	if v != nil {
		_c.SetRefundTxHash(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EscrowDealCreate) SetCreatedAt(v time.Time) *EscrowDealCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EscrowDealCreate) SetNillableCreatedAt(v *time.Time) *EscrowDealCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EscrowDealCreate) SetUpdatedAt(v time.Time) *EscrowDealCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EscrowDealCreate) SetNillableUpdatedAt(v *time.Time) *EscrowDealCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *EscrowDealCreate) SetExpiresAt(v time.Time) *EscrowDealCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// Mutation returns the EscrowDealMutation object of the builder.
func (_c *EscrowDealCreate) Mutation() *EscrowDealMutation {
	return _c.mutation
}

// Save creates the EscrowDeal in the database.
func (_c *EscrowDealCreate) Save(ctx context.Context) (*EscrowDeal, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EscrowDealCreate) SaveX(ctx context.Context) *EscrowDeal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EscrowDealCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EscrowDealCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EscrowDealCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := escrowdeal.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ChainID(); !ok {
		v := escrowdeal.DefaultChainID
		_c.mutation.SetChainID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := escrowdeal.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := escrowdeal.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EscrowDealCreate) check() error {
	if _, ok := _c.mutation.EscrowID(); !ok {
		return &ValidationError{Name: "escrow_id", err: errors.New(`ent: missing required field "EscrowDeal.escrow_id"`)}
	}
	if v, ok := _c.mutation.EscrowID(); ok {
		if err := escrowdeal.EscrowIDValidator(v); err != nil {
			return &ValidationError{Name: "escrow_id", err: fmt.Errorf(`ent: validator failed for field "EscrowDeal.escrow_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BuyerDid(); !ok {
		return &ValidationError{Name: "buyer_did", err: errors.New(`ent: missing required field "EscrowDeal.buyer_did"`)}
	}
	if v, ok := _c.mutation.BuyerDid(); ok {
		if err := escrowdeal.BuyerDidValidator(v); err != nil {
			return &ValidationError{Name: "buyer_did", err: fmt.Errorf(`ent: validator failed for field "EscrowDeal.buyer_did": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SellerDid(); !ok {
		return &ValidationError{Name: "seller_did", err: errors.New(`ent: missing required field "EscrowDeal.seller_did"`)}
	}
	if v, ok := _c.mutation.SellerDid(); ok {
		if err := escrowdeal.SellerDidValidator(v); err != nil {
			return &ValidationError{Name: "seller_did", err: fmt.Errorf(`ent: validator failed for field "EscrowDeal.seller_did": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "EscrowDeal.total_amount"`)}
	}
	if v, ok := _c.mutation.TotalAmount(); ok {
		if err := escrowdeal.TotalAmountValidator(v); err != nil {
			return &ValidationError{Name: "total_amount", err: fmt.Errorf(`ent: validator failed for field "EscrowDeal.total_amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EscrowDeal.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := escrowdeal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EscrowDeal.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EscrowDeal.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EscrowDeal.updated_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "EscrowDeal.expires_at"`)}
	}
	return nil
}

func (_c *EscrowDealCreate) sqlSave(ctx context.Context) (*EscrowDeal, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EscrowDealCreate) createSpec() (*EscrowDeal, *sqlgraph.CreateSpec) {
	var (
		_node = &EscrowDeal{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(escrowdeal.Table, sqlgraph.NewFieldSpec(escrowdeal.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.EscrowID(); ok {
		_spec.SetField(escrowdeal.FieldEscrowID, field.TypeString, value)
		_node.EscrowID = value
	}
	if value, ok := _c.mutation.BuyerDid(); ok {
		_spec.SetField(escrowdeal.FieldBuyerDid, field.TypeString, value)
		_node.BuyerDid = value
	}
	if value, ok := _c.mutation.SellerDid(); ok {
		_spec.SetField(escrowdeal.FieldSellerDid, field.TypeString, value)
		_node.SellerDid = value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(escrowdeal.FieldTotalAmount, field.TypeString, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(escrowdeal.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Milestones(); ok {
		_spec.SetField(escrowdeal.FieldMilestones, field.TypeBytes, value)
		_node.Milestones = value
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(escrowdeal.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(escrowdeal.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.DisputeNote(); ok {
		_spec.SetField(escrowdeal.FieldDisputeNote, field.TypeString, value)
		_node.DisputeNote = value
	}
	if value, ok := _c.mutation.ChainID(); ok {
		_spec.SetField(escrowdeal.FieldChainID, field.TypeInt64, value)
		_node.ChainID = value
	}
	if value, ok := _c.mutation.HubAddress(); ok {
		_spec.SetField(escrowdeal.FieldHubAddress, field.TypeString, value)
		_node.HubAddress = value
	}
	if value, ok := _c.mutation.OnChainDealID(); ok {
		_spec.SetField(escrowdeal.FieldOnChainDealID, field.TypeString, value)
		_node.OnChainDealID = value
	}
	if value, ok := _c.mutation.DepositTxHash(); ok {
		_spec.SetField(escrowdeal.FieldDepositTxHash, field.TypeString, value)
		_node.DepositTxHash = value
	}
	if value, ok := _c.mutation.ReleaseTxHash(); ok {
		_spec.SetField(escrowdeal.FieldReleaseTxHash, field.TypeString, value)
		_node.ReleaseTxHash = value
	}
	if value, ok := _c.mutation.RefundTxHash(); ok {
		_spec.SetField(escrowdeal.FieldRefundTxHash, field.TypeString, value)
		_node.RefundTxHash = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(escrowdeal.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(escrowdeal.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(escrowdeal.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// EscrowDealCreateBulk is the builder for creating many EscrowDeal entities in bulk.
type EscrowDealCreateBulk struct {
	config
	err      error
	builders []*EscrowDealCreate
}

// Save creates the EscrowDeal entities in the database.
func (_c *EscrowDealCreateBulk) Save(ctx context.Context) ([]*EscrowDeal, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EscrowDeal, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EscrowDealMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EscrowDealCreateBulk) SaveX(ctx context.Context) []*EscrowDeal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EscrowDealCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EscrowDealCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
