// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/mission"
)

// MissionCreate is the builder for creating a Mission entity.
type MissionCreate struct {
	config
	mutation *MissionMutation
	hooks    []Hook
}

// SetSessionKey sets the "session_key" field.
func (_c *MissionCreate) SetSessionKey(v string) *MissionCreate {
	_c.mutation.SetSessionKey(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *MissionCreate) SetTitle(v string) *MissionCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *MissionCreate) SetDescription(v string) *MissionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MissionCreate) SetNillableDescription(v *string) *MissionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *MissionCreate) SetStatus(v mission.Status) *MissionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MissionCreate) SetNillableStatus(v *mission.Status) *MissionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSourceKind sets the "source_kind" field.
func (_c *MissionCreate) SetSourceKind(v string) *MissionCreate {
	_c.mutation.SetSourceKind(v)
	return _c
}

// SetSourceRef sets the "source_ref" field.
func (_c *MissionCreate) SetSourceRef(v string) *MissionCreate {
	_c.mutation.SetSourceRef(v)
	return _c
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_c *MissionCreate) SetNillableSourceRef(v *string) *MissionCreate {
	if v != nil {
		_c.SetSourceRef(*v)
	}
	return _c
}

// SetCurrentBlockedReason sets the "current_blocked_reason" field.
func (_c *MissionCreate) SetCurrentBlockedReason(v string) *MissionCreate {
	_c.mutation.SetCurrentBlockedReason(v)
	return _c
}

// SetNillableCurrentBlockedReason sets the "current_blocked_reason" field if the given value is not nil.
func (_c *MissionCreate) SetNillableCurrentBlockedReason(v *string) *MissionCreate {
	if v != nil {
		_c.SetCurrentBlockedReason(*v)
	}
	return _c
}

// SetCurrentDecisionKind sets the "current_decision_kind" field.
func (_c *MissionCreate) SetCurrentDecisionKind(v string) *MissionCreate {
	_c.mutation.SetCurrentDecisionKind(v)
	return _c
}

// SetNillableCurrentDecisionKind sets the "current_decision_kind" field if the given value is not nil.
func (_c *MissionCreate) SetNillableCurrentDecisionKind(v *string) *MissionCreate {
	if v != nil {
		_c.SetCurrentDecisionKind(*v)
	}
	return _c
}

// SetCurrentDecisionSummary sets the "current_decision_summary" field.
func (_c *MissionCreate) SetCurrentDecisionSummary(v string) *MissionCreate {
	_c.mutation.SetCurrentDecisionSummary(v)
	return _c
}

// SetNillableCurrentDecisionSummary sets the "current_decision_summary" field if the given value is not nil.
func (_c *MissionCreate) SetNillableCurrentDecisionSummary(v *string) *MissionCreate {
	if v != nil {
		_c.SetCurrentDecisionSummary(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MissionCreate) SetCreatedAt(v time.Time) *MissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MissionCreate) SetNillableCreatedAt(v *time.Time) *MissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MissionCreate) SetUpdatedAt(v time.Time) *MissionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MissionCreate) SetNillableUpdatedAt(v *time.Time) *MissionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *MissionCreate) SetCompletedAt(v time.Time) *MissionCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *MissionCreate) SetNillableCompletedAt(v *time.Time) *MissionCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MissionCreate) SetID(v uuid.UUID) *MissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MissionCreate) SetNillableID(v *uuid.UUID) *MissionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MissionMutation object of the builder.
func (_c *MissionCreate) Mutation() *MissionMutation {
	return _c.mutation
}

// Save creates the Mission in the database.
func (_c *MissionCreate) Save(ctx context.Context) (*Mission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MissionCreate) SaveX(ctx context.Context) *Mission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MissionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := mission.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mission.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := mission.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MissionCreate) check() error {
	if _, ok := _c.mutation.SessionKey(); !ok {
		return &ValidationError{Name: "session_key", err: errors.New(`ent: missing required field "Mission.session_key"`)}
	}
	if v, ok := _c.mutation.SessionKey(); ok {
		if err := mission.SessionKeyValidator(v); err != nil {
			return &ValidationError{Name: "session_key", err: fmt.Errorf(`ent: validator failed for field "Mission.session_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Mission.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := mission.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Mission.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Mission.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := mission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Mission.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceKind(); !ok {
		return &ValidationError{Name: "source_kind", err: errors.New(`ent: missing required field "Mission.source_kind"`)}
	}
	if v, ok := _c.mutation.SourceKind(); ok {
		if err := mission.SourceKindValidator(v); err != nil {
			return &ValidationError{Name: "source_kind", err: fmt.Errorf(`ent: validator failed for field "Mission.source_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Mission.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Mission.updated_at"`)}
	}
	return nil
}

func (_c *MissionCreate) sqlSave(ctx context.Context) (*Mission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MissionCreate) createSpec() (*Mission, *sqlgraph.CreateSpec) {
	var (
		_node = &Mission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mission.Table, sqlgraph.NewFieldSpec(mission.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SessionKey(); ok {
		_spec.SetField(mission.FieldSessionKey, field.TypeString, value)
		_node.SessionKey = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(mission.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(mission.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(mission.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SourceKind(); ok {
		_spec.SetField(mission.FieldSourceKind, field.TypeString, value)
		_node.SourceKind = value
	}
	if value, ok := _c.mutation.SourceRef(); ok {
		_spec.SetField(mission.FieldSourceRef, field.TypeString, value)
		_node.SourceRef = &value
	}
	if value, ok := _c.mutation.CurrentBlockedReason(); ok {
		_spec.SetField(mission.FieldCurrentBlockedReason, field.TypeString, value)
		_node.CurrentBlockedReason = &value
	}
	if value, ok := _c.mutation.CurrentDecisionKind(); ok {
		_spec.SetField(mission.FieldCurrentDecisionKind, field.TypeString, value)
		_node.CurrentDecisionKind = &value
	}
	if value, ok := _c.mutation.CurrentDecisionSummary(); ok {
		_spec.SetField(mission.FieldCurrentDecisionSummary, field.TypeString, value)
		_node.CurrentDecisionSummary = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(mission.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	return _node, _spec
}

// MissionCreateBulk is the builder for creating many Mission entities in bulk.
type MissionCreateBulk struct {
	config
	err      error
	builders []*MissionCreate
}

// Save creates the Mission entities in the database.
func (_c *MissionCreateBulk) Save(ctx context.Context) ([]*Mission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Mission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MissionCreateBulk) SaveX(ctx context.Context) []*Mission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
