// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/langoai/lango/internal/ent/missionexecutionlink"
	"github.com/langoai/lango/internal/ent/predicate"
)

// MissionExecutionLinkDelete is the builder for deleting a MissionExecutionLink entity.
type MissionExecutionLinkDelete struct {
	config
	hooks    []Hook
	mutation *MissionExecutionLinkMutation
}

// Where appends a list predicates to the MissionExecutionLinkDelete builder.
func (_d *MissionExecutionLinkDelete) Where(ps ...predicate.MissionExecutionLink) *MissionExecutionLinkDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MissionExecutionLinkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MissionExecutionLinkDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MissionExecutionLinkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(missionexecutionlink.Table, sqlgraph.NewFieldSpec(missionexecutionlink.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MissionExecutionLinkDeleteOne is the builder for deleting a single MissionExecutionLink entity.
type MissionExecutionLinkDeleteOne struct {
	_d *MissionExecutionLinkDelete
}

// Where appends a list predicates to the MissionExecutionLinkDelete builder.
func (_d *MissionExecutionLinkDeleteOne) Where(ps ...predicate.MissionExecutionLink) *MissionExecutionLinkDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MissionExecutionLinkDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{missionexecutionlink.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MissionExecutionLinkDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
