// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/missionexecutionlink"
)

// MissionExecutionLinkCreate is the builder for creating a MissionExecutionLink entity.
type MissionExecutionLinkCreate struct {
	config
	mutation *MissionExecutionLinkMutation
	hooks    []Hook
}

// SetMissionID sets the "mission_id" field.
func (_c *MissionExecutionLinkCreate) SetMissionID(v uuid.UUID) *MissionExecutionLinkCreate {
	_c.mutation.SetMissionID(v)
	return _c
}

// SetExecutionKind sets the "execution_kind" field.
func (_c *MissionExecutionLinkCreate) SetExecutionKind(v missionexecutionlink.ExecutionKind) *MissionExecutionLinkCreate {
	_c.mutation.SetExecutionKind(v)
	return _c
}

// SetExecutionRef sets the "execution_ref" field.
func (_c *MissionExecutionLinkCreate) SetExecutionRef(v string) *MissionExecutionLinkCreate {
	_c.mutation.SetExecutionRef(v)
	return _c
}

// SetLinkRole sets the "link_role" field.
func (_c *MissionExecutionLinkCreate) SetLinkRole(v missionexecutionlink.LinkRole) *MissionExecutionLinkCreate {
	_c.mutation.SetLinkRole(v)
	return _c
}

// SetNillableLinkRole sets the "link_role" field if the given value is not nil.
func (_c *MissionExecutionLinkCreate) SetNillableLinkRole(v *missionexecutionlink.LinkRole) *MissionExecutionLinkCreate {
	if v != nil {
		_c.SetLinkRole(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MissionExecutionLinkCreate) SetCreatedAt(v time.Time) *MissionExecutionLinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MissionExecutionLinkCreate) SetNillableCreatedAt(v *time.Time) *MissionExecutionLinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MissionExecutionLinkCreate) SetID(v uuid.UUID) *MissionExecutionLinkCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MissionExecutionLinkCreate) SetNillableID(v *uuid.UUID) *MissionExecutionLinkCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MissionExecutionLinkMutation object of the builder.
func (_c *MissionExecutionLinkCreate) Mutation() *MissionExecutionLinkMutation {
	return _c.mutation
}

// Save creates the MissionExecutionLink in the database.
func (_c *MissionExecutionLinkCreate) Save(ctx context.Context) (*MissionExecutionLink, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MissionExecutionLinkCreate) SaveX(ctx context.Context) *MissionExecutionLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MissionExecutionLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MissionExecutionLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MissionExecutionLinkCreate) defaults() {
	if _, ok := _c.mutation.LinkRole(); !ok {
		v := missionexecutionlink.DefaultLinkRole
		_c.mutation.SetLinkRole(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := missionexecutionlink.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := missionexecutionlink.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MissionExecutionLinkCreate) check() error {
	if _, ok := _c.mutation.MissionID(); !ok {
		return &ValidationError{Name: "mission_id", err: errors.New(`ent: missing required field "MissionExecutionLink.mission_id"`)}
	}
	if _, ok := _c.mutation.ExecutionKind(); !ok {
		return &ValidationError{Name: "execution_kind", err: errors.New(`ent: missing required field "MissionExecutionLink.execution_kind"`)}
	}
	if v, ok := _c.mutation.ExecutionKind(); ok {
		if err := missionexecutionlink.ExecutionKindValidator(v); err != nil {
			return &ValidationError{Name: "execution_kind", err: fmt.Errorf(`ent: validator failed for field "MissionExecutionLink.execution_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExecutionRef(); !ok {
		return &ValidationError{Name: "execution_ref", err: errors.New(`ent: missing required field "MissionExecutionLink.execution_ref"`)}
	}
	if v, ok := _c.mutation.ExecutionRef(); ok {
		if err := missionexecutionlink.ExecutionRefValidator(v); err != nil {
			return &ValidationError{Name: "execution_ref", err: fmt.Errorf(`ent: validator failed for field "MissionExecutionLink.execution_ref": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LinkRole(); !ok {
		return &ValidationError{Name: "link_role", err: errors.New(`ent: missing required field "MissionExecutionLink.link_role"`)}
	}
	if v, ok := _c.mutation.LinkRole(); ok {
		if err := missionexecutionlink.LinkRoleValidator(v); err != nil {
			return &ValidationError{Name: "link_role", err: fmt.Errorf(`ent: validator failed for field "MissionExecutionLink.link_role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MissionExecutionLink.created_at"`)}
	}
	return nil
}

func (_c *MissionExecutionLinkCreate) sqlSave(ctx context.Context) (*MissionExecutionLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MissionExecutionLinkCreate) createSpec() (*MissionExecutionLink, *sqlgraph.CreateSpec) {
	var (
		_node = &MissionExecutionLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(missionexecutionlink.Table, sqlgraph.NewFieldSpec(missionexecutionlink.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.MissionID(); ok {
		_spec.SetField(missionexecutionlink.FieldMissionID, field.TypeUUID, value)
		_node.MissionID = value
	}
	if value, ok := _c.mutation.ExecutionKind(); ok {
		_spec.SetField(missionexecutionlink.FieldExecutionKind, field.TypeEnum, value)
		_node.ExecutionKind = value
	}
	if value, ok := _c.mutation.ExecutionRef(); ok {
		_spec.SetField(missionexecutionlink.FieldExecutionRef, field.TypeString, value)
		_node.ExecutionRef = value
	}
	if value, ok := _c.mutation.LinkRole(); ok {
		_spec.SetField(missionexecutionlink.FieldLinkRole, field.TypeEnum, value)
		_node.LinkRole = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(missionexecutionlink.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// MissionExecutionLinkCreateBulk is the builder for creating many MissionExecutionLink entities in bulk.
type MissionExecutionLinkCreateBulk struct {
	config
	err      error
	builders []*MissionExecutionLinkCreate
}

// Save creates the MissionExecutionLink entities in the database.
func (_c *MissionExecutionLinkCreateBulk) Save(ctx context.Context) ([]*MissionExecutionLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MissionExecutionLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MissionExecutionLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MissionExecutionLinkCreateBulk) SaveX(ctx context.Context) []*MissionExecutionLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MissionExecutionLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MissionExecutionLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
