// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/langoai/lango/internal/ent/ontologytype"
	"github.com/langoai/lango/internal/ent/predicate"
)

// OntologyTypeUpdate is the builder for updating OntologyType entities.
type OntologyTypeUpdate struct {
	config
	hooks    []Hook
	mutation *OntologyTypeMutation
}

// Where appends a list predicates to the OntologyTypeUpdate builder.
func (_u *OntologyTypeUpdate) Where(ps ...predicate.OntologyType) *OntologyTypeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *OntologyTypeUpdate) SetName(v string) *OntologyTypeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OntologyTypeUpdate) SetNillableName(v *string) *OntologyTypeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *OntologyTypeUpdate) SetDescription(v string) *OntologyTypeUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *OntologyTypeUpdate) SetNillableDescription(v *string) *OntologyTypeUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetProperties sets the "properties" field.
func (_u *OntologyTypeUpdate) SetProperties(v []map[string]interface{}) *OntologyTypeUpdate {
	_u.mutation.SetProperties(v)
	return _u
}

// AppendProperties appends value to the "properties" field.
func (_u *OntologyTypeUpdate) AppendProperties(v []map[string]interface{}) *OntologyTypeUpdate {
	_u.mutation.AppendProperties(v)
	return _u
}

// ClearProperties clears the value of the "properties" field.
func (_u *OntologyTypeUpdate) ClearProperties() *OntologyTypeUpdate {
	_u.mutation.ClearProperties()
	return _u
}

// SetExtends sets the "extends" field.
func (_u *OntologyTypeUpdate) SetExtends(v string) *OntologyTypeUpdate {
	_u.mutation.SetExtends(v)
	return _u
}

// SetNillableExtends sets the "extends" field if the given value is not nil.
func (_u *OntologyTypeUpdate) SetNillableExtends(v *string) *OntologyTypeUpdate {
	if v != nil {
		_u.SetExtends(*v)
	}
	return _u
}

// ClearExtends clears the value of the "extends" field.
func (_u *OntologyTypeUpdate) ClearExtends() *OntologyTypeUpdate {
	_u.mutation.ClearExtends()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OntologyTypeUpdate) SetStatus(v ontologytype.Status) *OntologyTypeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OntologyTypeUpdate) SetNillableStatus(v *ontologytype.Status) *OntologyTypeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *OntologyTypeUpdate) SetVersion(v int) *OntologyTypeUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *OntologyTypeUpdate) SetNillableVersion(v *int) *OntologyTypeUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *OntologyTypeUpdate) AddVersion(v int) *OntologyTypeUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OntologyTypeUpdate) SetUpdatedAt(v time.Time) *OntologyTypeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OntologyTypeMutation object of the builder.
func (_u *OntologyTypeUpdate) Mutation() *OntologyTypeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OntologyTypeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OntologyTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OntologyTypeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OntologyTypeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OntologyTypeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ontologytype.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OntologyTypeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := ontologytype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OntologyType.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ontologytype.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OntologyType.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OntologyTypeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ontologytype.Table, ontologytype.Columns, sqlgraph.NewFieldSpec(ontologytype.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ontologytype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(ontologytype.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Properties(); ok {
		_spec.SetField(ontologytype.FieldProperties, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProperties(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, ontologytype.FieldProperties, value)
		})
	}
	if _u.mutation.PropertiesCleared() {
		_spec.ClearField(ontologytype.FieldProperties, field.TypeJSON)
	}
	if value, ok := _u.mutation.Extends(); ok {
		_spec.SetField(ontologytype.FieldExtends, field.TypeString, value)
	}
	if _u.mutation.ExtendsCleared() {
		_spec.ClearField(ontologytype.FieldExtends, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ontologytype.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(ontologytype.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(ontologytype.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ontologytype.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ontologytype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OntologyTypeUpdateOne is the builder for updating a single OntologyType entity.
type OntologyTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OntologyTypeMutation
}

// SetName sets the "name" field.
func (_u *OntologyTypeUpdateOne) SetName(v string) *OntologyTypeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OntologyTypeUpdateOne) SetNillableName(v *string) *OntologyTypeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *OntologyTypeUpdateOne) SetDescription(v string) *OntologyTypeUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *OntologyTypeUpdateOne) SetNillableDescription(v *string) *OntologyTypeUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetProperties sets the "properties" field.
func (_u *OntologyTypeUpdateOne) SetProperties(v []map[string]interface{}) *OntologyTypeUpdateOne {
	_u.mutation.SetProperties(v)
	return _u
}

// AppendProperties appends value to the "properties" field.
func (_u *OntologyTypeUpdateOne) AppendProperties(v []map[string]interface{}) *OntologyTypeUpdateOne {
	_u.mutation.AppendProperties(v)
	return _u
}

// ClearProperties clears the value of the "properties" field.
func (_u *OntologyTypeUpdateOne) ClearProperties() *OntologyTypeUpdateOne {
	_u.mutation.ClearProperties()
	return _u
}

// SetExtends sets the "extends" field.
func (_u *OntologyTypeUpdateOne) SetExtends(v string) *OntologyTypeUpdateOne {
	_u.mutation.SetExtends(v)
	return _u
}

// SetNillableExtends sets the "extends" field if the given value is not nil.
func (_u *OntologyTypeUpdateOne) SetNillableExtends(v *string) *OntologyTypeUpdateOne {
	if v != nil {
		_u.SetExtends(*v)
	}
	return _u
}

// ClearExtends clears the value of the "extends" field.
func (_u *OntologyTypeUpdateOne) ClearExtends() *OntologyTypeUpdateOne {
	_u.mutation.ClearExtends()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OntologyTypeUpdateOne) SetStatus(v ontologytype.Status) *OntologyTypeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OntologyTypeUpdateOne) SetNillableStatus(v *ontologytype.Status) *OntologyTypeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *OntologyTypeUpdateOne) SetVersion(v int) *OntologyTypeUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *OntologyTypeUpdateOne) SetNillableVersion(v *int) *OntologyTypeUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *OntologyTypeUpdateOne) AddVersion(v int) *OntologyTypeUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OntologyTypeUpdateOne) SetUpdatedAt(v time.Time) *OntologyTypeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OntologyTypeMutation object of the builder.
func (_u *OntologyTypeUpdateOne) Mutation() *OntologyTypeMutation {
	return _u.mutation
}

// Where appends a list predicates to the OntologyTypeUpdate builder.
func (_u *OntologyTypeUpdateOne) Where(ps ...predicate.OntologyType) *OntologyTypeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OntologyTypeUpdateOne) Select(field string, fields ...string) *OntologyTypeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OntologyType entity.
func (_u *OntologyTypeUpdateOne) Save(ctx context.Context) (*OntologyType, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OntologyTypeUpdateOne) SaveX(ctx context.Context) *OntologyType {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OntologyTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OntologyTypeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OntologyTypeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ontologytype.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OntologyTypeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := ontologytype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OntologyType.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ontologytype.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OntologyType.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OntologyTypeUpdateOne) sqlSave(ctx context.Context) (_node *OntologyType, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ontologytype.Table, ontologytype.Columns, sqlgraph.NewFieldSpec(ontologytype.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OntologyType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ontologytype.FieldID)
		for _, f := range fields {
			if !ontologytype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ontologytype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ontologytype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(ontologytype.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Properties(); ok {
		_spec.SetField(ontologytype.FieldProperties, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProperties(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, ontologytype.FieldProperties, value)
		})
	}
	if _u.mutation.PropertiesCleared() {
		_spec.ClearField(ontologytype.FieldProperties, field.TypeJSON)
	}
	if value, ok := _u.mutation.Extends(); ok {
		_spec.SetField(ontologytype.FieldExtends, field.TypeString, value)
	}
	if _u.mutation.ExtendsCleared() {
		_spec.ClearField(ontologytype.FieldExtends, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ontologytype.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(ontologytype.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(ontologytype.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ontologytype.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OntologyType{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ontologytype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
