// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/ontologytype"
)

// OntologyTypeCreate is the builder for creating a OntologyType entity.
type OntologyTypeCreate struct {
	config
	mutation *OntologyTypeMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *OntologyTypeCreate) SetName(v string) *OntologyTypeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *OntologyTypeCreate) SetDescription(v string) *OntologyTypeCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *OntologyTypeCreate) SetNillableDescription(v *string) *OntologyTypeCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetProperties sets the "properties" field.
func (_c *OntologyTypeCreate) SetProperties(v []map[string]interface{}) *OntologyTypeCreate {
	_c.mutation.SetProperties(v)
	return _c
}

// SetExtends sets the "extends" field.
func (_c *OntologyTypeCreate) SetExtends(v string) *OntologyTypeCreate {
	_c.mutation.SetExtends(v)
	return _c
}

// SetNillableExtends sets the "extends" field if the given value is not nil.
func (_c *OntologyTypeCreate) SetNillableExtends(v *string) *OntologyTypeCreate {
	if v != nil {
		_c.SetExtends(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OntologyTypeCreate) SetStatus(v ontologytype.Status) *OntologyTypeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OntologyTypeCreate) SetNillableStatus(v *ontologytype.Status) *OntologyTypeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *OntologyTypeCreate) SetVersion(v int) *OntologyTypeCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *OntologyTypeCreate) SetNillableVersion(v *int) *OntologyTypeCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OntologyTypeCreate) SetCreatedAt(v time.Time) *OntologyTypeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OntologyTypeCreate) SetNillableCreatedAt(v *time.Time) *OntologyTypeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OntologyTypeCreate) SetUpdatedAt(v time.Time) *OntologyTypeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OntologyTypeCreate) SetNillableUpdatedAt(v *time.Time) *OntologyTypeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OntologyTypeCreate) SetID(v uuid.UUID) *OntologyTypeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OntologyTypeCreate) SetNillableID(v *uuid.UUID) *OntologyTypeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the OntologyTypeMutation object of the builder.
func (_c *OntologyTypeCreate) Mutation() *OntologyTypeMutation {
	return _c.mutation
}

// Save creates the OntologyType in the database.
func (_c *OntologyTypeCreate) Save(ctx context.Context) (*OntologyType, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OntologyTypeCreate) SaveX(ctx context.Context) *OntologyType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OntologyTypeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OntologyTypeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OntologyTypeCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := ontologytype.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := ontologytype.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := ontologytype.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ontologytype.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ontologytype.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := ontologytype.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OntologyTypeCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OntologyType.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := ontologytype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OntologyType.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "OntologyType.description"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OntologyType.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := ontologytype.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OntologyType.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "OntologyType.version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OntologyType.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OntologyType.updated_at"`)}
	}
	return nil
}

func (_c *OntologyTypeCreate) sqlSave(ctx context.Context) (*OntologyType, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OntologyTypeCreate) createSpec() (*OntologyType, *sqlgraph.CreateSpec) {
	var (
		_node = &OntologyType{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ontologytype.Table, sqlgraph.NewFieldSpec(ontologytype.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ontologytype.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(ontologytype.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Properties(); ok {
		_spec.SetField(ontologytype.FieldProperties, field.TypeJSON, value)
		_node.Properties = value
	}
	if value, ok := _c.mutation.Extends(); ok {
		_spec.SetField(ontologytype.FieldExtends, field.TypeString, value)
		_node.Extends = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ontologytype.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(ontologytype.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ontologytype.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ontologytype.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OntologyTypeCreateBulk is the builder for creating many OntologyType entities in bulk.
type OntologyTypeCreateBulk struct {
	config
	err      error
	builders []*OntologyTypeCreate
}

// Save creates the OntologyType entities in the database.
func (_c *OntologyTypeCreateBulk) Save(ctx context.Context) ([]*OntologyType, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OntologyType, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OntologyTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OntologyTypeCreateBulk) SaveX(ctx context.Context) []*OntologyType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OntologyTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OntologyTypeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
