// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/langoai/lango/internal/ent/ontologyconflict"
	"github.com/langoai/lango/internal/ent/predicate"
)

// OntologyConflictUpdate is the builder for updating OntologyConflict entities.
type OntologyConflictUpdate struct {
	config
	hooks    []Hook
	mutation *OntologyConflictMutation
}

// Where appends a list predicates to the OntologyConflictUpdate builder.
func (_u *OntologyConflictUpdate) Where(ps ...predicate.OntologyConflict) *OntologyConflictUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubject sets the "subject" field.
func (_u *OntologyConflictUpdate) SetSubject(v string) *OntologyConflictUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *OntologyConflictUpdate) SetNillableSubject(v *string) *OntologyConflictUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetPredicate sets the "predicate" field.
func (_u *OntologyConflictUpdate) SetPredicate(v string) *OntologyConflictUpdate {
	_u.mutation.SetPredicate(v)
	return _u
}

// SetNillablePredicate sets the "predicate" field if the given value is not nil.
func (_u *OntologyConflictUpdate) SetNillablePredicate(v *string) *OntologyConflictUpdate {
	if v != nil {
		_u.SetPredicate(*v)
	}
	return _u
}

// SetCandidates sets the "candidates" field.
func (_u *OntologyConflictUpdate) SetCandidates(v []map[string]interface{}) *OntologyConflictUpdate {
	_u.mutation.SetCandidates(v)
	return _u
}

// AppendCandidates appends value to the "candidates" field.
func (_u *OntologyConflictUpdate) AppendCandidates(v []map[string]interface{}) *OntologyConflictUpdate {
	_u.mutation.AppendCandidates(v)
	return _u
}

// ClearCandidates clears the value of the "candidates" field.
func (_u *OntologyConflictUpdate) ClearCandidates() *OntologyConflictUpdate {
	_u.mutation.ClearCandidates()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OntologyConflictUpdate) SetStatus(v ontologyconflict.Status) *OntologyConflictUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OntologyConflictUpdate) SetNillableStatus(v *ontologyconflict.Status) *OntologyConflictUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *OntologyConflictUpdate) SetResolution(v string) *OntologyConflictUpdate {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *OntologyConflictUpdate) SetNillableResolution(v *string) *OntologyConflictUpdate {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// ClearResolution clears the value of the "resolution" field.
func (_u *OntologyConflictUpdate) ClearResolution() *OntologyConflictUpdate {
	_u.mutation.ClearResolution()
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *OntologyConflictUpdate) SetResolvedAt(v time.Time) *OntologyConflictUpdate {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *OntologyConflictUpdate) SetNillableResolvedAt(v *time.Time) *OntologyConflictUpdate {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *OntologyConflictUpdate) ClearResolvedAt() *OntologyConflictUpdate {
	_u.mutation.ClearResolvedAt()
	return _u
}

// Mutation returns the OntologyConflictMutation object of the builder.
func (_u *OntologyConflictUpdate) Mutation() *OntologyConflictMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OntologyConflictUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OntologyConflictUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OntologyConflictUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OntologyConflictUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OntologyConflictUpdate) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := ontologyconflict.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "OntologyConflict.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Predicate(); ok {
		if err := ontologyconflict.PredicateValidator(v); err != nil {
			return &ValidationError{Name: "predicate", err: fmt.Errorf(`ent: validator failed for field "OntologyConflict.predicate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ontologyconflict.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OntologyConflict.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OntologyConflictUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ontologyconflict.Table, ontologyconflict.Columns, sqlgraph.NewFieldSpec(ontologyconflict.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(ontologyconflict.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Predicate(); ok {
		_spec.SetField(ontologyconflict.FieldPredicate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Candidates(); ok {
		_spec.SetField(ontologyconflict.FieldCandidates, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCandidates(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, ontologyconflict.FieldCandidates, value)
		})
	}
	if _u.mutation.CandidatesCleared() {
		_spec.ClearField(ontologyconflict.FieldCandidates, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ontologyconflict.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(ontologyconflict.FieldResolution, field.TypeString, value)
	}
	if _u.mutation.ResolutionCleared() {
		_spec.ClearField(ontologyconflict.FieldResolution, field.TypeString)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(ontologyconflict.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(ontologyconflict.FieldResolvedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ontologyconflict.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OntologyConflictUpdateOne is the builder for updating a single OntologyConflict entity.
type OntologyConflictUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OntologyConflictMutation
}

// SetSubject sets the "subject" field.
func (_u *OntologyConflictUpdateOne) SetSubject(v string) *OntologyConflictUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *OntologyConflictUpdateOne) SetNillableSubject(v *string) *OntologyConflictUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetPredicate sets the "predicate" field.
func (_u *OntologyConflictUpdateOne) SetPredicate(v string) *OntologyConflictUpdateOne {
	_u.mutation.SetPredicate(v)
	return _u
}

// SetNillablePredicate sets the "predicate" field if the given value is not nil.
func (_u *OntologyConflictUpdateOne) SetNillablePredicate(v *string) *OntologyConflictUpdateOne {
	if v != nil {
		_u.SetPredicate(*v)
	}
	return _u
}

// SetCandidates sets the "candidates" field.
func (_u *OntologyConflictUpdateOne) SetCandidates(v []map[string]interface{}) *OntologyConflictUpdateOne {
	_u.mutation.SetCandidates(v)
	return _u
}

// AppendCandidates appends value to the "candidates" field.
func (_u *OntologyConflictUpdateOne) AppendCandidates(v []map[string]interface{}) *OntologyConflictUpdateOne {
	_u.mutation.AppendCandidates(v)
	return _u
}

// ClearCandidates clears the value of the "candidates" field.
func (_u *OntologyConflictUpdateOne) ClearCandidates() *OntologyConflictUpdateOne {
	_u.mutation.ClearCandidates()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OntologyConflictUpdateOne) SetStatus(v ontologyconflict.Status) *OntologyConflictUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OntologyConflictUpdateOne) SetNillableStatus(v *ontologyconflict.Status) *OntologyConflictUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *OntologyConflictUpdateOne) SetResolution(v string) *OntologyConflictUpdateOne {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *OntologyConflictUpdateOne) SetNillableResolution(v *string) *OntologyConflictUpdateOne {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// ClearResolution clears the value of the "resolution" field.
func (_u *OntologyConflictUpdateOne) ClearResolution() *OntologyConflictUpdateOne {
	_u.mutation.ClearResolution()
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *OntologyConflictUpdateOne) SetResolvedAt(v time.Time) *OntologyConflictUpdateOne {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *OntologyConflictUpdateOne) SetNillableResolvedAt(v *time.Time) *OntologyConflictUpdateOne {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *OntologyConflictUpdateOne) ClearResolvedAt() *OntologyConflictUpdateOne {
	_u.mutation.ClearResolvedAt()
	return _u
}

// Mutation returns the OntologyConflictMutation object of the builder.
func (_u *OntologyConflictUpdateOne) Mutation() *OntologyConflictMutation {
	return _u.mutation
}

// Where appends a list predicates to the OntologyConflictUpdate builder.
func (_u *OntologyConflictUpdateOne) Where(ps ...predicate.OntologyConflict) *OntologyConflictUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OntologyConflictUpdateOne) Select(field string, fields ...string) *OntologyConflictUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OntologyConflict entity.
func (_u *OntologyConflictUpdateOne) Save(ctx context.Context) (*OntologyConflict, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OntologyConflictUpdateOne) SaveX(ctx context.Context) *OntologyConflict {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OntologyConflictUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OntologyConflictUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OntologyConflictUpdateOne) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := ontologyconflict.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "OntologyConflict.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Predicate(); ok {
		if err := ontologyconflict.PredicateValidator(v); err != nil {
			return &ValidationError{Name: "predicate", err: fmt.Errorf(`ent: validator failed for field "OntologyConflict.predicate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ontologyconflict.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OntologyConflict.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OntologyConflictUpdateOne) sqlSave(ctx context.Context) (_node *OntologyConflict, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ontologyconflict.Table, ontologyconflict.Columns, sqlgraph.NewFieldSpec(ontologyconflict.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OntologyConflict.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ontologyconflict.FieldID)
		for _, f := range fields {
			if !ontologyconflict.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ontologyconflict.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(ontologyconflict.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Predicate(); ok {
		_spec.SetField(ontologyconflict.FieldPredicate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Candidates(); ok {
		_spec.SetField(ontologyconflict.FieldCandidates, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCandidates(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, ontologyconflict.FieldCandidates, value)
		})
	}
	if _u.mutation.CandidatesCleared() {
		_spec.ClearField(ontologyconflict.FieldCandidates, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ontologyconflict.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(ontologyconflict.FieldResolution, field.TypeString, value)
	}
	if _u.mutation.ResolutionCleared() {
		_spec.ClearField(ontologyconflict.FieldResolution, field.TypeString)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(ontologyconflict.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(ontologyconflict.FieldResolvedAt, field.TypeTime)
	}
	_node = &OntologyConflict{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ontologyconflict.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
