// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/langoai/lango/internal/ent/predicate"
	"github.com/langoai/lango/internal/ent/runjournal"
)

// RunJournalUpdate is the builder for updating RunJournal entities.
type RunJournalUpdate struct {
	config
	hooks    []Hook
	mutation *RunJournalMutation
}

// Where appends a list predicates to the RunJournalUpdate builder.
func (_u *RunJournalUpdate) Where(ps ...predicate.RunJournal) *RunJournalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *RunJournalUpdate) SetType(v runjournal.Type) *RunJournalUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RunJournalUpdate) SetNillableType(v *runjournal.Type) *RunJournalUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *RunJournalUpdate) SetPayload(v string) *RunJournalUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *RunJournalUpdate) SetNillablePayload(v *string) *RunJournalUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// Mutation returns the RunJournalMutation object of the builder.
func (_u *RunJournalUpdate) Mutation() *RunJournalMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RunJournalUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunJournalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RunJournalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunJournalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RunJournalUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := runjournal.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RunJournal.type": %w`, err)}
		}
	}
	return nil
}

func (_u *RunJournalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(runjournal.Table, runjournal.Columns, sqlgraph.NewFieldSpec(runjournal.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(runjournal.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(runjournal.FieldPayload, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runjournal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RunJournalUpdateOne is the builder for updating a single RunJournal entity.
type RunJournalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RunJournalMutation
}

// SetType sets the "type" field.
func (_u *RunJournalUpdateOne) SetType(v runjournal.Type) *RunJournalUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RunJournalUpdateOne) SetNillableType(v *runjournal.Type) *RunJournalUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *RunJournalUpdateOne) SetPayload(v string) *RunJournalUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *RunJournalUpdateOne) SetNillablePayload(v *string) *RunJournalUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// Mutation returns the RunJournalMutation object of the builder.
func (_u *RunJournalUpdateOne) Mutation() *RunJournalMutation {
	return _u.mutation
}

// Where appends a list predicates to the RunJournalUpdate builder.
func (_u *RunJournalUpdateOne) Where(ps ...predicate.RunJournal) *RunJournalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RunJournalUpdateOne) Select(field string, fields ...string) *RunJournalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RunJournal entity.
func (_u *RunJournalUpdateOne) Save(ctx context.Context) (*RunJournal, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunJournalUpdateOne) SaveX(ctx context.Context) *RunJournal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RunJournalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunJournalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RunJournalUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := runjournal.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RunJournal.type": %w`, err)}
		}
	}
	return nil
}

func (_u *RunJournalUpdateOne) sqlSave(ctx context.Context) (_node *RunJournal, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(runjournal.Table, runjournal.Columns, sqlgraph.NewFieldSpec(runjournal.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RunJournal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, runjournal.FieldID)
		for _, f := range fields {
			if !runjournal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != runjournal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(runjournal.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(runjournal.FieldPayload, field.TypeString, value)
	}
	_node = &RunJournal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runjournal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
