// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/runjournal"
)

// RunJournalCreate is the builder for creating a RunJournal entity.
type RunJournalCreate struct {
	config
	mutation *RunJournalMutation
	hooks    []Hook
}

// SetRunID sets the "run_id" field.
func (_c *RunJournalCreate) SetRunID(v string) *RunJournalCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetSeq sets the "seq" field.
func (_c *RunJournalCreate) SetSeq(v int64) *RunJournalCreate {
	_c.mutation.SetSeq(v)
	return _c
}

// SetType sets the "type" field.
func (_c *RunJournalCreate) SetType(v runjournal.Type) *RunJournalCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *RunJournalCreate) SetTimestamp(v time.Time) *RunJournalCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *RunJournalCreate) SetNillableTimestamp(v *time.Time) *RunJournalCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *RunJournalCreate) SetPayload(v string) *RunJournalCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RunJournalCreate) SetID(v uuid.UUID) *RunJournalCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RunJournalCreate) SetNillableID(v *uuid.UUID) *RunJournalCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RunJournalMutation object of the builder.
func (_c *RunJournalCreate) Mutation() *RunJournalMutation {
	return _c.mutation
}

// Save creates the RunJournal in the database.
func (_c *RunJournalCreate) Save(ctx context.Context) (*RunJournal, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RunJournalCreate) SaveX(ctx context.Context) *RunJournal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RunJournalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RunJournalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RunJournalCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := runjournal.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := runjournal.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RunJournalCreate) check() error {
	if _, ok := _c.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "RunJournal.run_id"`)}
	}
	if v, ok := _c.mutation.RunID(); ok {
		if err := runjournal.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "RunJournal.run_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Seq(); !ok {
		return &ValidationError{Name: "seq", err: errors.New(`ent: missing required field "RunJournal.seq"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "RunJournal.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := runjournal.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RunJournal.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "RunJournal.timestamp"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "RunJournal.payload"`)}
	}
	return nil
}

func (_c *RunJournalCreate) sqlSave(ctx context.Context) (*RunJournal, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RunJournalCreate) createSpec() (*RunJournal, *sqlgraph.CreateSpec) {
	var (
		_node = &RunJournal{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(runjournal.Table, sqlgraph.NewFieldSpec(runjournal.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.RunID(); ok {
		_spec.SetField(runjournal.FieldRunID, field.TypeString, value)
		_node.RunID = value
	}
	if value, ok := _c.mutation.Seq(); ok {
		_spec.SetField(runjournal.FieldSeq, field.TypeInt64, value)
		_node.Seq = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(runjournal.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(runjournal.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(runjournal.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	return _node, _spec
}

// RunJournalCreateBulk is the builder for creating many RunJournal entities in bulk.
type RunJournalCreateBulk struct {
	config
	err      error
	builders []*RunJournalCreate
}

// Save creates the RunJournal entities in the database.
func (_c *RunJournalCreateBulk) Save(ctx context.Context) ([]*RunJournal, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RunJournal, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RunJournalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RunJournalCreateBulk) SaveX(ctx context.Context) []*RunJournal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RunJournalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RunJournalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
