// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/langoai/lango/internal/ent/predicate"
	"github.com/langoai/lango/internal/ent/runsnapshot"
)

// RunSnapshotDelete is the builder for deleting a RunSnapshot entity.
type RunSnapshotDelete struct {
	config
	hooks    []Hook
	mutation *RunSnapshotMutation
}

// Where appends a list predicates to the RunSnapshotDelete builder.
func (_d *RunSnapshotDelete) Where(ps ...predicate.RunSnapshot) *RunSnapshotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RunSnapshotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RunSnapshotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RunSnapshotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(runsnapshot.Table, sqlgraph.NewFieldSpec(runsnapshot.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RunSnapshotDeleteOne is the builder for deleting a single RunSnapshot entity.
type RunSnapshotDeleteOne struct {
	_d *RunSnapshotDelete
}

// Where appends a list predicates to the RunSnapshotDelete builder.
func (_d *RunSnapshotDeleteOne) Where(ps ...predicate.RunSnapshot) *RunSnapshotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RunSnapshotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{runsnapshot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RunSnapshotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
