// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/actionlog"
	"github.com/langoai/lango/internal/ent/agentmemory"
	"github.com/langoai/lango/internal/ent/auditlog"
	"github.com/langoai/lango/internal/ent/configprofile"
	"github.com/langoai/lango/internal/ent/cronjob"
	"github.com/langoai/lango/internal/ent/cronjobhistory"
	"github.com/langoai/lango/internal/ent/entityalias"
	"github.com/langoai/lango/internal/ent/entityproperty"
	"github.com/langoai/lango/internal/ent/escrowdeal"
	"github.com/langoai/lango/internal/ent/externalref"
	"github.com/langoai/lango/internal/ent/inquiry"
	"github.com/langoai/lango/internal/ent/key"
	"github.com/langoai/lango/internal/ent/knowledge"
	"github.com/langoai/lango/internal/ent/learning"
	"github.com/langoai/lango/internal/ent/message"
	"github.com/langoai/lango/internal/ent/observation"
	"github.com/langoai/lango/internal/ent/ontologyconflict"
	"github.com/langoai/lango/internal/ent/ontologypredicate"
	"github.com/langoai/lango/internal/ent/ontologytype"
	"github.com/langoai/lango/internal/ent/paymenttx"
	"github.com/langoai/lango/internal/ent/peerreputation"
	"github.com/langoai/lango/internal/ent/provenanceattribution"
	"github.com/langoai/lango/internal/ent/provenancecheckpoint"
	"github.com/langoai/lango/internal/ent/reflection"
	"github.com/langoai/lango/internal/ent/runjournal"
	"github.com/langoai/lango/internal/ent/runsnapshot"
	"github.com/langoai/lango/internal/ent/runstep"
	"github.com/langoai/lango/internal/ent/schema"
	"github.com/langoai/lango/internal/ent/secret"
	"github.com/langoai/lango/internal/ent/session"
	"github.com/langoai/lango/internal/ent/sessionprovenance"
	"github.com/langoai/lango/internal/ent/tokenusage"
	"github.com/langoai/lango/internal/ent/turntrace"
	"github.com/langoai/lango/internal/ent/turntraceevent"
	"github.com/langoai/lango/internal/ent/workflowrun"
	"github.com/langoai/lango/internal/ent/workflowsteprun"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	actionlogFields := schema.ActionLog{}.Fields()
	_ = actionlogFields
	// actionlogDescActionName is the schema descriptor for action_name field.
	actionlogDescActionName := actionlogFields[1].Descriptor()
	// actionlog.ActionNameValidator is a validator for the "action_name" field. It is called by the builders before save.
	actionlog.ActionNameValidator = actionlogDescActionName.Validators[0].(func(string) error)
	// actionlogDescPrincipal is the schema descriptor for principal field.
	actionlogDescPrincipal := actionlogFields[2].Descriptor()
	// actionlog.PrincipalValidator is a validator for the "principal" field. It is called by the builders before save.
	actionlog.PrincipalValidator = actionlogDescPrincipal.Validators[0].(func(string) error)
	// actionlogDescStartedAt is the schema descriptor for started_at field.
	actionlogDescStartedAt := actionlogFields[7].Descriptor()
	// actionlog.DefaultStartedAt holds the default value on creation for the started_at field.
	actionlog.DefaultStartedAt = actionlogDescStartedAt.Default.(func() time.Time)
	// actionlogDescID is the schema descriptor for id field.
	actionlogDescID := actionlogFields[0].Descriptor()
	// actionlog.DefaultID holds the default value on creation for the id field.
	actionlog.DefaultID = actionlogDescID.Default.(func() uuid.UUID)
	agentmemoryFields := schema.AgentMemory{}.Fields()
	_ = agentmemoryFields
	// agentmemoryDescAgentName is the schema descriptor for agent_name field.
	agentmemoryDescAgentName := agentmemoryFields[1].Descriptor()
	// agentmemory.AgentNameValidator is a validator for the "agent_name" field. It is called by the builders before save.
	agentmemory.AgentNameValidator = agentmemoryDescAgentName.Validators[0].(func(string) error)
	// agentmemoryDescKey is the schema descriptor for key field.
	agentmemoryDescKey := agentmemoryFields[4].Descriptor()
	// agentmemory.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	agentmemory.KeyValidator = agentmemoryDescKey.Validators[0].(func(string) error)
	// agentmemoryDescContent is the schema descriptor for content field.
	agentmemoryDescContent := agentmemoryFields[5].Descriptor()
	// agentmemory.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	agentmemory.ContentValidator = agentmemoryDescContent.Validators[0].(func(string) error)
	// agentmemoryDescConfidence is the schema descriptor for confidence field.
	agentmemoryDescConfidence := agentmemoryFields[6].Descriptor()
	// agentmemory.DefaultConfidence holds the default value on creation for the confidence field.
	agentmemory.DefaultConfidence = agentmemoryDescConfidence.Default.(float64)
	// agentmemoryDescUseCount is the schema descriptor for use_count field.
	agentmemoryDescUseCount := agentmemoryFields[7].Descriptor()
	// agentmemory.DefaultUseCount holds the default value on creation for the use_count field.
	agentmemory.DefaultUseCount = agentmemoryDescUseCount.Default.(int)
	// agentmemoryDescCreatedAt is the schema descriptor for created_at field.
	agentmemoryDescCreatedAt := agentmemoryFields[9].Descriptor()
	// agentmemory.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentmemory.DefaultCreatedAt = agentmemoryDescCreatedAt.Default.(func() time.Time)
	// agentmemoryDescUpdatedAt is the schema descriptor for updated_at field.
	agentmemoryDescUpdatedAt := agentmemoryFields[10].Descriptor()
	// agentmemory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentmemory.DefaultUpdatedAt = agentmemoryDescUpdatedAt.Default.(func() time.Time)
	// agentmemory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentmemory.UpdateDefaultUpdatedAt = agentmemoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentmemoryDescID is the schema descriptor for id field.
	agentmemoryDescID := agentmemoryFields[0].Descriptor()
	// agentmemory.DefaultID holds the default value on creation for the id field.
	agentmemory.DefaultID = agentmemoryDescID.Default.(func() uuid.UUID)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescActor is the schema descriptor for actor field.
	auditlogDescActor := auditlogFields[3].Descriptor()
	// auditlog.ActorValidator is a validator for the "actor" field. It is called by the builders before save.
	auditlog.ActorValidator = auditlogDescActor.Validators[0].(func(string) error)
	// auditlogDescTimestamp is the schema descriptor for timestamp field.
	auditlogDescTimestamp := auditlogFields[6].Descriptor()
	// auditlog.DefaultTimestamp holds the default value on creation for the timestamp field.
	auditlog.DefaultTimestamp = auditlogDescTimestamp.Default.(func() time.Time)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogFields[0].Descriptor()
	// auditlog.DefaultID holds the default value on creation for the id field.
	auditlog.DefaultID = auditlogDescID.Default.(func() uuid.UUID)
	configprofileFields := schema.ConfigProfile{}.Fields()
	_ = configprofileFields
	// configprofileDescName is the schema descriptor for name field.
	configprofileDescName := configprofileFields[1].Descriptor()
	// configprofile.NameValidator is a validator for the "name" field. It is called by the builders before save.
	configprofile.NameValidator = configprofileDescName.Validators[0].(func(string) error)
	// configprofileDescActive is the schema descriptor for active field.
	configprofileDescActive := configprofileFields[3].Descriptor()
	// configprofile.DefaultActive holds the default value on creation for the active field.
	configprofile.DefaultActive = configprofileDescActive.Default.(bool)
	// configprofileDescVersion is the schema descriptor for version field.
	configprofileDescVersion := configprofileFields[4].Descriptor()
	// configprofile.DefaultVersion holds the default value on creation for the version field.
	configprofile.DefaultVersion = configprofileDescVersion.Default.(int)
	// configprofileDescCreatedAt is the schema descriptor for created_at field.
	configprofileDescCreatedAt := configprofileFields[5].Descriptor()
	// configprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	configprofile.DefaultCreatedAt = configprofileDescCreatedAt.Default.(func() time.Time)
	// configprofileDescUpdatedAt is the schema descriptor for updated_at field.
	configprofileDescUpdatedAt := configprofileFields[6].Descriptor()
	// configprofile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	configprofile.DefaultUpdatedAt = configprofileDescUpdatedAt.Default.(func() time.Time)
	// configprofile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	configprofile.UpdateDefaultUpdatedAt = configprofileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// configprofileDescID is the schema descriptor for id field.
	configprofileDescID := configprofileFields[0].Descriptor()
	// configprofile.DefaultID holds the default value on creation for the id field.
	configprofile.DefaultID = configprofileDescID.Default.(func() uuid.UUID)
	cronjobFields := schema.CronJob{}.Fields()
	_ = cronjobFields
	// cronjobDescName is the schema descriptor for name field.
	cronjobDescName := cronjobFields[1].Descriptor()
	// cronjob.NameValidator is a validator for the "name" field. It is called by the builders before save.
	cronjob.NameValidator = cronjobDescName.Validators[0].(func(string) error)
	// cronjobDescSchedule is the schema descriptor for schedule field.
	cronjobDescSchedule := cronjobFields[3].Descriptor()
	// cronjob.ScheduleValidator is a validator for the "schedule" field. It is called by the builders before save.
	cronjob.ScheduleValidator = cronjobDescSchedule.Validators[0].(func(string) error)
	// cronjobDescPrompt is the schema descriptor for prompt field.
	cronjobDescPrompt := cronjobFields[4].Descriptor()
	// cronjob.PromptValidator is a validator for the "prompt" field. It is called by the builders before save.
	cronjob.PromptValidator = cronjobDescPrompt.Validators[0].(func(string) error)
	// cronjobDescSessionMode is the schema descriptor for session_mode field.
	cronjobDescSessionMode := cronjobFields[5].Descriptor()
	// cronjob.DefaultSessionMode holds the default value on creation for the session_mode field.
	cronjob.DefaultSessionMode = cronjobDescSessionMode.Default.(string)
	// cronjobDescTimezone is the schema descriptor for timezone field.
	cronjobDescTimezone := cronjobFields[7].Descriptor()
	// cronjob.DefaultTimezone holds the default value on creation for the timezone field.
	cronjob.DefaultTimezone = cronjobDescTimezone.Default.(string)
	// cronjobDescEnabled is the schema descriptor for enabled field.
	cronjobDescEnabled := cronjobFields[8].Descriptor()
	// cronjob.DefaultEnabled holds the default value on creation for the enabled field.
	cronjob.DefaultEnabled = cronjobDescEnabled.Default.(bool)
	// cronjobDescCreatedAt is the schema descriptor for created_at field.
	cronjobDescCreatedAt := cronjobFields[12].Descriptor()
	// cronjob.DefaultCreatedAt holds the default value on creation for the created_at field.
	cronjob.DefaultCreatedAt = cronjobDescCreatedAt.Default.(func() time.Time)
	// cronjobDescUpdatedAt is the schema descriptor for updated_at field.
	cronjobDescUpdatedAt := cronjobFields[13].Descriptor()
	// cronjob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cronjob.DefaultUpdatedAt = cronjobDescUpdatedAt.Default.(func() time.Time)
	// cronjob.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cronjob.UpdateDefaultUpdatedAt = cronjobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cronjobDescID is the schema descriptor for id field.
	cronjobDescID := cronjobFields[0].Descriptor()
	// cronjob.DefaultID holds the default value on creation for the id field.
	cronjob.DefaultID = cronjobDescID.Default.(func() uuid.UUID)
	cronjobhistoryFields := schema.CronJobHistory{}.Fields()
	_ = cronjobhistoryFields
	// cronjobhistoryDescJobName is the schema descriptor for job_name field.
	cronjobhistoryDescJobName := cronjobhistoryFields[2].Descriptor()
	// cronjobhistory.JobNameValidator is a validator for the "job_name" field. It is called by the builders before save.
	cronjobhistory.JobNameValidator = cronjobhistoryDescJobName.Validators[0].(func(string) error)
	// cronjobhistoryDescTokensUsed is the schema descriptor for tokens_used field.
	cronjobhistoryDescTokensUsed := cronjobhistoryFields[7].Descriptor()
	// cronjobhistory.DefaultTokensUsed holds the default value on creation for the tokens_used field.
	cronjobhistory.DefaultTokensUsed = cronjobhistoryDescTokensUsed.Default.(int)
	// cronjobhistoryDescStartedAt is the schema descriptor for started_at field.
	cronjobhistoryDescStartedAt := cronjobhistoryFields[8].Descriptor()
	// cronjobhistory.DefaultStartedAt holds the default value on creation for the started_at field.
	cronjobhistory.DefaultStartedAt = cronjobhistoryDescStartedAt.Default.(func() time.Time)
	// cronjobhistoryDescID is the schema descriptor for id field.
	cronjobhistoryDescID := cronjobhistoryFields[0].Descriptor()
	// cronjobhistory.DefaultID holds the default value on creation for the id field.
	cronjobhistory.DefaultID = cronjobhistoryDescID.Default.(func() uuid.UUID)
	entityaliasFields := schema.EntityAlias{}.Fields()
	_ = entityaliasFields
	// entityaliasDescRawID is the schema descriptor for raw_id field.
	entityaliasDescRawID := entityaliasFields[1].Descriptor()
	// entityalias.RawIDValidator is a validator for the "raw_id" field. It is called by the builders before save.
	entityalias.RawIDValidator = entityaliasDescRawID.Validators[0].(func(string) error)
	// entityaliasDescCanonicalID is the schema descriptor for canonical_id field.
	entityaliasDescCanonicalID := entityaliasFields[2].Descriptor()
	// entityalias.CanonicalIDValidator is a validator for the "canonical_id" field. It is called by the builders before save.
	entityalias.CanonicalIDValidator = entityaliasDescCanonicalID.Validators[0].(func(string) error)
	// entityaliasDescSource is the schema descriptor for source field.
	entityaliasDescSource := entityaliasFields[3].Descriptor()
	// entityalias.DefaultSource holds the default value on creation for the source field.
	entityalias.DefaultSource = entityaliasDescSource.Default.(string)
	// entityaliasDescCreatedAt is the schema descriptor for created_at field.
	entityaliasDescCreatedAt := entityaliasFields[4].Descriptor()
	// entityalias.DefaultCreatedAt holds the default value on creation for the created_at field.
	entityalias.DefaultCreatedAt = entityaliasDescCreatedAt.Default.(func() time.Time)
	// entityaliasDescID is the schema descriptor for id field.
	entityaliasDescID := entityaliasFields[0].Descriptor()
	// entityalias.DefaultID holds the default value on creation for the id field.
	entityalias.DefaultID = entityaliasDescID.Default.(func() uuid.UUID)
	entitypropertyFields := schema.EntityProperty{}.Fields()
	_ = entitypropertyFields
	// entitypropertyDescEntityID is the schema descriptor for entity_id field.
	entitypropertyDescEntityID := entitypropertyFields[1].Descriptor()
	// entityproperty.EntityIDValidator is a validator for the "entity_id" field. It is called by the builders before save.
	entityproperty.EntityIDValidator = entitypropertyDescEntityID.Validators[0].(func(string) error)
	// entitypropertyDescEntityType is the schema descriptor for entity_type field.
	entitypropertyDescEntityType := entitypropertyFields[2].Descriptor()
	// entityproperty.EntityTypeValidator is a validator for the "entity_type" field. It is called by the builders before save.
	entityproperty.EntityTypeValidator = entitypropertyDescEntityType.Validators[0].(func(string) error)
	// entitypropertyDescProperty is the schema descriptor for property field.
	entitypropertyDescProperty := entitypropertyFields[3].Descriptor()
	// entityproperty.PropertyValidator is a validator for the "property" field. It is called by the builders before save.
	entityproperty.PropertyValidator = entitypropertyDescProperty.Validators[0].(func(string) error)
	// entitypropertyDescValueType is the schema descriptor for value_type field.
	entitypropertyDescValueType := entitypropertyFields[5].Descriptor()
	// entityproperty.DefaultValueType holds the default value on creation for the value_type field.
	entityproperty.DefaultValueType = entitypropertyDescValueType.Default.(string)
	// entitypropertyDescCreatedAt is the schema descriptor for created_at field.
	entitypropertyDescCreatedAt := entitypropertyFields[6].Descriptor()
	// entityproperty.DefaultCreatedAt holds the default value on creation for the created_at field.
	entityproperty.DefaultCreatedAt = entitypropertyDescCreatedAt.Default.(func() time.Time)
	// entitypropertyDescUpdatedAt is the schema descriptor for updated_at field.
	entitypropertyDescUpdatedAt := entitypropertyFields[7].Descriptor()
	// entityproperty.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	entityproperty.DefaultUpdatedAt = entitypropertyDescUpdatedAt.Default.(func() time.Time)
	// entityproperty.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	entityproperty.UpdateDefaultUpdatedAt = entitypropertyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entitypropertyDescID is the schema descriptor for id field.
	entitypropertyDescID := entitypropertyFields[0].Descriptor()
	// entityproperty.DefaultID holds the default value on creation for the id field.
	entityproperty.DefaultID = entitypropertyDescID.Default.(func() uuid.UUID)
	escrowdealFields := schema.EscrowDeal{}.Fields()
	_ = escrowdealFields
	// escrowdealDescEscrowID is the schema descriptor for escrow_id field.
	escrowdealDescEscrowID := escrowdealFields[0].Descriptor()
	// escrowdeal.EscrowIDValidator is a validator for the "escrow_id" field. It is called by the builders before save.
	escrowdeal.EscrowIDValidator = escrowdealDescEscrowID.Validators[0].(func(string) error)
	// escrowdealDescBuyerDid is the schema descriptor for buyer_did field.
	escrowdealDescBuyerDid := escrowdealFields[1].Descriptor()
	// escrowdeal.BuyerDidValidator is a validator for the "buyer_did" field. It is called by the builders before save.
	escrowdeal.BuyerDidValidator = escrowdealDescBuyerDid.Validators[0].(func(string) error)
	// escrowdealDescSellerDid is the schema descriptor for seller_did field.
	escrowdealDescSellerDid := escrowdealFields[2].Descriptor()
	// escrowdeal.SellerDidValidator is a validator for the "seller_did" field. It is called by the builders before save.
	escrowdeal.SellerDidValidator = escrowdealDescSellerDid.Validators[0].(func(string) error)
	// escrowdealDescTotalAmount is the schema descriptor for total_amount field.
	escrowdealDescTotalAmount := escrowdealFields[3].Descriptor()
	// escrowdeal.TotalAmountValidator is a validator for the "total_amount" field. It is called by the builders before save.
	escrowdeal.TotalAmountValidator = escrowdealDescTotalAmount.Validators[0].(func(string) error)
	// escrowdealDescStatus is the schema descriptor for status field.
	escrowdealDescStatus := escrowdealFields[4].Descriptor()
	// escrowdeal.DefaultStatus holds the default value on creation for the status field.
	escrowdeal.DefaultStatus = escrowdealDescStatus.Default.(string)
	// escrowdeal.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	escrowdeal.StatusValidator = escrowdealDescStatus.Validators[0].(func(string) error)
	// escrowdealDescChainID is the schema descriptor for chain_id field.
	escrowdealDescChainID := escrowdealFields[9].Descriptor()
	// escrowdeal.DefaultChainID holds the default value on creation for the chain_id field.
	escrowdeal.DefaultChainID = escrowdealDescChainID.Default.(int64)
	// escrowdealDescCreatedAt is the schema descriptor for created_at field.
	escrowdealDescCreatedAt := escrowdealFields[15].Descriptor()
	// escrowdeal.DefaultCreatedAt holds the default value on creation for the created_at field.
	escrowdeal.DefaultCreatedAt = escrowdealDescCreatedAt.Default.(func() time.Time)
	// escrowdealDescUpdatedAt is the schema descriptor for updated_at field.
	escrowdealDescUpdatedAt := escrowdealFields[16].Descriptor()
	// escrowdeal.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	escrowdeal.DefaultUpdatedAt = escrowdealDescUpdatedAt.Default.(func() time.Time)
	// escrowdeal.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	escrowdeal.UpdateDefaultUpdatedAt = escrowdealDescUpdatedAt.UpdateDefault.(func() time.Time)
	externalrefFields := schema.ExternalRef{}.Fields()
	_ = externalrefFields
	// externalrefDescName is the schema descriptor for name field.
	externalrefDescName := externalrefFields[1].Descriptor()
	// externalref.NameValidator is a validator for the "name" field. It is called by the builders before save.
	externalref.NameValidator = externalrefDescName.Validators[0].(func(string) error)
	// externalrefDescLocation is the schema descriptor for location field.
	externalrefDescLocation := externalrefFields[3].Descriptor()
	// externalref.LocationValidator is a validator for the "location" field. It is called by the builders before save.
	externalref.LocationValidator = externalrefDescLocation.Validators[0].(func(string) error)
	// externalrefDescCreatedAt is the schema descriptor for created_at field.
	externalrefDescCreatedAt := externalrefFields[6].Descriptor()
	// externalref.DefaultCreatedAt holds the default value on creation for the created_at field.
	externalref.DefaultCreatedAt = externalrefDescCreatedAt.Default.(func() time.Time)
	// externalrefDescUpdatedAt is the schema descriptor for updated_at field.
	externalrefDescUpdatedAt := externalrefFields[7].Descriptor()
	// externalref.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	externalref.DefaultUpdatedAt = externalrefDescUpdatedAt.Default.(func() time.Time)
	// externalref.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	externalref.UpdateDefaultUpdatedAt = externalrefDescUpdatedAt.UpdateDefault.(func() time.Time)
	// externalrefDescID is the schema descriptor for id field.
	externalrefDescID := externalrefFields[0].Descriptor()
	// externalref.DefaultID holds the default value on creation for the id field.
	externalref.DefaultID = externalrefDescID.Default.(func() uuid.UUID)
	inquiryFields := schema.Inquiry{}.Fields()
	_ = inquiryFields
	// inquiryDescSessionKey is the schema descriptor for session_key field.
	inquiryDescSessionKey := inquiryFields[1].Descriptor()
	// inquiry.SessionKeyValidator is a validator for the "session_key" field. It is called by the builders before save.
	inquiry.SessionKeyValidator = inquiryDescSessionKey.Validators[0].(func(string) error)
	// inquiryDescTopic is the schema descriptor for topic field.
	inquiryDescTopic := inquiryFields[2].Descriptor()
	// inquiry.TopicValidator is a validator for the "topic" field. It is called by the builders before save.
	inquiry.TopicValidator = inquiryDescTopic.Validators[0].(func(string) error)
	// inquiryDescQuestion is the schema descriptor for question field.
	inquiryDescQuestion := inquiryFields[3].Descriptor()
	// inquiry.QuestionValidator is a validator for the "question" field. It is called by the builders before save.
	inquiry.QuestionValidator = inquiryDescQuestion.Validators[0].(func(string) error)
	// inquiryDescCreatedAt is the schema descriptor for created_at field.
	inquiryDescCreatedAt := inquiryFields[10].Descriptor()
	// inquiry.DefaultCreatedAt holds the default value on creation for the created_at field.
	inquiry.DefaultCreatedAt = inquiryDescCreatedAt.Default.(func() time.Time)
	// inquiryDescID is the schema descriptor for id field.
	inquiryDescID := inquiryFields[0].Descriptor()
	// inquiry.DefaultID holds the default value on creation for the id field.
	inquiry.DefaultID = inquiryDescID.Default.(func() uuid.UUID)
	keyFields := schema.Key{}.Fields()
	_ = keyFields
	// keyDescName is the schema descriptor for name field.
	keyDescName := keyFields[1].Descriptor()
	// key.NameValidator is a validator for the "name" field. It is called by the builders before save.
	key.NameValidator = keyDescName.Validators[0].(func(string) error)
	// keyDescRemoteKeyID is the schema descriptor for remote_key_id field.
	keyDescRemoteKeyID := keyFields[2].Descriptor()
	// key.RemoteKeyIDValidator is a validator for the "remote_key_id" field. It is called by the builders before save.
	key.RemoteKeyIDValidator = keyDescRemoteKeyID.Validators[0].(func(string) error)
	// keyDescCreatedAt is the schema descriptor for created_at field.
	keyDescCreatedAt := keyFields[4].Descriptor()
	// key.DefaultCreatedAt holds the default value on creation for the created_at field.
	key.DefaultCreatedAt = keyDescCreatedAt.Default.(func() time.Time)
	// keyDescID is the schema descriptor for id field.
	keyDescID := keyFields[0].Descriptor()
	// key.DefaultID holds the default value on creation for the id field.
	key.DefaultID = keyDescID.Default.(func() uuid.UUID)
	knowledgeFields := schema.Knowledge{}.Fields()
	_ = knowledgeFields
	// knowledgeDescKey is the schema descriptor for key field.
	knowledgeDescKey := knowledgeFields[1].Descriptor()
	// knowledge.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	knowledge.KeyValidator = knowledgeDescKey.Validators[0].(func(string) error)
	// knowledgeDescContent is the schema descriptor for content field.
	knowledgeDescContent := knowledgeFields[3].Descriptor()
	// knowledge.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	knowledge.ContentValidator = knowledgeDescContent.Validators[0].(func(string) error)
	// knowledgeDescVersion is the schema descriptor for version field.
	knowledgeDescVersion := knowledgeFields[6].Descriptor()
	// knowledge.DefaultVersion holds the default value on creation for the version field.
	knowledge.DefaultVersion = knowledgeDescVersion.Default.(int)
	// knowledgeDescIsLatest is the schema descriptor for is_latest field.
	knowledgeDescIsLatest := knowledgeFields[7].Descriptor()
	// knowledge.DefaultIsLatest holds the default value on creation for the is_latest field.
	knowledge.DefaultIsLatest = knowledgeDescIsLatest.Default.(bool)
	// knowledgeDescUseCount is the schema descriptor for use_count field.
	knowledgeDescUseCount := knowledgeFields[8].Descriptor()
	// knowledge.DefaultUseCount holds the default value on creation for the use_count field.
	knowledge.DefaultUseCount = knowledgeDescUseCount.Default.(int)
	// knowledgeDescRelevanceScore is the schema descriptor for relevance_score field.
	knowledgeDescRelevanceScore := knowledgeFields[9].Descriptor()
	// knowledge.DefaultRelevanceScore holds the default value on creation for the relevance_score field.
	knowledge.DefaultRelevanceScore = knowledgeDescRelevanceScore.Default.(float64)
	// knowledgeDescCreatedAt is the schema descriptor for created_at field.
	knowledgeDescCreatedAt := knowledgeFields[10].Descriptor()
	// knowledge.DefaultCreatedAt holds the default value on creation for the created_at field.
	knowledge.DefaultCreatedAt = knowledgeDescCreatedAt.Default.(func() time.Time)
	// knowledgeDescUpdatedAt is the schema descriptor for updated_at field.
	knowledgeDescUpdatedAt := knowledgeFields[11].Descriptor()
	// knowledge.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	knowledge.DefaultUpdatedAt = knowledgeDescUpdatedAt.Default.(func() time.Time)
	// knowledge.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	knowledge.UpdateDefaultUpdatedAt = knowledgeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// knowledgeDescID is the schema descriptor for id field.
	knowledgeDescID := knowledgeFields[0].Descriptor()
	// knowledge.DefaultID holds the default value on creation for the id field.
	knowledge.DefaultID = knowledgeDescID.Default.(func() uuid.UUID)
	learningFields := schema.Learning{}.Fields()
	_ = learningFields
	// learningDescTrigger is the schema descriptor for trigger field.
	learningDescTrigger := learningFields[1].Descriptor()
	// learning.TriggerValidator is a validator for the "trigger" field. It is called by the builders before save.
	learning.TriggerValidator = learningDescTrigger.Validators[0].(func(string) error)
	// learningDescOccurrenceCount is the schema descriptor for occurrence_count field.
	learningDescOccurrenceCount := learningFields[7].Descriptor()
	// learning.DefaultOccurrenceCount holds the default value on creation for the occurrence_count field.
	learning.DefaultOccurrenceCount = learningDescOccurrenceCount.Default.(int)
	// learningDescSuccessCount is the schema descriptor for success_count field.
	learningDescSuccessCount := learningFields[8].Descriptor()
	// learning.DefaultSuccessCount holds the default value on creation for the success_count field.
	learning.DefaultSuccessCount = learningDescSuccessCount.Default.(int)
	// learningDescConfidence is the schema descriptor for confidence field.
	learningDescConfidence := learningFields[9].Descriptor()
	// learning.DefaultConfidence holds the default value on creation for the confidence field.
	learning.DefaultConfidence = learningDescConfidence.Default.(float64)
	// learningDescCreatedAt is the schema descriptor for created_at field.
	learningDescCreatedAt := learningFields[10].Descriptor()
	// learning.DefaultCreatedAt holds the default value on creation for the created_at field.
	learning.DefaultCreatedAt = learningDescCreatedAt.Default.(func() time.Time)
	// learningDescUpdatedAt is the schema descriptor for updated_at field.
	learningDescUpdatedAt := learningFields[11].Descriptor()
	// learning.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	learning.DefaultUpdatedAt = learningDescUpdatedAt.Default.(func() time.Time)
	// learning.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	learning.UpdateDefaultUpdatedAt = learningDescUpdatedAt.UpdateDefault.(func() time.Time)
	// learningDescID is the schema descriptor for id field.
	learningDescID := learningFields[0].Descriptor()
	// learning.DefaultID holds the default value on creation for the id field.
	learning.DefaultID = learningDescID.Default.(func() uuid.UUID)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescRole is the schema descriptor for role field.
	messageDescRole := messageFields[0].Descriptor()
	// message.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	message.RoleValidator = messageDescRole.Validators[0].(func(string) error)
	// messageDescTimestamp is the schema descriptor for timestamp field.
	messageDescTimestamp := messageFields[2].Descriptor()
	// message.DefaultTimestamp holds the default value on creation for the timestamp field.
	message.DefaultTimestamp = messageDescTimestamp.Default.(func() time.Time)
	// messageDescAuthor is the schema descriptor for author field.
	messageDescAuthor := messageFields[4].Descriptor()
	// message.DefaultAuthor holds the default value on creation for the author field.
	message.DefaultAuthor = messageDescAuthor.Default.(string)
	observationFields := schema.Observation{}.Fields()
	_ = observationFields
	// observationDescSessionKey is the schema descriptor for session_key field.
	observationDescSessionKey := observationFields[1].Descriptor()
	// observation.SessionKeyValidator is a validator for the "session_key" field. It is called by the builders before save.
	observation.SessionKeyValidator = observationDescSessionKey.Validators[0].(func(string) error)
	// observationDescContent is the schema descriptor for content field.
	observationDescContent := observationFields[2].Descriptor()
	// observation.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	observation.ContentValidator = observationDescContent.Validators[0].(func(string) error)
	// observationDescTokenCount is the schema descriptor for token_count field.
	observationDescTokenCount := observationFields[3].Descriptor()
	// observation.DefaultTokenCount holds the default value on creation for the token_count field.
	observation.DefaultTokenCount = observationDescTokenCount.Default.(int)
	// observationDescSourceStartIndex is the schema descriptor for source_start_index field.
	observationDescSourceStartIndex := observationFields[4].Descriptor()
	// observation.DefaultSourceStartIndex holds the default value on creation for the source_start_index field.
	observation.DefaultSourceStartIndex = observationDescSourceStartIndex.Default.(int)
	// observationDescSourceEndIndex is the schema descriptor for source_end_index field.
	observationDescSourceEndIndex := observationFields[5].Descriptor()
	// observation.DefaultSourceEndIndex holds the default value on creation for the source_end_index field.
	observation.DefaultSourceEndIndex = observationDescSourceEndIndex.Default.(int)
	// observationDescCreatedAt is the schema descriptor for created_at field.
	observationDescCreatedAt := observationFields[6].Descriptor()
	// observation.DefaultCreatedAt holds the default value on creation for the created_at field.
	observation.DefaultCreatedAt = observationDescCreatedAt.Default.(func() time.Time)
	// observationDescID is the schema descriptor for id field.
	observationDescID := observationFields[0].Descriptor()
	// observation.DefaultID holds the default value on creation for the id field.
	observation.DefaultID = observationDescID.Default.(func() uuid.UUID)
	ontologyconflictFields := schema.OntologyConflict{}.Fields()
	_ = ontologyconflictFields
	// ontologyconflictDescSubject is the schema descriptor for subject field.
	ontologyconflictDescSubject := ontologyconflictFields[1].Descriptor()
	// ontologyconflict.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	ontologyconflict.SubjectValidator = ontologyconflictDescSubject.Validators[0].(func(string) error)
	// ontologyconflictDescPredicate is the schema descriptor for predicate field.
	ontologyconflictDescPredicate := ontologyconflictFields[2].Descriptor()
	// ontologyconflict.PredicateValidator is a validator for the "predicate" field. It is called by the builders before save.
	ontologyconflict.PredicateValidator = ontologyconflictDescPredicate.Validators[0].(func(string) error)
	// ontologyconflictDescCreatedAt is the schema descriptor for created_at field.
	ontologyconflictDescCreatedAt := ontologyconflictFields[7].Descriptor()
	// ontologyconflict.DefaultCreatedAt holds the default value on creation for the created_at field.
	ontologyconflict.DefaultCreatedAt = ontologyconflictDescCreatedAt.Default.(func() time.Time)
	// ontologyconflictDescID is the schema descriptor for id field.
	ontologyconflictDescID := ontologyconflictFields[0].Descriptor()
	// ontologyconflict.DefaultID holds the default value on creation for the id field.
	ontologyconflict.DefaultID = ontologyconflictDescID.Default.(func() uuid.UUID)
	ontologypredicateFields := schema.OntologyPredicate{}.Fields()
	_ = ontologypredicateFields
	// ontologypredicateDescName is the schema descriptor for name field.
	ontologypredicateDescName := ontologypredicateFields[1].Descriptor()
	// ontologypredicate.NameValidator is a validator for the "name" field. It is called by the builders before save.
	ontologypredicate.NameValidator = ontologypredicateDescName.Validators[0].(func(string) error)
	// ontologypredicateDescDescription is the schema descriptor for description field.
	ontologypredicateDescDescription := ontologypredicateFields[2].Descriptor()
	// ontologypredicate.DefaultDescription holds the default value on creation for the description field.
	ontologypredicate.DefaultDescription = ontologypredicateDescDescription.Default.(string)
	// ontologypredicateDescVersion is the schema descriptor for version field.
	ontologypredicateDescVersion := ontologypredicateFields[8].Descriptor()
	// ontologypredicate.DefaultVersion holds the default value on creation for the version field.
	ontologypredicate.DefaultVersion = ontologypredicateDescVersion.Default.(int)
	// ontologypredicateDescCreatedAt is the schema descriptor for created_at field.
	ontologypredicateDescCreatedAt := ontologypredicateFields[9].Descriptor()
	// ontologypredicate.DefaultCreatedAt holds the default value on creation for the created_at field.
	ontologypredicate.DefaultCreatedAt = ontologypredicateDescCreatedAt.Default.(func() time.Time)
	// ontologypredicateDescUpdatedAt is the schema descriptor for updated_at field.
	ontologypredicateDescUpdatedAt := ontologypredicateFields[10].Descriptor()
	// ontologypredicate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ontologypredicate.DefaultUpdatedAt = ontologypredicateDescUpdatedAt.Default.(func() time.Time)
	// ontologypredicate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ontologypredicate.UpdateDefaultUpdatedAt = ontologypredicateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ontologypredicateDescID is the schema descriptor for id field.
	ontologypredicateDescID := ontologypredicateFields[0].Descriptor()
	// ontologypredicate.DefaultID holds the default value on creation for the id field.
	ontologypredicate.DefaultID = ontologypredicateDescID.Default.(func() uuid.UUID)
	ontologytypeFields := schema.OntologyType{}.Fields()
	_ = ontologytypeFields
	// ontologytypeDescName is the schema descriptor for name field.
	ontologytypeDescName := ontologytypeFields[1].Descriptor()
	// ontologytype.NameValidator is a validator for the "name" field. It is called by the builders before save.
	ontologytype.NameValidator = ontologytypeDescName.Validators[0].(func(string) error)
	// ontologytypeDescDescription is the schema descriptor for description field.
	ontologytypeDescDescription := ontologytypeFields[2].Descriptor()
	// ontologytype.DefaultDescription holds the default value on creation for the description field.
	ontologytype.DefaultDescription = ontologytypeDescDescription.Default.(string)
	// ontologytypeDescVersion is the schema descriptor for version field.
	ontologytypeDescVersion := ontologytypeFields[6].Descriptor()
	// ontologytype.DefaultVersion holds the default value on creation for the version field.
	ontologytype.DefaultVersion = ontologytypeDescVersion.Default.(int)
	// ontologytypeDescCreatedAt is the schema descriptor for created_at field.
	ontologytypeDescCreatedAt := ontologytypeFields[7].Descriptor()
	// ontologytype.DefaultCreatedAt holds the default value on creation for the created_at field.
	ontologytype.DefaultCreatedAt = ontologytypeDescCreatedAt.Default.(func() time.Time)
	// ontologytypeDescUpdatedAt is the schema descriptor for updated_at field.
	ontologytypeDescUpdatedAt := ontologytypeFields[8].Descriptor()
	// ontologytype.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ontologytype.DefaultUpdatedAt = ontologytypeDescUpdatedAt.Default.(func() time.Time)
	// ontologytype.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ontologytype.UpdateDefaultUpdatedAt = ontologytypeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ontologytypeDescID is the schema descriptor for id field.
	ontologytypeDescID := ontologytypeFields[0].Descriptor()
	// ontologytype.DefaultID holds the default value on creation for the id field.
	ontologytype.DefaultID = ontologytypeDescID.Default.(func() uuid.UUID)
	paymenttxFields := schema.PaymentTx{}.Fields()
	_ = paymenttxFields
	// paymenttxDescFromAddress is the schema descriptor for from_address field.
	paymenttxDescFromAddress := paymenttxFields[2].Descriptor()
	// paymenttx.FromAddressValidator is a validator for the "from_address" field. It is called by the builders before save.
	paymenttx.FromAddressValidator = paymenttxDescFromAddress.Validators[0].(func(string) error)
	// paymenttxDescToAddress is the schema descriptor for to_address field.
	paymenttxDescToAddress := paymenttxFields[3].Descriptor()
	// paymenttx.ToAddressValidator is a validator for the "to_address" field. It is called by the builders before save.
	paymenttx.ToAddressValidator = paymenttxDescToAddress.Validators[0].(func(string) error)
	// paymenttxDescAmount is the schema descriptor for amount field.
	paymenttxDescAmount := paymenttxFields[4].Descriptor()
	// paymenttx.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	paymenttx.AmountValidator = paymenttxDescAmount.Validators[0].(func(string) error)
	// paymenttxDescCreatedAt is the schema descriptor for created_at field.
	paymenttxDescCreatedAt := paymenttxFields[12].Descriptor()
	// paymenttx.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymenttx.DefaultCreatedAt = paymenttxDescCreatedAt.Default.(func() time.Time)
	// paymenttxDescUpdatedAt is the schema descriptor for updated_at field.
	paymenttxDescUpdatedAt := paymenttxFields[13].Descriptor()
	// paymenttx.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	paymenttx.DefaultUpdatedAt = paymenttxDescUpdatedAt.Default.(func() time.Time)
	// paymenttx.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	paymenttx.UpdateDefaultUpdatedAt = paymenttxDescUpdatedAt.UpdateDefault.(func() time.Time)
	// paymenttxDescID is the schema descriptor for id field.
	paymenttxDescID := paymenttxFields[0].Descriptor()
	// paymenttx.DefaultID holds the default value on creation for the id field.
	paymenttx.DefaultID = paymenttxDescID.Default.(func() uuid.UUID)
	peerreputationFields := schema.PeerReputation{}.Fields()
	_ = peerreputationFields
	// peerreputationDescPeerDid is the schema descriptor for peer_did field.
	peerreputationDescPeerDid := peerreputationFields[1].Descriptor()
	// peerreputation.PeerDidValidator is a validator for the "peer_did" field. It is called by the builders before save.
	peerreputation.PeerDidValidator = peerreputationDescPeerDid.Validators[0].(func(string) error)
	// peerreputationDescSuccessfulExchanges is the schema descriptor for successful_exchanges field.
	peerreputationDescSuccessfulExchanges := peerreputationFields[2].Descriptor()
	// peerreputation.DefaultSuccessfulExchanges holds the default value on creation for the successful_exchanges field.
	peerreputation.DefaultSuccessfulExchanges = peerreputationDescSuccessfulExchanges.Default.(int)
	// peerreputationDescFailedExchanges is the schema descriptor for failed_exchanges field.
	peerreputationDescFailedExchanges := peerreputationFields[3].Descriptor()
	// peerreputation.DefaultFailedExchanges holds the default value on creation for the failed_exchanges field.
	peerreputation.DefaultFailedExchanges = peerreputationDescFailedExchanges.Default.(int)
	// peerreputationDescTimeoutCount is the schema descriptor for timeout_count field.
	peerreputationDescTimeoutCount := peerreputationFields[4].Descriptor()
	// peerreputation.DefaultTimeoutCount holds the default value on creation for the timeout_count field.
	peerreputation.DefaultTimeoutCount = peerreputationDescTimeoutCount.Default.(int)
	// peerreputationDescTrustScore is the schema descriptor for trust_score field.
	peerreputationDescTrustScore := peerreputationFields[5].Descriptor()
	// peerreputation.DefaultTrustScore holds the default value on creation for the trust_score field.
	peerreputation.DefaultTrustScore = peerreputationDescTrustScore.Default.(float64)
	// peerreputationDescFirstSeen is the schema descriptor for first_seen field.
	peerreputationDescFirstSeen := peerreputationFields[6].Descriptor()
	// peerreputation.DefaultFirstSeen holds the default value on creation for the first_seen field.
	peerreputation.DefaultFirstSeen = peerreputationDescFirstSeen.Default.(func() time.Time)
	// peerreputationDescLastInteraction is the schema descriptor for last_interaction field.
	peerreputationDescLastInteraction := peerreputationFields[7].Descriptor()
	// peerreputation.DefaultLastInteraction holds the default value on creation for the last_interaction field.
	peerreputation.DefaultLastInteraction = peerreputationDescLastInteraction.Default.(func() time.Time)
	// peerreputation.UpdateDefaultLastInteraction holds the default value on update for the last_interaction field.
	peerreputation.UpdateDefaultLastInteraction = peerreputationDescLastInteraction.UpdateDefault.(func() time.Time)
	// peerreputationDescCreatedAt is the schema descriptor for created_at field.
	peerreputationDescCreatedAt := peerreputationFields[8].Descriptor()
	// peerreputation.DefaultCreatedAt holds the default value on creation for the created_at field.
	peerreputation.DefaultCreatedAt = peerreputationDescCreatedAt.Default.(func() time.Time)
	// peerreputationDescUpdatedAt is the schema descriptor for updated_at field.
	peerreputationDescUpdatedAt := peerreputationFields[9].Descriptor()
	// peerreputation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	peerreputation.DefaultUpdatedAt = peerreputationDescUpdatedAt.Default.(func() time.Time)
	// peerreputation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	peerreputation.UpdateDefaultUpdatedAt = peerreputationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// peerreputationDescID is the schema descriptor for id field.
	peerreputationDescID := peerreputationFields[0].Descriptor()
	// peerreputation.DefaultID holds the default value on creation for the id field.
	peerreputation.DefaultID = peerreputationDescID.Default.(func() uuid.UUID)
	provenanceattributionFields := schema.ProvenanceAttribution{}.Fields()
	_ = provenanceattributionFields
	// provenanceattributionDescSessionKey is the schema descriptor for session_key field.
	provenanceattributionDescSessionKey := provenanceattributionFields[1].Descriptor()
	// provenanceattribution.SessionKeyValidator is a validator for the "session_key" field. It is called by the builders before save.
	provenanceattribution.SessionKeyValidator = provenanceattributionDescSessionKey.Validators[0].(func(string) error)
	// provenanceattributionDescAuthorType is the schema descriptor for author_type field.
	provenanceattributionDescAuthorType := provenanceattributionFields[4].Descriptor()
	// provenanceattribution.AuthorTypeValidator is a validator for the "author_type" field. It is called by the builders before save.
	provenanceattribution.AuthorTypeValidator = provenanceattributionDescAuthorType.Validators[0].(func(string) error)
	// provenanceattributionDescAuthorID is the schema descriptor for author_id field.
	provenanceattributionDescAuthorID := provenanceattributionFields[5].Descriptor()
	// provenanceattribution.AuthorIDValidator is a validator for the "author_id" field. It is called by the builders before save.
	provenanceattribution.AuthorIDValidator = provenanceattributionDescAuthorID.Validators[0].(func(string) error)
	// provenanceattributionDescSource is the schema descriptor for source field.
	provenanceattributionDescSource := provenanceattributionFields[9].Descriptor()
	// provenanceattribution.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	provenanceattribution.SourceValidator = provenanceattributionDescSource.Validators[0].(func(string) error)
	// provenanceattributionDescLinesAdded is the schema descriptor for lines_added field.
	provenanceattributionDescLinesAdded := provenanceattributionFields[10].Descriptor()
	// provenanceattribution.DefaultLinesAdded holds the default value on creation for the lines_added field.
	provenanceattribution.DefaultLinesAdded = provenanceattributionDescLinesAdded.Default.(int)
	// provenanceattributionDescLinesRemoved is the schema descriptor for lines_removed field.
	provenanceattributionDescLinesRemoved := provenanceattributionFields[11].Descriptor()
	// provenanceattribution.DefaultLinesRemoved holds the default value on creation for the lines_removed field.
	provenanceattribution.DefaultLinesRemoved = provenanceattributionDescLinesRemoved.Default.(int)
	// provenanceattributionDescCreatedAt is the schema descriptor for created_at field.
	provenanceattributionDescCreatedAt := provenanceattributionFields[12].Descriptor()
	// provenanceattribution.DefaultCreatedAt holds the default value on creation for the created_at field.
	provenanceattribution.DefaultCreatedAt = provenanceattributionDescCreatedAt.Default.(func() time.Time)
	// provenanceattributionDescID is the schema descriptor for id field.
	provenanceattributionDescID := provenanceattributionFields[0].Descriptor()
	// provenanceattribution.DefaultID holds the default value on creation for the id field.
	provenanceattribution.DefaultID = provenanceattributionDescID.Default.(func() uuid.UUID)
	provenancecheckpointFields := schema.ProvenanceCheckpoint{}.Fields()
	_ = provenancecheckpointFields
	// provenancecheckpointDescLabel is the schema descriptor for label field.
	provenancecheckpointDescLabel := provenancecheckpointFields[3].Descriptor()
	// provenancecheckpoint.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	provenancecheckpoint.LabelValidator = provenancecheckpointDescLabel.Validators[0].(func(string) error)
	// provenancecheckpointDescJournalSeq is the schema descriptor for journal_seq field.
	provenancecheckpointDescJournalSeq := provenancecheckpointFields[5].Descriptor()
	// provenancecheckpoint.DefaultJournalSeq holds the default value on creation for the journal_seq field.
	provenancecheckpoint.DefaultJournalSeq = provenancecheckpointDescJournalSeq.Default.(int64)
	// provenancecheckpointDescCreatedAt is the schema descriptor for created_at field.
	provenancecheckpointDescCreatedAt := provenancecheckpointFields[8].Descriptor()
	// provenancecheckpoint.DefaultCreatedAt holds the default value on creation for the created_at field.
	provenancecheckpoint.DefaultCreatedAt = provenancecheckpointDescCreatedAt.Default.(func() time.Time)
	// provenancecheckpointDescID is the schema descriptor for id field.
	provenancecheckpointDescID := provenancecheckpointFields[0].Descriptor()
	// provenancecheckpoint.DefaultID holds the default value on creation for the id field.
	provenancecheckpoint.DefaultID = provenancecheckpointDescID.Default.(func() uuid.UUID)
	reflectionFields := schema.Reflection{}.Fields()
	_ = reflectionFields
	// reflectionDescSessionKey is the schema descriptor for session_key field.
	reflectionDescSessionKey := reflectionFields[1].Descriptor()
	// reflection.SessionKeyValidator is a validator for the "session_key" field. It is called by the builders before save.
	reflection.SessionKeyValidator = reflectionDescSessionKey.Validators[0].(func(string) error)
	// reflectionDescContent is the schema descriptor for content field.
	reflectionDescContent := reflectionFields[2].Descriptor()
	// reflection.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	reflection.ContentValidator = reflectionDescContent.Validators[0].(func(string) error)
	// reflectionDescTokenCount is the schema descriptor for token_count field.
	reflectionDescTokenCount := reflectionFields[3].Descriptor()
	// reflection.DefaultTokenCount holds the default value on creation for the token_count field.
	reflection.DefaultTokenCount = reflectionDescTokenCount.Default.(int)
	// reflectionDescGeneration is the schema descriptor for generation field.
	reflectionDescGeneration := reflectionFields[4].Descriptor()
	// reflection.DefaultGeneration holds the default value on creation for the generation field.
	reflection.DefaultGeneration = reflectionDescGeneration.Default.(int)
	// reflectionDescCreatedAt is the schema descriptor for created_at field.
	reflectionDescCreatedAt := reflectionFields[5].Descriptor()
	// reflection.DefaultCreatedAt holds the default value on creation for the created_at field.
	reflection.DefaultCreatedAt = reflectionDescCreatedAt.Default.(func() time.Time)
	// reflectionDescID is the schema descriptor for id field.
	reflectionDescID := reflectionFields[0].Descriptor()
	// reflection.DefaultID holds the default value on creation for the id field.
	reflection.DefaultID = reflectionDescID.Default.(func() uuid.UUID)
	runjournalFields := schema.RunJournal{}.Fields()
	_ = runjournalFields
	// runjournalDescRunID is the schema descriptor for run_id field.
	runjournalDescRunID := runjournalFields[1].Descriptor()
	// runjournal.RunIDValidator is a validator for the "run_id" field. It is called by the builders before save.
	runjournal.RunIDValidator = runjournalDescRunID.Validators[0].(func(string) error)
	// runjournalDescTimestamp is the schema descriptor for timestamp field.
	runjournalDescTimestamp := runjournalFields[4].Descriptor()
	// runjournal.DefaultTimestamp holds the default value on creation for the timestamp field.
	runjournal.DefaultTimestamp = runjournalDescTimestamp.Default.(func() time.Time)
	// runjournalDescID is the schema descriptor for id field.
	runjournalDescID := runjournalFields[0].Descriptor()
	// runjournal.DefaultID holds the default value on creation for the id field.
	runjournal.DefaultID = runjournalDescID.Default.(func() uuid.UUID)
	runsnapshotFields := schema.RunSnapshot{}.Fields()
	_ = runsnapshotFields
	// runsnapshotDescRunID is the schema descriptor for run_id field.
	runsnapshotDescRunID := runsnapshotFields[1].Descriptor()
	// runsnapshot.RunIDValidator is a validator for the "run_id" field. It is called by the builders before save.
	runsnapshot.RunIDValidator = runsnapshotDescRunID.Validators[0].(func(string) error)
	// runsnapshotDescLastJournalSeq is the schema descriptor for last_journal_seq field.
	runsnapshotDescLastJournalSeq := runsnapshotFields[6].Descriptor()
	// runsnapshot.DefaultLastJournalSeq holds the default value on creation for the last_journal_seq field.
	runsnapshot.DefaultLastJournalSeq = runsnapshotDescLastJournalSeq.Default.(int64)
	// runsnapshotDescCreatedAt is the schema descriptor for created_at field.
	runsnapshotDescCreatedAt := runsnapshotFields[7].Descriptor()
	// runsnapshot.DefaultCreatedAt holds the default value on creation for the created_at field.
	runsnapshot.DefaultCreatedAt = runsnapshotDescCreatedAt.Default.(func() time.Time)
	// runsnapshotDescUpdatedAt is the schema descriptor for updated_at field.
	runsnapshotDescUpdatedAt := runsnapshotFields[8].Descriptor()
	// runsnapshot.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	runsnapshot.DefaultUpdatedAt = runsnapshotDescUpdatedAt.Default.(func() time.Time)
	// runsnapshot.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	runsnapshot.UpdateDefaultUpdatedAt = runsnapshotDescUpdatedAt.UpdateDefault.(func() time.Time)
	// runsnapshotDescID is the schema descriptor for id field.
	runsnapshotDescID := runsnapshotFields[0].Descriptor()
	// runsnapshot.DefaultID holds the default value on creation for the id field.
	runsnapshot.DefaultID = runsnapshotDescID.Default.(func() uuid.UUID)
	runstepFields := schema.RunStep{}.Fields()
	_ = runstepFields
	// runstepDescRunID is the schema descriptor for run_id field.
	runstepDescRunID := runstepFields[1].Descriptor()
	// runstep.RunIDValidator is a validator for the "run_id" field. It is called by the builders before save.
	runstep.RunIDValidator = runstepDescRunID.Validators[0].(func(string) error)
	// runstepDescStepID is the schema descriptor for step_id field.
	runstepDescStepID := runstepFields[2].Descriptor()
	// runstep.StepIDValidator is a validator for the "step_id" field. It is called by the builders before save.
	runstep.StepIDValidator = runstepDescStepID.Validators[0].(func(string) error)
	// runstepDescStepIndex is the schema descriptor for step_index field.
	runstepDescStepIndex := runstepFields[3].Descriptor()
	// runstep.DefaultStepIndex holds the default value on creation for the step_index field.
	runstep.DefaultStepIndex = runstepDescStepIndex.Default.(int)
	// runstepDescRetryCount is the schema descriptor for retry_count field.
	runstepDescRetryCount := runstepFields[10].Descriptor()
	// runstep.DefaultRetryCount holds the default value on creation for the retry_count field.
	runstep.DefaultRetryCount = runstepDescRetryCount.Default.(int)
	// runstepDescMaxRetries is the schema descriptor for max_retries field.
	runstepDescMaxRetries := runstepFields[11].Descriptor()
	// runstep.DefaultMaxRetries holds the default value on creation for the max_retries field.
	runstep.DefaultMaxRetries = runstepDescMaxRetries.Default.(int)
	// runstepDescCreatedAt is the schema descriptor for created_at field.
	runstepDescCreatedAt := runstepFields[12].Descriptor()
	// runstep.DefaultCreatedAt holds the default value on creation for the created_at field.
	runstep.DefaultCreatedAt = runstepDescCreatedAt.Default.(func() time.Time)
	// runstepDescUpdatedAt is the schema descriptor for updated_at field.
	runstepDescUpdatedAt := runstepFields[13].Descriptor()
	// runstep.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	runstep.DefaultUpdatedAt = runstepDescUpdatedAt.Default.(func() time.Time)
	// runstep.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	runstep.UpdateDefaultUpdatedAt = runstepDescUpdatedAt.UpdateDefault.(func() time.Time)
	// runstepDescID is the schema descriptor for id field.
	runstepDescID := runstepFields[0].Descriptor()
	// runstep.DefaultID holds the default value on creation for the id field.
	runstep.DefaultID = runstepDescID.Default.(func() uuid.UUID)
	secretFields := schema.Secret{}.Fields()
	_ = secretFields
	// secretDescName is the schema descriptor for name field.
	secretDescName := secretFields[1].Descriptor()
	// secret.NameValidator is a validator for the "name" field. It is called by the builders before save.
	secret.NameValidator = secretDescName.Validators[0].(func(string) error)
	// secretDescCreatedAt is the schema descriptor for created_at field.
	secretDescCreatedAt := secretFields[3].Descriptor()
	// secret.DefaultCreatedAt holds the default value on creation for the created_at field.
	secret.DefaultCreatedAt = secretDescCreatedAt.Default.(func() time.Time)
	// secretDescUpdatedAt is the schema descriptor for updated_at field.
	secretDescUpdatedAt := secretFields[4].Descriptor()
	// secret.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	secret.DefaultUpdatedAt = secretDescUpdatedAt.Default.(func() time.Time)
	// secret.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	secret.UpdateDefaultUpdatedAt = secretDescUpdatedAt.UpdateDefault.(func() time.Time)
	// secretDescAccessCount is the schema descriptor for access_count field.
	secretDescAccessCount := secretFields[5].Descriptor()
	// secret.DefaultAccessCount holds the default value on creation for the access_count field.
	secret.DefaultAccessCount = secretDescAccessCount.Default.(int)
	// secretDescID is the schema descriptor for id field.
	secretDescID := secretFields[0].Descriptor()
	// secret.DefaultID holds the default value on creation for the id field.
	secret.DefaultID = secretDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescKey is the schema descriptor for key field.
	sessionDescKey := sessionFields[0].Descriptor()
	// session.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	session.KeyValidator = sessionDescKey.Validators[0].(func(string) error)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[6].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionFields[7].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	sessionprovenanceFields := schema.SessionProvenance{}.Fields()
	_ = sessionprovenanceFields
	// sessionprovenanceDescSessionKey is the schema descriptor for session_key field.
	sessionprovenanceDescSessionKey := sessionprovenanceFields[1].Descriptor()
	// sessionprovenance.SessionKeyValidator is a validator for the "session_key" field. It is called by the builders before save.
	sessionprovenance.SessionKeyValidator = sessionprovenanceDescSessionKey.Validators[0].(func(string) error)
	// sessionprovenanceDescAgentName is the schema descriptor for agent_name field.
	sessionprovenanceDescAgentName := sessionprovenanceFields[3].Descriptor()
	// sessionprovenance.AgentNameValidator is a validator for the "agent_name" field. It is called by the builders before save.
	sessionprovenance.AgentNameValidator = sessionprovenanceDescAgentName.Validators[0].(func(string) error)
	// sessionprovenanceDescDepth is the schema descriptor for depth field.
	sessionprovenanceDescDepth := sessionprovenanceFields[7].Descriptor()
	// sessionprovenance.DefaultDepth holds the default value on creation for the depth field.
	sessionprovenance.DefaultDepth = sessionprovenanceDescDepth.Default.(int)
	// sessionprovenanceDescCreatedAt is the schema descriptor for created_at field.
	sessionprovenanceDescCreatedAt := sessionprovenanceFields[9].Descriptor()
	// sessionprovenance.DefaultCreatedAt holds the default value on creation for the created_at field.
	sessionprovenance.DefaultCreatedAt = sessionprovenanceDescCreatedAt.Default.(func() time.Time)
	// sessionprovenanceDescID is the schema descriptor for id field.
	sessionprovenanceDescID := sessionprovenanceFields[0].Descriptor()
	// sessionprovenance.DefaultID holds the default value on creation for the id field.
	sessionprovenance.DefaultID = sessionprovenanceDescID.Default.(func() uuid.UUID)
	tokenusageFields := schema.TokenUsage{}.Fields()
	_ = tokenusageFields
	// tokenusageDescProvider is the schema descriptor for provider field.
	tokenusageDescProvider := tokenusageFields[2].Descriptor()
	// tokenusage.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	tokenusage.ProviderValidator = tokenusageDescProvider.Validators[0].(func(string) error)
	// tokenusageDescModel is the schema descriptor for model field.
	tokenusageDescModel := tokenusageFields[3].Descriptor()
	// tokenusage.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	tokenusage.ModelValidator = tokenusageDescModel.Validators[0].(func(string) error)
	// tokenusageDescInputTokens is the schema descriptor for input_tokens field.
	tokenusageDescInputTokens := tokenusageFields[5].Descriptor()
	// tokenusage.DefaultInputTokens holds the default value on creation for the input_tokens field.
	tokenusage.DefaultInputTokens = tokenusageDescInputTokens.Default.(int64)
	// tokenusageDescOutputTokens is the schema descriptor for output_tokens field.
	tokenusageDescOutputTokens := tokenusageFields[6].Descriptor()
	// tokenusage.DefaultOutputTokens holds the default value on creation for the output_tokens field.
	tokenusage.DefaultOutputTokens = tokenusageDescOutputTokens.Default.(int64)
	// tokenusageDescTotalTokens is the schema descriptor for total_tokens field.
	tokenusageDescTotalTokens := tokenusageFields[7].Descriptor()
	// tokenusage.DefaultTotalTokens holds the default value on creation for the total_tokens field.
	tokenusage.DefaultTotalTokens = tokenusageDescTotalTokens.Default.(int64)
	// tokenusageDescCacheTokens is the schema descriptor for cache_tokens field.
	tokenusageDescCacheTokens := tokenusageFields[8].Descriptor()
	// tokenusage.DefaultCacheTokens holds the default value on creation for the cache_tokens field.
	tokenusage.DefaultCacheTokens = tokenusageDescCacheTokens.Default.(int64)
	// tokenusageDescTimestamp is the schema descriptor for timestamp field.
	tokenusageDescTimestamp := tokenusageFields[9].Descriptor()
	// tokenusage.DefaultTimestamp holds the default value on creation for the timestamp field.
	tokenusage.DefaultTimestamp = tokenusageDescTimestamp.Default.(func() time.Time)
	// tokenusageDescID is the schema descriptor for id field.
	tokenusageDescID := tokenusageFields[0].Descriptor()
	// tokenusage.DefaultID holds the default value on creation for the id field.
	tokenusage.DefaultID = tokenusageDescID.Default.(func() uuid.UUID)
	turntraceFields := schema.TurnTrace{}.Fields()
	_ = turntraceFields
	// turntraceDescTraceID is the schema descriptor for trace_id field.
	turntraceDescTraceID := turntraceFields[1].Descriptor()
	// turntrace.TraceIDValidator is a validator for the "trace_id" field. It is called by the builders before save.
	turntrace.TraceIDValidator = turntraceDescTraceID.Validators[0].(func(string) error)
	// turntraceDescSessionKey is the schema descriptor for session_key field.
	turntraceDescSessionKey := turntraceFields[2].Descriptor()
	// turntrace.SessionKeyValidator is a validator for the "session_key" field. It is called by the builders before save.
	turntrace.SessionKeyValidator = turntraceDescSessionKey.Validators[0].(func(string) error)
	// turntraceDescEntrypoint is the schema descriptor for entrypoint field.
	turntraceDescEntrypoint := turntraceFields[3].Descriptor()
	// turntrace.EntrypointValidator is a validator for the "entrypoint" field. It is called by the builders before save.
	turntrace.EntrypointValidator = turntraceDescEntrypoint.Validators[0].(func(string) error)
	// turntraceDescOutcome is the schema descriptor for outcome field.
	turntraceDescOutcome := turntraceFields[4].Descriptor()
	// turntrace.DefaultOutcome holds the default value on creation for the outcome field.
	turntrace.DefaultOutcome = turntraceDescOutcome.Default.(string)
	// turntraceDescStartedAt is the schema descriptor for started_at field.
	turntraceDescStartedAt := turntraceFields[9].Descriptor()
	// turntrace.DefaultStartedAt holds the default value on creation for the started_at field.
	turntrace.DefaultStartedAt = turntraceDescStartedAt.Default.(func() time.Time)
	// turntraceDescID is the schema descriptor for id field.
	turntraceDescID := turntraceFields[0].Descriptor()
	// turntrace.DefaultID holds the default value on creation for the id field.
	turntrace.DefaultID = turntraceDescID.Default.(func() uuid.UUID)
	turntraceeventFields := schema.TurnTraceEvent{}.Fields()
	_ = turntraceeventFields
	// turntraceeventDescTraceID is the schema descriptor for trace_id field.
	turntraceeventDescTraceID := turntraceeventFields[1].Descriptor()
	// turntraceevent.TraceIDValidator is a validator for the "trace_id" field. It is called by the builders before save.
	turntraceevent.TraceIDValidator = turntraceeventDescTraceID.Validators[0].(func(string) error)
	// turntraceeventDescEventType is the schema descriptor for event_type field.
	turntraceeventDescEventType := turntraceeventFields[3].Descriptor()
	// turntraceevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	turntraceevent.EventTypeValidator = turntraceeventDescEventType.Validators[0].(func(string) error)
	// turntraceeventDescPayloadTruncated is the schema descriptor for payload_truncated field.
	turntraceeventDescPayloadTruncated := turntraceeventFields[8].Descriptor()
	// turntraceevent.DefaultPayloadTruncated holds the default value on creation for the payload_truncated field.
	turntraceevent.DefaultPayloadTruncated = turntraceeventDescPayloadTruncated.Default.(bool)
	// turntraceeventDescCreatedAt is the schema descriptor for created_at field.
	turntraceeventDescCreatedAt := turntraceeventFields[9].Descriptor()
	// turntraceevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	turntraceevent.DefaultCreatedAt = turntraceeventDescCreatedAt.Default.(func() time.Time)
	// turntraceeventDescID is the schema descriptor for id field.
	turntraceeventDescID := turntraceeventFields[0].Descriptor()
	// turntraceevent.DefaultID holds the default value on creation for the id field.
	turntraceevent.DefaultID = turntraceeventDescID.Default.(func() uuid.UUID)
	workflowrunFields := schema.WorkflowRun{}.Fields()
	_ = workflowrunFields
	// workflowrunDescWorkflowName is the schema descriptor for workflow_name field.
	workflowrunDescWorkflowName := workflowrunFields[1].Descriptor()
	// workflowrun.WorkflowNameValidator is a validator for the "workflow_name" field. It is called by the builders before save.
	workflowrun.WorkflowNameValidator = workflowrunDescWorkflowName.Validators[0].(func(string) error)
	// workflowrunDescTotalSteps is the schema descriptor for total_steps field.
	workflowrunDescTotalSteps := workflowrunFields[4].Descriptor()
	// workflowrun.DefaultTotalSteps holds the default value on creation for the total_steps field.
	workflowrun.DefaultTotalSteps = workflowrunDescTotalSteps.Default.(int)
	// workflowrunDescCompletedSteps is the schema descriptor for completed_steps field.
	workflowrunDescCompletedSteps := workflowrunFields[5].Descriptor()
	// workflowrun.DefaultCompletedSteps holds the default value on creation for the completed_steps field.
	workflowrun.DefaultCompletedSteps = workflowrunDescCompletedSteps.Default.(int)
	// workflowrunDescStartedAt is the schema descriptor for started_at field.
	workflowrunDescStartedAt := workflowrunFields[7].Descriptor()
	// workflowrun.DefaultStartedAt holds the default value on creation for the started_at field.
	workflowrun.DefaultStartedAt = workflowrunDescStartedAt.Default.(func() time.Time)
	// workflowrunDescID is the schema descriptor for id field.
	workflowrunDescID := workflowrunFields[0].Descriptor()
	// workflowrun.DefaultID holds the default value on creation for the id field.
	workflowrun.DefaultID = workflowrunDescID.Default.(func() uuid.UUID)
	workflowsteprunFields := schema.WorkflowStepRun{}.Fields()
	_ = workflowsteprunFields
	// workflowsteprunDescStepID is the schema descriptor for step_id field.
	workflowsteprunDescStepID := workflowsteprunFields[2].Descriptor()
	// workflowsteprun.StepIDValidator is a validator for the "step_id" field. It is called by the builders before save.
	workflowsteprun.StepIDValidator = workflowsteprunDescStepID.Validators[0].(func(string) error)
	// workflowsteprunDescID is the schema descriptor for id field.
	workflowsteprunDescID := workflowsteprunFields[0].Descriptor()
	// workflowsteprun.DefaultID holds the default value on creation for the id field.
	workflowsteprun.DefaultID = workflowsteprunDescID.Default.(func() uuid.UUID)
}
