// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/sessionprovenance"
)

// SessionProvenance is the model entity for the SessionProvenance schema.
type SessionProvenance struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Unique session key
	SessionKey string `json:"session_key,omitempty"`
	// Parent session key for tree hierarchy
	ParentKey string `json:"parent_key,omitempty"`
	// Name of the agent that owns this session
	AgentName string `json:"agent_name,omitempty"`
	// Session goal or task description
	Goal string `json:"goal,omitempty"`
	// Associated RunLedger run ID
	RunID string `json:"run_id,omitempty"`
	// Associated workspace ID
	WorkspaceID string `json:"workspace_id,omitempty"`
	// Depth in the session tree (root = 0)
	Depth int `json:"depth,omitempty"`
	// Session lifecycle status
	Status sessionprovenance.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// When the session was closed (merged/discarded/completed)
	ClosedAt     *time.Time `json:"closed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SessionProvenance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sessionprovenance.FieldDepth:
			values[i] = new(sql.NullInt64)
		case sessionprovenance.FieldSessionKey, sessionprovenance.FieldParentKey, sessionprovenance.FieldAgentName, sessionprovenance.FieldGoal, sessionprovenance.FieldRunID, sessionprovenance.FieldWorkspaceID, sessionprovenance.FieldStatus:
			values[i] = new(sql.NullString)
		case sessionprovenance.FieldCreatedAt, sessionprovenance.FieldClosedAt:
			values[i] = new(sql.NullTime)
		case sessionprovenance.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SessionProvenance fields.
func (_m *SessionProvenance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sessionprovenance.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case sessionprovenance.FieldSessionKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_key", values[i])
			} else if value.Valid {
				_m.SessionKey = value.String
			}
		case sessionprovenance.FieldParentKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_key", values[i])
			} else if value.Valid {
				_m.ParentKey = value.String
			}
		case sessionprovenance.FieldAgentName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_name", values[i])
			} else if value.Valid {
				_m.AgentName = value.String
			}
		case sessionprovenance.FieldGoal:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field goal", values[i])
			} else if value.Valid {
				_m.Goal = value.String
			}
		case sessionprovenance.FieldRunID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value.Valid {
				_m.RunID = value.String
			}
		case sessionprovenance.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				_m.WorkspaceID = value.String
			}
		case sessionprovenance.FieldDepth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field depth", values[i])
			} else if value.Valid {
				_m.Depth = int(value.Int64)
			}
		case sessionprovenance.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = sessionprovenance.Status(value.String)
			}
		case sessionprovenance.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sessionprovenance.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SessionProvenance.
// This includes values selected through modifiers, order, etc.
func (_m *SessionProvenance) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SessionProvenance.
// Note that you need to call SessionProvenance.Unwrap() before calling this method if this SessionProvenance
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SessionProvenance) Update() *SessionProvenanceUpdateOne {
	return NewSessionProvenanceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SessionProvenance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SessionProvenance) Unwrap() *SessionProvenance {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SessionProvenance is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SessionProvenance) String() string {
	var builder strings.Builder
	builder.WriteString("SessionProvenance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_key=")
	builder.WriteString(_m.SessionKey)
	builder.WriteString(", ")
	builder.WriteString("parent_key=")
	builder.WriteString(_m.ParentKey)
	builder.WriteString(", ")
	builder.WriteString("agent_name=")
	builder.WriteString(_m.AgentName)
	builder.WriteString(", ")
	builder.WriteString("goal=")
	builder.WriteString(_m.Goal)
	builder.WriteString(", ")
	builder.WriteString("run_id=")
	builder.WriteString(_m.RunID)
	builder.WriteString(", ")
	builder.WriteString("workspace_id=")
	builder.WriteString(_m.WorkspaceID)
	builder.WriteString(", ")
	builder.WriteString("depth=")
	builder.WriteString(fmt.Sprintf("%v", _m.Depth))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SessionProvenances is a parsable slice of SessionProvenance.
type SessionProvenances []*SessionProvenance
