// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/tokenusage"
)

// TokenUsage is the model entity for the TokenUsage schema.
type TokenUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SessionKey holds the value of the "session_key" field.
	SessionKey string `json:"session_key,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// AgentName holds the value of the "agent_name" field.
	AgentName string `json:"agent_name,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int64 `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int64 `json:"output_tokens,omitempty"`
	// TotalTokens holds the value of the "total_tokens" field.
	TotalTokens int64 `json:"total_tokens,omitempty"`
	// CacheTokens holds the value of the "cache_tokens" field.
	CacheTokens int64 `json:"cache_tokens,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp    time.Time `json:"timestamp,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TokenUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tokenusage.FieldInputTokens, tokenusage.FieldOutputTokens, tokenusage.FieldTotalTokens, tokenusage.FieldCacheTokens:
			values[i] = new(sql.NullInt64)
		case tokenusage.FieldSessionKey, tokenusage.FieldProvider, tokenusage.FieldModel, tokenusage.FieldAgentName:
			values[i] = new(sql.NullString)
		case tokenusage.FieldTimestamp:
			values[i] = new(sql.NullTime)
		case tokenusage.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TokenUsage fields.
func (_m *TokenUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tokenusage.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case tokenusage.FieldSessionKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_key", values[i])
			} else if value.Valid {
				_m.SessionKey = value.String
			}
		case tokenusage.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case tokenusage.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case tokenusage.FieldAgentName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_name", values[i])
			} else if value.Valid {
				_m.AgentName = value.String
			}
		case tokenusage.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = value.Int64
			}
		case tokenusage.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = value.Int64
			}
		case tokenusage.FieldTotalTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_tokens", values[i])
			} else if value.Valid {
				_m.TotalTokens = value.Int64
			}
		case tokenusage.FieldCacheTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_tokens", values[i])
			} else if value.Valid {
				_m.CacheTokens = value.Int64
			}
		case tokenusage.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TokenUsage.
// This includes values selected through modifiers, order, etc.
func (_m *TokenUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TokenUsage.
// Note that you need to call TokenUsage.Unwrap() before calling this method if this TokenUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TokenUsage) Update() *TokenUsageUpdateOne {
	return NewTokenUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TokenUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TokenUsage) Unwrap() *TokenUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TokenUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TokenUsage) String() string {
	var builder strings.Builder
	builder.WriteString("TokenUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_key=")
	builder.WriteString(_m.SessionKey)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("agent_name=")
	builder.WriteString(_m.AgentName)
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("total_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheTokens))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TokenUsages is a parsable slice of TokenUsage.
type TokenUsages []*TokenUsage
