// Code generated by ent, DO NOT EDIT.

package escrowdeal

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the escrowdeal type in the database.
	Label = "escrow_deal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEscrowID holds the string denoting the escrow_id field in the database.
	FieldEscrowID = "escrow_id"
	// FieldBuyerDid holds the string denoting the buyer_did field in the database.
	FieldBuyerDid = "buyer_did"
	// FieldSellerDid holds the string denoting the seller_did field in the database.
	FieldSellerDid = "seller_did"
	// FieldTotalAmount holds the string denoting the total_amount field in the database.
	FieldTotalAmount = "total_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMilestones holds the string denoting the milestones field in the database.
	FieldMilestones = "milestones"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldDisputeNote holds the string denoting the dispute_note field in the database.
	FieldDisputeNote = "dispute_note"
	// FieldChainID holds the string denoting the chain_id field in the database.
	FieldChainID = "chain_id"
	// FieldHubAddress holds the string denoting the hub_address field in the database.
	FieldHubAddress = "hub_address"
	// FieldOnChainDealID holds the string denoting the on_chain_deal_id field in the database.
	FieldOnChainDealID = "on_chain_deal_id"
	// FieldDepositTxHash holds the string denoting the deposit_tx_hash field in the database.
	FieldDepositTxHash = "deposit_tx_hash"
	// FieldReleaseTxHash holds the string denoting the release_tx_hash field in the database.
	FieldReleaseTxHash = "release_tx_hash"
	// FieldRefundTxHash holds the string denoting the refund_tx_hash field in the database.
	FieldRefundTxHash = "refund_tx_hash"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the escrowdeal in the database.
	Table = "escrow_deals"
)

// Columns holds all SQL columns for escrowdeal fields.
var Columns = []string{
	FieldID,
	FieldEscrowID,
	FieldBuyerDid,
	FieldSellerDid,
	FieldTotalAmount,
	FieldStatus,
	FieldMilestones,
	FieldTaskID,
	FieldReason,
	FieldDisputeNote,
	FieldChainID,
	FieldHubAddress,
	FieldOnChainDealID,
	FieldDepositTxHash,
	FieldReleaseTxHash,
	FieldRefundTxHash,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EscrowIDValidator is a validator for the "escrow_id" field. It is called by the builders before save.
	EscrowIDValidator func(string) error
	// BuyerDidValidator is a validator for the "buyer_did" field. It is called by the builders before save.
	BuyerDidValidator func(string) error
	// SellerDidValidator is a validator for the "seller_did" field. It is called by the builders before save.
	SellerDidValidator func(string) error
	// TotalAmountValidator is a validator for the "total_amount" field. It is called by the builders before save.
	TotalAmountValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultChainID holds the default value on creation for the "chain_id" field.
	DefaultChainID int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the EscrowDeal queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEscrowID orders the results by the escrow_id field.
func ByEscrowID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEscrowID, opts...).ToFunc()
}

// ByBuyerDid orders the results by the buyer_did field.
func ByBuyerDid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerDid, opts...).ToFunc()
}

// BySellerDid orders the results by the seller_did field.
func BySellerDid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellerDid, opts...).ToFunc()
}

// ByTotalAmount orders the results by the total_amount field.
func ByTotalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByDisputeNote orders the results by the dispute_note field.
func ByDisputeNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisputeNote, opts...).ToFunc()
}

// ByChainID orders the results by the chain_id field.
func ByChainID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChainID, opts...).ToFunc()
}

// ByHubAddress orders the results by the hub_address field.
func ByHubAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHubAddress, opts...).ToFunc()
}

// ByOnChainDealID orders the results by the on_chain_deal_id field.
func ByOnChainDealID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOnChainDealID, opts...).ToFunc()
}

// ByDepositTxHash orders the results by the deposit_tx_hash field.
func ByDepositTxHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepositTxHash, opts...).ToFunc()
}

// ByReleaseTxHash orders the results by the release_tx_hash field.
func ByReleaseTxHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseTxHash, opts...).ToFunc()
}

// ByRefundTxHash orders the results by the refund_tx_hash field.
func ByRefundTxHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundTxHash, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
