// Code generated by ent, DO NOT EDIT.

package turntraceevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the turntraceevent type in the database.
	Label = "turn_trace_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTraceID holds the string denoting the trace_id field in the database.
	FieldTraceID = "trace_id"
	// FieldSeq holds the string denoting the seq field in the database.
	FieldSeq = "seq"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldAgentName holds the string denoting the agent_name field in the database.
	FieldAgentName = "agent_name"
	// FieldToolName holds the string denoting the tool_name field in the database.
	FieldToolName = "tool_name"
	// FieldCallSignature holds the string denoting the call_signature field in the database.
	FieldCallSignature = "call_signature"
	// FieldPayloadJSON holds the string denoting the payload_json field in the database.
	FieldPayloadJSON = "payload_json"
	// FieldPayloadTruncated holds the string denoting the payload_truncated field in the database.
	FieldPayloadTruncated = "payload_truncated"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the turntraceevent in the database.
	Table = "turn_trace_events"
)

// Columns holds all SQL columns for turntraceevent fields.
var Columns = []string{
	FieldID,
	FieldTraceID,
	FieldSeq,
	FieldEventType,
	FieldAgentName,
	FieldToolName,
	FieldCallSignature,
	FieldPayloadJSON,
	FieldPayloadTruncated,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TraceIDValidator is a validator for the "trace_id" field. It is called by the builders before save.
	TraceIDValidator func(string) error
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// DefaultPayloadTruncated holds the default value on creation for the "payload_truncated" field.
	DefaultPayloadTruncated bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the TurnTraceEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTraceID orders the results by the trace_id field.
func ByTraceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTraceID, opts...).ToFunc()
}

// BySeq orders the results by the seq field.
func BySeq(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeq, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByAgentName orders the results by the agent_name field.
func ByAgentName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentName, opts...).ToFunc()
}

// ByToolName orders the results by the tool_name field.
func ByToolName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToolName, opts...).ToFunc()
}

// ByCallSignature orders the results by the call_signature field.
func ByCallSignature(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCallSignature, opts...).ToFunc()
}

// ByPayloadJSON orders the results by the payload_json field.
func ByPayloadJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadJSON, opts...).ToFunc()
}

// ByPayloadTruncated orders the results by the payload_truncated field.
func ByPayloadTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadTruncated, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
