//go:build linux

package os

import (
	"context"
	"fmt"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// BwrapIsolator wraps exec.Cmd with bubblewrap (bwrap) on Linux to provide
// process-level isolation: filesystem bind mounts (read-only root + writable
// workspace), network unshare, and PID/IPC/UTS/cgroup namespaces.
//
// The absolute bwrap path is captured at probe time (NewBwrapIsolator) and
// reused at Apply time so that PATH or working-directory changes between
// probe and execution cannot redirect to a different binary.
//
// Availability is determined by a two-phase smoke probe:
//
//  1. Base probe — reuses compileBwrapArgs with a read-only-global +
//     NetworkAllow policy (matching MCPServerPolicy's network model) to
//     verify the pid/ipc/uts/cgroup namespaces and root ro-bind that every
//     lango policy requires. Failure marks the whole isolator unavailable.
//  2. Network probe — additionally runs a NetworkDeny policy through
//     compileBwrapArgs to verify --unshare-net works. Failure does NOT
//     mark the isolator unavailable; instead, it downgrades Apply() so
//     that only NetworkDeny/NetworkUnixOnly policies are rejected,
//     while NetworkAllow policies (e.g. MCPServerPolicy) still succeed.
//
// This two-phase design keeps the probe argv in lockstep with the runtime
// argv (zero drift because both go through compileBwrapArgs) while
// preventing a host that blocks --unshare-net from false-negating MCP.
type BwrapIsolator struct {
	available              bool
	reason                 string
	version                string
	resolvedPath           string
	networkIsolation       bool
	networkIsolationReason string
}

// Compile-time interface compliance check.
var _ OSIsolator = (*BwrapIsolator)(nil)

// bwrapSmokeProbeTimeout bounds a single bwrap smoke probe invocation.
// The probe runs /bin/true inside a minimal sandbox; normal environments
// finish in < 100ms, and 2 seconds leaves ample headroom while bounding
// startup hangs on pathological hosts.
const bwrapSmokeProbeTimeout = 2 * time.Second

// NewBwrapIsolator probes the system for bwrap and returns an isolator that
// either reports availability with a captured absolute path + version, or is
// unavailable with a human-readable reason. See the BwrapIsolator doc comment
// for the two-phase probe contract.
func NewBwrapIsolator() OSIsolator {
	path, err := exec.LookPath("bwrap")
	if err != nil {
		return &BwrapIsolator{
			reason: "bwrap binary not found in PATH (install bubblewrap package)",
		}
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		return &BwrapIsolator{
			reason: fmt.Sprintf("resolve absolute bwrap path: %v", err),
		}
	}
	out, err := exec.Command(abs, "--version").Output()
	if err != nil {
		return &BwrapIsolator{
			reason: fmt.Sprintf("bwrap --version failed: %v", err),
		}
	}

	// Phase 1: base smoke probe. Uses the minimum bwrap argv every lango
	// consumer needs (NetworkAllow — matches MCPServerPolicy). Failure
	// here means bwrap cannot be used for ANY lango policy on this host.
	if err := smokeProbeBwrapBase(abs); err != nil {
		return &BwrapIsolator{
			reason: fmt.Sprintf("bwrap base namespace smoke probe failed: %v "+
				"(check kernel.unprivileged_userns_clone, AppArmor lockdown, "+
				"or install bubblewrap as setuid-root)", err),
		}
	}

	// Phase 2: network isolation probe. Failure here only downgrades the
	// isolator: Apply() rejects NetworkDeny/NetworkUnixOnly policies,
	// while NetworkAllow policies (e.g. MCP) still succeed.
	b := &BwrapIsolator{
		available:    true,
		version:      strings.TrimSpace(string(out)),
		resolvedPath: abs,
	}
	if netErr := smokeProbeBwrapNetwork(abs); netErr == nil {
		b.networkIsolation = true
	} else {
		b.networkIsolationReason = fmt.Sprintf(
			"bwrap network isolation probe failed: %v "+
				"(NetworkDeny/NetworkUnixOnly policies will be rejected by Apply; "+
				"NetworkAllow policies such as MCP are unaffected)", netErr)
	}
	return b
}

// smokeProbeBwrapBase runs the minimum bwrap invocation every lango policy
// requires: pid/ipc/uts/cgroup namespace + root ro-bind, no network isolation.
// Uses NetworkAllow so MCPServerPolicy (which also uses NetworkAllow) is the
// probe's exact lower bound. The argv is generated by compileBwrapArgs so
// probe and runtime cannot drift — whatever flags runtime adds, probe
// automatically picks them up through the shared builder.
func smokeProbeBwrapBase(abs string) error {
	basePolicy := Policy{
		Filesystem: FilesystemPolicy{ReadOnlyGlobal: true},
		Network:    NetworkAllow,
		Process:    ProcessPolicy{AllowFork: true, AllowSignals: false},
	}
	args, err := compileBwrapArgs(basePolicy)
	if err != nil {
		return fmt.Errorf("compile base probe args: %w", err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), bwrapSmokeProbeTimeout)
	defer cancel()
	fullArgs := append(args, "--", "/bin/true")
	return exec.CommandContext(ctx, abs, fullArgs...).Run()
}

// smokeProbeBwrapNetwork additionally tests --unshare-net. Matches
// DefaultToolPolicy (NetworkDeny). Failure here is a partial degradation:
// Apply() rejects NetworkDeny/NetworkUnixOnly policies with an actionable
// error, while MCP (NetworkAllow) keeps working.
func smokeProbeBwrapNetwork(abs string) error {
	netPolicy := Policy{
		Filesystem: FilesystemPolicy{ReadOnlyGlobal: true},
		Network:    NetworkDeny,
		Process:    ProcessPolicy{AllowFork: true, AllowSignals: false},
	}
	args, err := compileBwrapArgs(netPolicy)
	if err != nil {
		return fmt.Errorf("compile network probe args: %w", err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), bwrapSmokeProbeTimeout)
	defer cancel()
	fullArgs := append(args, "--", "/bin/true")
	return exec.CommandContext(ctx, abs, fullArgs...).Run()
}

// Apply rewrites cmd to run inside bwrap with arguments compiled from policy.
// The original argv becomes the child program after the bwrap "--" separator.
//
// Apply-time network gate: if the probe could not verify --unshare-net, the
// isolator rejects NetworkDeny/NetworkUnixOnly policies with an
// ErrIsolatorUnavailable-wrapped error BEFORE mutating cmd. NetworkAllow
// policies proceed normally — partial degradation does not affect consumers
// that do not require network isolation.
func (b *BwrapIsolator) Apply(_ context.Context, cmd *exec.Cmd, policy Policy) error {
	if !b.available {
		return ErrIsolatorUnavailable
	}
	if (policy.Network == NetworkDeny || policy.Network == NetworkUnixOnly) && !b.networkIsolation {
		return fmt.Errorf("%w: %s", ErrIsolatorUnavailable, b.networkIsolationReason)
	}
	args, err := compileBwrapArgs(policy)
	if err != nil {
		return fmt.Errorf("compile bwrap args: %w", err)
	}

	originalArgs := cmd.Args
	// Use the absolute path captured at probe time, NOT the bare "bwrap" string.
	// This guarantees probe-time and exec-time refer to the same binary even if
	// PATH or cwd changes between Apply() and cmd.Run().
	cmd.Path = b.resolvedPath
	cmd.Args = append(append([]string{b.resolvedPath}, args...), append([]string{"--"}, originalArgs...)...)
	return nil
}

func (b *BwrapIsolator) Available() bool { return b.available }
func (b *BwrapIsolator) Name() string    { return "bwrap" }

func (b *BwrapIsolator) Reason() string {
	if b.available {
		return ""
	}
	return b.reason
}

// Version returns the captured `bwrap --version` string, or "" when the
// isolator is unavailable. CLI surfaces (e.g. `lango sandbox test`) can
// type-assert to a versioner interface to display this.
func (b *BwrapIsolator) Version() string { return b.version }

// NetworkIsolationAvailable reports whether the network smoke probe verified
// that --unshare-net works on this host. When false, Apply() rejects
// NetworkDeny/NetworkUnixOnly policies. NetworkAllow policies are unaffected.
// Available()==true does not imply network isolation availability; consumers
// that require network isolation should check this method separately.
func (b *BwrapIsolator) NetworkIsolationAvailable() bool { return b.networkIsolation }

// NetworkIsolationReason returns the diagnostic message when network isolation
// is unavailable. Empty when NetworkIsolationAvailable()==true. The primary
// Reason() method (from the OSIsolator interface) remains empty whenever
// Available()==true, preserving the existing spec contract that partial
// degradation is surfaced only through the dedicated network methods.
func (b *BwrapIsolator) NetworkIsolationReason() string {
	if b.networkIsolation {
		return ""
	}
	return b.networkIsolationReason
}
