// Code generated by ent, DO NOT EDIT.

package ontologypredicate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldDescription, v))
}

// Inverse applies equality check predicate on the "inverse" field. It's identical to InverseEQ.
func Inverse(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldInverse, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldContainsFold(FieldDescription, v))
}

// SourceTypesIsNil applies the IsNil predicate on the "source_types" field.
func SourceTypesIsNil() predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldIsNull(FieldSourceTypes))
}

// SourceTypesNotNil applies the NotNil predicate on the "source_types" field.
func SourceTypesNotNil() predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNotNull(FieldSourceTypes))
}

// TargetTypesIsNil applies the IsNil predicate on the "target_types" field.
func TargetTypesIsNil() predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldIsNull(FieldTargetTypes))
}

// TargetTypesNotNil applies the NotNil predicate on the "target_types" field.
func TargetTypesNotNil() predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNotNull(FieldTargetTypes))
}

// CardinalityEQ applies the EQ predicate on the "cardinality" field.
func CardinalityEQ(v Cardinality) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldCardinality, v))
}

// CardinalityNEQ applies the NEQ predicate on the "cardinality" field.
func CardinalityNEQ(v Cardinality) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNEQ(FieldCardinality, v))
}

// CardinalityIn applies the In predicate on the "cardinality" field.
func CardinalityIn(vs ...Cardinality) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldIn(FieldCardinality, vs...))
}

// CardinalityNotIn applies the NotIn predicate on the "cardinality" field.
func CardinalityNotIn(vs ...Cardinality) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNotIn(FieldCardinality, vs...))
}

// InverseEQ applies the EQ predicate on the "inverse" field.
func InverseEQ(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldInverse, v))
}

// InverseNEQ applies the NEQ predicate on the "inverse" field.
func InverseNEQ(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNEQ(FieldInverse, v))
}

// InverseIn applies the In predicate on the "inverse" field.
func InverseIn(vs ...string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldIn(FieldInverse, vs...))
}

// InverseNotIn applies the NotIn predicate on the "inverse" field.
func InverseNotIn(vs ...string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNotIn(FieldInverse, vs...))
}

// InverseGT applies the GT predicate on the "inverse" field.
func InverseGT(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldGT(FieldInverse, v))
}

// InverseGTE applies the GTE predicate on the "inverse" field.
func InverseGTE(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldGTE(FieldInverse, v))
}

// InverseLT applies the LT predicate on the "inverse" field.
func InverseLT(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldLT(FieldInverse, v))
}

// InverseLTE applies the LTE predicate on the "inverse" field.
func InverseLTE(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldLTE(FieldInverse, v))
}

// InverseContains applies the Contains predicate on the "inverse" field.
func InverseContains(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldContains(FieldInverse, v))
}

// InverseHasPrefix applies the HasPrefix predicate on the "inverse" field.
func InverseHasPrefix(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldHasPrefix(FieldInverse, v))
}

// InverseHasSuffix applies the HasSuffix predicate on the "inverse" field.
func InverseHasSuffix(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldHasSuffix(FieldInverse, v))
}

// InverseIsNil applies the IsNil predicate on the "inverse" field.
func InverseIsNil() predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldIsNull(FieldInverse))
}

// InverseNotNil applies the NotNil predicate on the "inverse" field.
func InverseNotNil() predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNotNull(FieldInverse))
}

// InverseEqualFold applies the EqualFold predicate on the "inverse" field.
func InverseEqualFold(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEqualFold(FieldInverse, v))
}

// InverseContainsFold applies the ContainsFold predicate on the "inverse" field.
func InverseContainsFold(v string) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldContainsFold(FieldInverse, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNotIn(FieldStatus, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldLTE(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OntologyPredicate) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OntologyPredicate) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OntologyPredicate) predicate.OntologyPredicate {
	return predicate.OntologyPredicate(sql.NotPredicates(p))
}
