// Code generated by ent, DO NOT EDIT.

package agentmemory

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the agentmemory type in the database.
	Label = "agent_memory"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAgentName holds the string denoting the agent_name field in the database.
	FieldAgentName = "agent_name"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldConfidence holds the string denoting the confidence field in the database.
	FieldConfidence = "confidence"
	// FieldUseCount holds the string denoting the use_count field in the database.
	FieldUseCount = "use_count"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the agentmemory in the database.
	Table = "agent_memories"
)

// Columns holds all SQL columns for agentmemory fields.
var Columns = []string{
	FieldID,
	FieldAgentName,
	FieldScope,
	FieldKind,
	FieldKey,
	FieldContent,
	FieldConfidence,
	FieldUseCount,
	FieldTags,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AgentNameValidator is a validator for the "agent_name" field. It is called by the builders before save.
	AgentNameValidator func(string) error
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// DefaultConfidence holds the default value on creation for the "confidence" field.
	DefaultConfidence float64
	// DefaultUseCount holds the default value on creation for the "use_count" field.
	DefaultUseCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Scope defines the type for the "scope" enum field.
type Scope string

// Scope values.
const (
	ScopeInstance Scope = "instance"
	ScopeGlobal   Scope = "global"
)

func (s Scope) String() string {
	return string(s)
}

// ScopeValidator is a validator for the "scope" field enum values. It is called by the builders before save.
func ScopeValidator(s Scope) error {
	switch s {
	case ScopeInstance, ScopeGlobal:
		return nil
	default:
		return fmt.Errorf("agentmemory: invalid enum value for scope field: %q", s)
	}
}

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindPattern    Kind = "pattern"
	KindPreference Kind = "preference"
	KindFact       Kind = "fact"
	KindSkill      Kind = "skill"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindPattern, KindPreference, KindFact, KindSkill:
		return nil
	default:
		return fmt.Errorf("agentmemory: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the AgentMemory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAgentName orders the results by the agent_name field.
func ByAgentName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentName, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByConfidence orders the results by the confidence field.
func ByConfidence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfidence, opts...).ToFunc()
}

// ByUseCount orders the results by the use_count field.
func ByUseCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUseCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
