// Code generated by ent, DO NOT EDIT.

package entityalias

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the entityalias type in the database.
	Label = "entity_alias"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRawID holds the string denoting the raw_id field in the database.
	FieldRawID = "raw_id"
	// FieldCanonicalID holds the string denoting the canonical_id field in the database.
	FieldCanonicalID = "canonical_id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the entityalias in the database.
	Table = "entity_alias"
)

// Columns holds all SQL columns for entityalias fields.
var Columns = []string{
	FieldID,
	FieldRawID,
	FieldCanonicalID,
	FieldSource,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RawIDValidator is a validator for the "raw_id" field. It is called by the builders before save.
	RawIDValidator func(string) error
	// CanonicalIDValidator is a validator for the "canonical_id" field. It is called by the builders before save.
	CanonicalIDValidator func(string) error
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the EntityAlias queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRawID orders the results by the raw_id field.
func ByRawID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawID, opts...).ToFunc()
}

// ByCanonicalID orders the results by the canonical_id field.
func ByCanonicalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanonicalID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
