// Code generated by ent, DO NOT EDIT.

package actionlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/langoai/lango/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldLTE(FieldID, id))
}

// ActionName applies equality check predicate on the "action_name" field. It's identical to ActionNameEQ.
func ActionName(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEQ(FieldActionName, v))
}

// Principal applies equality check predicate on the "principal" field. It's identical to PrincipalEQ.
func Principal(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEQ(FieldPrincipal, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEQ(FieldErrorMessage, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEQ(FieldCompletedAt, v))
}

// ActionNameEQ applies the EQ predicate on the "action_name" field.
func ActionNameEQ(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEQ(FieldActionName, v))
}

// ActionNameNEQ applies the NEQ predicate on the "action_name" field.
func ActionNameNEQ(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNEQ(FieldActionName, v))
}

// ActionNameIn applies the In predicate on the "action_name" field.
func ActionNameIn(vs ...string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldIn(FieldActionName, vs...))
}

// ActionNameNotIn applies the NotIn predicate on the "action_name" field.
func ActionNameNotIn(vs ...string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNotIn(FieldActionName, vs...))
}

// ActionNameGT applies the GT predicate on the "action_name" field.
func ActionNameGT(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldGT(FieldActionName, v))
}

// ActionNameGTE applies the GTE predicate on the "action_name" field.
func ActionNameGTE(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldGTE(FieldActionName, v))
}

// ActionNameLT applies the LT predicate on the "action_name" field.
func ActionNameLT(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldLT(FieldActionName, v))
}

// ActionNameLTE applies the LTE predicate on the "action_name" field.
func ActionNameLTE(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldLTE(FieldActionName, v))
}

// ActionNameContains applies the Contains predicate on the "action_name" field.
func ActionNameContains(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldContains(FieldActionName, v))
}

// ActionNameHasPrefix applies the HasPrefix predicate on the "action_name" field.
func ActionNameHasPrefix(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldHasPrefix(FieldActionName, v))
}

// ActionNameHasSuffix applies the HasSuffix predicate on the "action_name" field.
func ActionNameHasSuffix(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldHasSuffix(FieldActionName, v))
}

// ActionNameEqualFold applies the EqualFold predicate on the "action_name" field.
func ActionNameEqualFold(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEqualFold(FieldActionName, v))
}

// ActionNameContainsFold applies the ContainsFold predicate on the "action_name" field.
func ActionNameContainsFold(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldContainsFold(FieldActionName, v))
}

// PrincipalEQ applies the EQ predicate on the "principal" field.
func PrincipalEQ(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEQ(FieldPrincipal, v))
}

// PrincipalNEQ applies the NEQ predicate on the "principal" field.
func PrincipalNEQ(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNEQ(FieldPrincipal, v))
}

// PrincipalIn applies the In predicate on the "principal" field.
func PrincipalIn(vs ...string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldIn(FieldPrincipal, vs...))
}

// PrincipalNotIn applies the NotIn predicate on the "principal" field.
func PrincipalNotIn(vs ...string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNotIn(FieldPrincipal, vs...))
}

// PrincipalGT applies the GT predicate on the "principal" field.
func PrincipalGT(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldGT(FieldPrincipal, v))
}

// PrincipalGTE applies the GTE predicate on the "principal" field.
func PrincipalGTE(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldGTE(FieldPrincipal, v))
}

// PrincipalLT applies the LT predicate on the "principal" field.
func PrincipalLT(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldLT(FieldPrincipal, v))
}

// PrincipalLTE applies the LTE predicate on the "principal" field.
func PrincipalLTE(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldLTE(FieldPrincipal, v))
}

// PrincipalContains applies the Contains predicate on the "principal" field.
func PrincipalContains(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldContains(FieldPrincipal, v))
}

// PrincipalHasPrefix applies the HasPrefix predicate on the "principal" field.
func PrincipalHasPrefix(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldHasPrefix(FieldPrincipal, v))
}

// PrincipalHasSuffix applies the HasSuffix predicate on the "principal" field.
func PrincipalHasSuffix(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldHasSuffix(FieldPrincipal, v))
}

// PrincipalEqualFold applies the EqualFold predicate on the "principal" field.
func PrincipalEqualFold(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEqualFold(FieldPrincipal, v))
}

// PrincipalContainsFold applies the ContainsFold predicate on the "principal" field.
func PrincipalContainsFold(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldContainsFold(FieldPrincipal, v))
}

// ParamsIsNil applies the IsNil predicate on the "params" field.
func ParamsIsNil() predicate.ActionLog {
	return predicate.ActionLog(sql.FieldIsNull(FieldParams))
}

// ParamsNotNil applies the NotNil predicate on the "params" field.
func ParamsNotNil() predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNotNull(FieldParams))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNotIn(FieldStatus, vs...))
}

// EffectsIsNil applies the IsNil predicate on the "effects" field.
func EffectsIsNil() predicate.ActionLog {
	return predicate.ActionLog(sql.FieldIsNull(FieldEffects))
}

// EffectsNotNil applies the NotNil predicate on the "effects" field.
func EffectsNotNil() predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNotNull(FieldEffects))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.ActionLog {
	return predicate.ActionLog(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldContainsFold(FieldErrorMessage, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldLTE(FieldStartedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.ActionLog {
	return predicate.ActionLog(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.ActionLog {
	return predicate.ActionLog(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.ActionLog {
	return predicate.ActionLog(sql.FieldNotNull(FieldCompletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ActionLog) predicate.ActionLog {
	return predicate.ActionLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ActionLog) predicate.ActionLog {
	return predicate.ActionLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ActionLog) predicate.ActionLog {
	return predicate.ActionLog(sql.NotPredicates(p))
}
